// Generated by jextract

package org.ros2.rcl.srv;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * struct rcutils_sha256_ctx_s {
 *     uint8_t data[64];
 *     size_t datalen;
 *     uint64_t bitlen;
 *     uint32_t state[8];
 * }
 * }
 */
public class rcutils_sha256_ctx_s {

    rcutils_sha256_ctx_s() {
        // Should not be called directly
    }

    private static final GroupLayout $LAYOUT = MemoryLayout.structLayout(
        MemoryLayout.sequenceLayout(64, StdSrvs_Lib.C_CHAR).withName("data"),
        StdSrvs_Lib.C_LONG.withName("datalen"),
        StdSrvs_Lib.C_LONG.withName("bitlen"),
        MemoryLayout.sequenceLayout(8, StdSrvs_Lib.C_INT).withName("state")
    ).withName("rcutils_sha256_ctx_s");

    /**
     * The layout of this struct
     */
    public static final GroupLayout layout() {
        return $LAYOUT;
    }

    private static final SequenceLayout data$LAYOUT = (SequenceLayout)$LAYOUT.select(groupElement("data"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * uint8_t data[64]
     * }
     */
    public static final SequenceLayout data$layout() {
        return data$LAYOUT;
    }

    private static final long data$OFFSET = $LAYOUT.byteOffset(groupElement("data"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * uint8_t data[64]
     * }
     */
    public static final long data$offset() {
        return data$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * uint8_t data[64]
     * }
     */
    public static MemorySegment data(MemorySegment struct) {
        return struct.asSlice(data$OFFSET, data$LAYOUT.byteSize());
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * uint8_t data[64]
     * }
     */
    public static void data(MemorySegment struct, MemorySegment fieldValue) {
        MemorySegment.copy(fieldValue, 0L, struct, data$OFFSET, data$LAYOUT.byteSize());
    }

    private static long[] data$DIMS = { 64 };

    /**
     * Dimensions for array field:
     * {@snippet lang=c :
     * uint8_t data[64]
     * }
     */
    public static long[] data$dimensions() {
        return data$DIMS;
    }
    private static final VarHandle data$ELEM_HANDLE = data$LAYOUT.varHandle(sequenceElement());

    /**
     * Indexed getter for field:
     * {@snippet lang=c :
     * uint8_t data[64]
     * }
     */
    public static byte data(MemorySegment struct, long index0) {
        return (byte)data$ELEM_HANDLE.get(struct, data$OFFSET, index0);
    }

    /**
     * Indexed setter for field:
     * {@snippet lang=c :
     * uint8_t data[64]
     * }
     */
    public static void data(MemorySegment struct, long index0, byte fieldValue) {
        data$ELEM_HANDLE.set(struct, data$OFFSET, index0, fieldValue);
    }

    private static final OfLong datalen$LAYOUT = (OfLong)$LAYOUT.select(groupElement("datalen"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * size_t datalen
     * }
     */
    public static final OfLong datalen$layout() {
        return datalen$LAYOUT;
    }

    private static final long datalen$OFFSET = $LAYOUT.byteOffset(groupElement("datalen"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * size_t datalen
     * }
     */
    public static final long datalen$offset() {
        return datalen$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * size_t datalen
     * }
     */
    public static long datalen(MemorySegment struct) {
        return struct.get(datalen$LAYOUT, datalen$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * size_t datalen
     * }
     */
    public static void datalen(MemorySegment struct, long fieldValue) {
        struct.set(datalen$LAYOUT, datalen$OFFSET, fieldValue);
    }

    private static final OfLong bitlen$LAYOUT = (OfLong)$LAYOUT.select(groupElement("bitlen"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * uint64_t bitlen
     * }
     */
    public static final OfLong bitlen$layout() {
        return bitlen$LAYOUT;
    }

    private static final long bitlen$OFFSET = $LAYOUT.byteOffset(groupElement("bitlen"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * uint64_t bitlen
     * }
     */
    public static final long bitlen$offset() {
        return bitlen$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * uint64_t bitlen
     * }
     */
    public static long bitlen(MemorySegment struct) {
        return struct.get(bitlen$LAYOUT, bitlen$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * uint64_t bitlen
     * }
     */
    public static void bitlen(MemorySegment struct, long fieldValue) {
        struct.set(bitlen$LAYOUT, bitlen$OFFSET, fieldValue);
    }

    private static final SequenceLayout state$LAYOUT = (SequenceLayout)$LAYOUT.select(groupElement("state"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * uint32_t state[8]
     * }
     */
    public static final SequenceLayout state$layout() {
        return state$LAYOUT;
    }

    private static final long state$OFFSET = $LAYOUT.byteOffset(groupElement("state"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * uint32_t state[8]
     * }
     */
    public static final long state$offset() {
        return state$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * uint32_t state[8]
     * }
     */
    public static MemorySegment state(MemorySegment struct) {
        return struct.asSlice(state$OFFSET, state$LAYOUT.byteSize());
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * uint32_t state[8]
     * }
     */
    public static void state(MemorySegment struct, MemorySegment fieldValue) {
        MemorySegment.copy(fieldValue, 0L, struct, state$OFFSET, state$LAYOUT.byteSize());
    }

    private static long[] state$DIMS = { 8 };

    /**
     * Dimensions for array field:
     * {@snippet lang=c :
     * uint32_t state[8]
     * }
     */
    public static long[] state$dimensions() {
        return state$DIMS;
    }
    private static final VarHandle state$ELEM_HANDLE = state$LAYOUT.varHandle(sequenceElement());

    /**
     * Indexed getter for field:
     * {@snippet lang=c :
     * uint32_t state[8]
     * }
     */
    public static int state(MemorySegment struct, long index0) {
        return (int)state$ELEM_HANDLE.get(struct, state$OFFSET, index0);
    }

    /**
     * Indexed setter for field:
     * {@snippet lang=c :
     * uint32_t state[8]
     * }
     */
    public static void state(MemorySegment struct, long index0, int fieldValue) {
        state$ELEM_HANDLE.set(struct, state$OFFSET, index0, fieldValue);
    }

    /**
     * Obtains a slice of {@code arrayParam} which selects the array element at {@code index}.
     * The returned segment has address {@code arrayParam.address() + index * layout().byteSize()}
     */
    public static MemorySegment asSlice(MemorySegment array, long index) {
        return array.asSlice(layout().byteSize() * index);
    }

    /**
     * The size (in bytes) of this struct
     */
    public static long sizeof() { return layout().byteSize(); }

    /**
     * Allocate a segment of size {@code layout().byteSize()} using {@code allocator}
     */
    public static MemorySegment allocate(SegmentAllocator allocator) {
        return allocator.allocate(layout());
    }

    /**
     * Allocate an array of size {@code elementCount} using {@code allocator}.
     * The returned segment has size {@code elementCount * layout().byteSize()}.
     */
    public static MemorySegment allocateArray(long elementCount, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(elementCount, layout()));
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, Arena arena, Consumer<MemorySegment> cleanup) {
        return reinterpret(addr, 1, arena, cleanup);
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code elementCount * layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, long elementCount, Arena arena, Consumer<MemorySegment> cleanup) {
        return addr.reinterpret(layout().byteSize() * elementCount, arena, cleanup);
    }
}

