// Generated by jextract

package org.ros2.rcl.srv;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * typedef rosidl_runtime_c__float__Sequence rosidl_runtime_c__float32__Sequence
 * }
 */
public class rosidl_runtime_c__float32__Sequence extends rosidl_runtime_c__float__Sequence {

    rosidl_runtime_c__float32__Sequence() {
        // Should not be called directly
    }
}

