// Generated by jextract

package org.ros2.rcl.srv;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * struct rosidl_service_type_support_t {
 *     const char *typesupport_identifier;
 *     const void *data;
 *     rosidl_service_typesupport_handle_function func;
 *     const rosidl_message_type_support_t *request_typesupport;
 *     const rosidl_message_type_support_t *response_typesupport;
 *     const rosidl_message_type_support_t *event_typesupport;
 *     rosidl_event_message_create_handle_function_function event_message_create_handle_function;
 *     rosidl_event_message_destroy_handle_function_function event_message_destroy_handle_function;
 *     rosidl_service_get_type_hash_function get_type_hash_func;
 *     rosidl_service_get_type_description_function get_type_description_func;
 *     rosidl_service_get_type_description_sources_function get_type_description_sources_func;
 * }
 * }
 */
public class rosidl_service_type_support_t {

    rosidl_service_type_support_t() {
        // Should not be called directly
    }

    private static final GroupLayout $LAYOUT = MemoryLayout.structLayout(
        StdSrvs_Lib.C_POINTER.withName("typesupport_identifier"),
        StdSrvs_Lib.C_POINTER.withName("data"),
        StdSrvs_Lib.C_POINTER.withName("func"),
        StdSrvs_Lib.C_POINTER.withName("request_typesupport"),
        StdSrvs_Lib.C_POINTER.withName("response_typesupport"),
        StdSrvs_Lib.C_POINTER.withName("event_typesupport"),
        StdSrvs_Lib.C_POINTER.withName("event_message_create_handle_function"),
        StdSrvs_Lib.C_POINTER.withName("event_message_destroy_handle_function"),
        StdSrvs_Lib.C_POINTER.withName("get_type_hash_func"),
        StdSrvs_Lib.C_POINTER.withName("get_type_description_func"),
        StdSrvs_Lib.C_POINTER.withName("get_type_description_sources_func")
    ).withName("rosidl_service_type_support_t");

    /**
     * The layout of this struct
     */
    public static final GroupLayout layout() {
        return $LAYOUT;
    }

    private static final AddressLayout typesupport_identifier$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("typesupport_identifier"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * const char *typesupport_identifier
     * }
     */
    public static final AddressLayout typesupport_identifier$layout() {
        return typesupport_identifier$LAYOUT;
    }

    private static final long typesupport_identifier$OFFSET = $LAYOUT.byteOffset(groupElement("typesupport_identifier"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * const char *typesupport_identifier
     * }
     */
    public static final long typesupport_identifier$offset() {
        return typesupport_identifier$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * const char *typesupport_identifier
     * }
     */
    public static MemorySegment typesupport_identifier(MemorySegment struct) {
        return struct.get(typesupport_identifier$LAYOUT, typesupport_identifier$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * const char *typesupport_identifier
     * }
     */
    public static void typesupport_identifier(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(typesupport_identifier$LAYOUT, typesupport_identifier$OFFSET, fieldValue);
    }

    private static final AddressLayout data$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("data"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * const void *data
     * }
     */
    public static final AddressLayout data$layout() {
        return data$LAYOUT;
    }

    private static final long data$OFFSET = $LAYOUT.byteOffset(groupElement("data"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * const void *data
     * }
     */
    public static final long data$offset() {
        return data$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * const void *data
     * }
     */
    public static MemorySegment data(MemorySegment struct) {
        return struct.get(data$LAYOUT, data$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * const void *data
     * }
     */
    public static void data(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(data$LAYOUT, data$OFFSET, fieldValue);
    }

    private static final AddressLayout func$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("func"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * rosidl_service_typesupport_handle_function func
     * }
     */
    public static final AddressLayout func$layout() {
        return func$LAYOUT;
    }

    private static final long func$OFFSET = $LAYOUT.byteOffset(groupElement("func"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * rosidl_service_typesupport_handle_function func
     * }
     */
    public static final long func$offset() {
        return func$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * rosidl_service_typesupport_handle_function func
     * }
     */
    public static MemorySegment func(MemorySegment struct) {
        return struct.get(func$LAYOUT, func$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * rosidl_service_typesupport_handle_function func
     * }
     */
    public static void func(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(func$LAYOUT, func$OFFSET, fieldValue);
    }

    private static final AddressLayout request_typesupport$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("request_typesupport"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * const rosidl_message_type_support_t *request_typesupport
     * }
     */
    public static final AddressLayout request_typesupport$layout() {
        return request_typesupport$LAYOUT;
    }

    private static final long request_typesupport$OFFSET = $LAYOUT.byteOffset(groupElement("request_typesupport"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * const rosidl_message_type_support_t *request_typesupport
     * }
     */
    public static final long request_typesupport$offset() {
        return request_typesupport$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * const rosidl_message_type_support_t *request_typesupport
     * }
     */
    public static MemorySegment request_typesupport(MemorySegment struct) {
        return struct.get(request_typesupport$LAYOUT, request_typesupport$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * const rosidl_message_type_support_t *request_typesupport
     * }
     */
    public static void request_typesupport(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(request_typesupport$LAYOUT, request_typesupport$OFFSET, fieldValue);
    }

    private static final AddressLayout response_typesupport$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("response_typesupport"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * const rosidl_message_type_support_t *response_typesupport
     * }
     */
    public static final AddressLayout response_typesupport$layout() {
        return response_typesupport$LAYOUT;
    }

    private static final long response_typesupport$OFFSET = $LAYOUT.byteOffset(groupElement("response_typesupport"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * const rosidl_message_type_support_t *response_typesupport
     * }
     */
    public static final long response_typesupport$offset() {
        return response_typesupport$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * const rosidl_message_type_support_t *response_typesupport
     * }
     */
    public static MemorySegment response_typesupport(MemorySegment struct) {
        return struct.get(response_typesupport$LAYOUT, response_typesupport$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * const rosidl_message_type_support_t *response_typesupport
     * }
     */
    public static void response_typesupport(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(response_typesupport$LAYOUT, response_typesupport$OFFSET, fieldValue);
    }

    private static final AddressLayout event_typesupport$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("event_typesupport"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * const rosidl_message_type_support_t *event_typesupport
     * }
     */
    public static final AddressLayout event_typesupport$layout() {
        return event_typesupport$LAYOUT;
    }

    private static final long event_typesupport$OFFSET = $LAYOUT.byteOffset(groupElement("event_typesupport"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * const rosidl_message_type_support_t *event_typesupport
     * }
     */
    public static final long event_typesupport$offset() {
        return event_typesupport$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * const rosidl_message_type_support_t *event_typesupport
     * }
     */
    public static MemorySegment event_typesupport(MemorySegment struct) {
        return struct.get(event_typesupport$LAYOUT, event_typesupport$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * const rosidl_message_type_support_t *event_typesupport
     * }
     */
    public static void event_typesupport(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(event_typesupport$LAYOUT, event_typesupport$OFFSET, fieldValue);
    }

    private static final AddressLayout event_message_create_handle_function$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("event_message_create_handle_function"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * rosidl_event_message_create_handle_function_function event_message_create_handle_function
     * }
     */
    public static final AddressLayout event_message_create_handle_function$layout() {
        return event_message_create_handle_function$LAYOUT;
    }

    private static final long event_message_create_handle_function$OFFSET = $LAYOUT.byteOffset(groupElement("event_message_create_handle_function"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * rosidl_event_message_create_handle_function_function event_message_create_handle_function
     * }
     */
    public static final long event_message_create_handle_function$offset() {
        return event_message_create_handle_function$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * rosidl_event_message_create_handle_function_function event_message_create_handle_function
     * }
     */
    public static MemorySegment event_message_create_handle_function(MemorySegment struct) {
        return struct.get(event_message_create_handle_function$LAYOUT, event_message_create_handle_function$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * rosidl_event_message_create_handle_function_function event_message_create_handle_function
     * }
     */
    public static void event_message_create_handle_function(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(event_message_create_handle_function$LAYOUT, event_message_create_handle_function$OFFSET, fieldValue);
    }

    private static final AddressLayout event_message_destroy_handle_function$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("event_message_destroy_handle_function"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * rosidl_event_message_destroy_handle_function_function event_message_destroy_handle_function
     * }
     */
    public static final AddressLayout event_message_destroy_handle_function$layout() {
        return event_message_destroy_handle_function$LAYOUT;
    }

    private static final long event_message_destroy_handle_function$OFFSET = $LAYOUT.byteOffset(groupElement("event_message_destroy_handle_function"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * rosidl_event_message_destroy_handle_function_function event_message_destroy_handle_function
     * }
     */
    public static final long event_message_destroy_handle_function$offset() {
        return event_message_destroy_handle_function$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * rosidl_event_message_destroy_handle_function_function event_message_destroy_handle_function
     * }
     */
    public static MemorySegment event_message_destroy_handle_function(MemorySegment struct) {
        return struct.get(event_message_destroy_handle_function$LAYOUT, event_message_destroy_handle_function$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * rosidl_event_message_destroy_handle_function_function event_message_destroy_handle_function
     * }
     */
    public static void event_message_destroy_handle_function(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(event_message_destroy_handle_function$LAYOUT, event_message_destroy_handle_function$OFFSET, fieldValue);
    }

    private static final AddressLayout get_type_hash_func$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("get_type_hash_func"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * rosidl_service_get_type_hash_function get_type_hash_func
     * }
     */
    public static final AddressLayout get_type_hash_func$layout() {
        return get_type_hash_func$LAYOUT;
    }

    private static final long get_type_hash_func$OFFSET = $LAYOUT.byteOffset(groupElement("get_type_hash_func"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * rosidl_service_get_type_hash_function get_type_hash_func
     * }
     */
    public static final long get_type_hash_func$offset() {
        return get_type_hash_func$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * rosidl_service_get_type_hash_function get_type_hash_func
     * }
     */
    public static MemorySegment get_type_hash_func(MemorySegment struct) {
        return struct.get(get_type_hash_func$LAYOUT, get_type_hash_func$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * rosidl_service_get_type_hash_function get_type_hash_func
     * }
     */
    public static void get_type_hash_func(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(get_type_hash_func$LAYOUT, get_type_hash_func$OFFSET, fieldValue);
    }

    private static final AddressLayout get_type_description_func$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("get_type_description_func"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * rosidl_service_get_type_description_function get_type_description_func
     * }
     */
    public static final AddressLayout get_type_description_func$layout() {
        return get_type_description_func$LAYOUT;
    }

    private static final long get_type_description_func$OFFSET = $LAYOUT.byteOffset(groupElement("get_type_description_func"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * rosidl_service_get_type_description_function get_type_description_func
     * }
     */
    public static final long get_type_description_func$offset() {
        return get_type_description_func$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * rosidl_service_get_type_description_function get_type_description_func
     * }
     */
    public static MemorySegment get_type_description_func(MemorySegment struct) {
        return struct.get(get_type_description_func$LAYOUT, get_type_description_func$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * rosidl_service_get_type_description_function get_type_description_func
     * }
     */
    public static void get_type_description_func(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(get_type_description_func$LAYOUT, get_type_description_func$OFFSET, fieldValue);
    }

    private static final AddressLayout get_type_description_sources_func$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("get_type_description_sources_func"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * rosidl_service_get_type_description_sources_function get_type_description_sources_func
     * }
     */
    public static final AddressLayout get_type_description_sources_func$layout() {
        return get_type_description_sources_func$LAYOUT;
    }

    private static final long get_type_description_sources_func$OFFSET = $LAYOUT.byteOffset(groupElement("get_type_description_sources_func"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * rosidl_service_get_type_description_sources_function get_type_description_sources_func
     * }
     */
    public static final long get_type_description_sources_func$offset() {
        return get_type_description_sources_func$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * rosidl_service_get_type_description_sources_function get_type_description_sources_func
     * }
     */
    public static MemorySegment get_type_description_sources_func(MemorySegment struct) {
        return struct.get(get_type_description_sources_func$LAYOUT, get_type_description_sources_func$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * rosidl_service_get_type_description_sources_function get_type_description_sources_func
     * }
     */
    public static void get_type_description_sources_func(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(get_type_description_sources_func$LAYOUT, get_type_description_sources_func$OFFSET, fieldValue);
    }

    /**
     * Obtains a slice of {@code arrayParam} which selects the array element at {@code index}.
     * The returned segment has address {@code arrayParam.address() + index * layout().byteSize()}
     */
    public static MemorySegment asSlice(MemorySegment array, long index) {
        return array.asSlice(layout().byteSize() * index);
    }

    /**
     * The size (in bytes) of this struct
     */
    public static long sizeof() { return layout().byteSize(); }

    /**
     * Allocate a segment of size {@code layout().byteSize()} using {@code allocator}
     */
    public static MemorySegment allocate(SegmentAllocator allocator) {
        return allocator.allocate(layout());
    }

    /**
     * Allocate an array of size {@code elementCount} using {@code allocator}.
     * The returned segment has size {@code elementCount * layout().byteSize()}.
     */
    public static MemorySegment allocateArray(long elementCount, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(elementCount, layout()));
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, Arena arena, Consumer<MemorySegment> cleanup) {
        return reinterpret(addr, 1, arena, cleanup);
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code elementCount * layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, long elementCount, Arena arena, Consumer<MemorySegment> cleanup) {
        return addr.reinterpret(layout().byteSize() * elementCount, arena, cleanup);
    }
}

