// Generated by jextract

package org.ros2.rcl.srv;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * struct std_srvs__srv__SetBool_Response {
 *     bool success;
 *     rosidl_runtime_c__String message;
 * }
 * }
 */
public class std_srvs__srv__SetBool_Response {

    std_srvs__srv__SetBool_Response() {
        // Should not be called directly
    }

    private static final GroupLayout $LAYOUT = MemoryLayout.structLayout(
        StdSrvs_Lib.C_BOOL.withName("success"),
        MemoryLayout.paddingLayout(7),
        rosidl_runtime_c__String.layout().withName("message")
    ).withName("std_srvs__srv__SetBool_Response");

    /**
     * The layout of this struct
     */
    public static final GroupLayout layout() {
        return $LAYOUT;
    }

    private static final OfBoolean success$LAYOUT = (OfBoolean)$LAYOUT.select(groupElement("success"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * bool success
     * }
     */
    public static final OfBoolean success$layout() {
        return success$LAYOUT;
    }

    private static final long success$OFFSET = $LAYOUT.byteOffset(groupElement("success"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * bool success
     * }
     */
    public static final long success$offset() {
        return success$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * bool success
     * }
     */
    public static boolean success(MemorySegment struct) {
        return struct.get(success$LAYOUT, success$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * bool success
     * }
     */
    public static void success(MemorySegment struct, boolean fieldValue) {
        struct.set(success$LAYOUT, success$OFFSET, fieldValue);
    }

    private static final GroupLayout message$LAYOUT = (GroupLayout)$LAYOUT.select(groupElement("message"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * rosidl_runtime_c__String message
     * }
     */
    public static final GroupLayout message$layout() {
        return message$LAYOUT;
    }

    private static final long message$OFFSET = $LAYOUT.byteOffset(groupElement("message"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * rosidl_runtime_c__String message
     * }
     */
    public static final long message$offset() {
        return message$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * rosidl_runtime_c__String message
     * }
     */
    public static MemorySegment message(MemorySegment struct) {
        return struct.asSlice(message$OFFSET, message$LAYOUT.byteSize());
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * rosidl_runtime_c__String message
     * }
     */
    public static void message(MemorySegment struct, MemorySegment fieldValue) {
        MemorySegment.copy(fieldValue, 0L, struct, message$OFFSET, message$LAYOUT.byteSize());
    }

    /**
     * Obtains a slice of {@code arrayParam} which selects the array element at {@code index}.
     * The returned segment has address {@code arrayParam.address() + index * layout().byteSize()}
     */
    public static MemorySegment asSlice(MemorySegment array, long index) {
        return array.asSlice(layout().byteSize() * index);
    }

    /**
     * The size (in bytes) of this struct
     */
    public static long sizeof() { return layout().byteSize(); }

    /**
     * Allocate a segment of size {@code layout().byteSize()} using {@code allocator}
     */
    public static MemorySegment allocate(SegmentAllocator allocator) {
        return allocator.allocate(layout());
    }

    /**
     * Allocate an array of size {@code elementCount} using {@code allocator}.
     * The returned segment has size {@code elementCount * layout().byteSize()}.
     */
    public static MemorySegment allocateArray(long elementCount, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(elementCount, layout()));
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, Arena arena, Consumer<MemorySegment> cleanup) {
        return reinterpret(addr, 1, arena, cleanup);
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code elementCount * layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, long elementCount, Arena arena, Consumer<MemorySegment> cleanup) {
        return addr.reinterpret(layout().byteSize() * elementCount, arena, cleanup);
    }
}

