// Generated by jextract

package org.ros2.rcl.msgs;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * struct geometry_msgs__msg__Polygon {
 *     geometry_msgs__msg__Point32__Sequence points;
 * }
 * }
 */
public class geometry_msgs__msg__Polygon {

    geometry_msgs__msg__Polygon() {
        // Should not be called directly
    }

    private static final GroupLayout $LAYOUT = MemoryLayout.structLayout(
        geometry_msgs__msg__Point32__Sequence.layout().withName("points")
    ).withName("geometry_msgs__msg__Polygon");

    /**
     * The layout of this struct
     */
    public static final GroupLayout layout() {
        return $LAYOUT;
    }

    private static final GroupLayout points$LAYOUT = (GroupLayout)$LAYOUT.select(groupElement("points"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * geometry_msgs__msg__Point32__Sequence points
     * }
     */
    public static final GroupLayout points$layout() {
        return points$LAYOUT;
    }

    private static final long points$OFFSET = $LAYOUT.byteOffset(groupElement("points"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * geometry_msgs__msg__Point32__Sequence points
     * }
     */
    public static final long points$offset() {
        return points$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * geometry_msgs__msg__Point32__Sequence points
     * }
     */
    public static MemorySegment points(MemorySegment struct) {
        return struct.asSlice(points$OFFSET, points$LAYOUT.byteSize());
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * geometry_msgs__msg__Point32__Sequence points
     * }
     */
    public static void points(MemorySegment struct, MemorySegment fieldValue) {
        MemorySegment.copy(fieldValue, 0L, struct, points$OFFSET, points$LAYOUT.byteSize());
    }

    /**
     * Obtains a slice of {@code arrayParam} which selects the array element at {@code index}.
     * The returned segment has address {@code arrayParam.address() + index * layout().byteSize()}
     */
    public static MemorySegment asSlice(MemorySegment array, long index) {
        return array.asSlice(layout().byteSize() * index);
    }

    /**
     * The size (in bytes) of this struct
     */
    public static long sizeof() { return layout().byteSize(); }

    /**
     * Allocate a segment of size {@code layout().byteSize()} using {@code allocator}
     */
    public static MemorySegment allocate(SegmentAllocator allocator) {
        return allocator.allocate(layout());
    }

    /**
     * Allocate an array of size {@code elementCount} using {@code allocator}.
     * The returned segment has size {@code elementCount * layout().byteSize()}.
     */
    public static MemorySegment allocateArray(long elementCount, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(elementCount, layout()));
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, Arena arena, Consumer<MemorySegment> cleanup) {
        return reinterpret(addr, 1, arena, cleanup);
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code elementCount * layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, long elementCount, Arena arena, Consumer<MemorySegment> cleanup) {
        return addr.reinterpret(layout().byteSize() * elementCount, arena, cleanup);
    }
}

