// Generated by jextract

package org.ros2.rcl.msgs;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * struct geometry_msgs__msg__Twist {
 *     geometry_msgs__msg__Vector3 linear;
 *     geometry_msgs__msg__Vector3 angular;
 * }
 * }
 */
public class geometry_msgs__msg__Twist {

    geometry_msgs__msg__Twist() {
        // Should not be called directly
    }

    private static final GroupLayout $LAYOUT = MemoryLayout.structLayout(
        geometry_msgs__msg__Vector3.layout().withName("linear"),
        geometry_msgs__msg__Vector3.layout().withName("angular")
    ).withName("geometry_msgs__msg__Twist");

    /**
     * The layout of this struct
     */
    public static final GroupLayout layout() {
        return $LAYOUT;
    }

    private static final GroupLayout linear$LAYOUT = (GroupLayout)$LAYOUT.select(groupElement("linear"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * geometry_msgs__msg__Vector3 linear
     * }
     */
    public static final GroupLayout linear$layout() {
        return linear$LAYOUT;
    }

    private static final long linear$OFFSET = $LAYOUT.byteOffset(groupElement("linear"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * geometry_msgs__msg__Vector3 linear
     * }
     */
    public static final long linear$offset() {
        return linear$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * geometry_msgs__msg__Vector3 linear
     * }
     */
    public static MemorySegment linear(MemorySegment struct) {
        return struct.asSlice(linear$OFFSET, linear$LAYOUT.byteSize());
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * geometry_msgs__msg__Vector3 linear
     * }
     */
    public static void linear(MemorySegment struct, MemorySegment fieldValue) {
        MemorySegment.copy(fieldValue, 0L, struct, linear$OFFSET, linear$LAYOUT.byteSize());
    }

    private static final GroupLayout angular$LAYOUT = (GroupLayout)$LAYOUT.select(groupElement("angular"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * geometry_msgs__msg__Vector3 angular
     * }
     */
    public static final GroupLayout angular$layout() {
        return angular$LAYOUT;
    }

    private static final long angular$OFFSET = $LAYOUT.byteOffset(groupElement("angular"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * geometry_msgs__msg__Vector3 angular
     * }
     */
    public static final long angular$offset() {
        return angular$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * geometry_msgs__msg__Vector3 angular
     * }
     */
    public static MemorySegment angular(MemorySegment struct) {
        return struct.asSlice(angular$OFFSET, angular$LAYOUT.byteSize());
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * geometry_msgs__msg__Vector3 angular
     * }
     */
    public static void angular(MemorySegment struct, MemorySegment fieldValue) {
        MemorySegment.copy(fieldValue, 0L, struct, angular$OFFSET, angular$LAYOUT.byteSize());
    }

    /**
     * Obtains a slice of {@code arrayParam} which selects the array element at {@code index}.
     * The returned segment has address {@code arrayParam.address() + index * layout().byteSize()}
     */
    public static MemorySegment asSlice(MemorySegment array, long index) {
        return array.asSlice(layout().byteSize() * index);
    }

    /**
     * The size (in bytes) of this struct
     */
    public static long sizeof() { return layout().byteSize(); }

    /**
     * Allocate a segment of size {@code layout().byteSize()} using {@code allocator}
     */
    public static MemorySegment allocate(SegmentAllocator allocator) {
        return allocator.allocate(layout());
    }

    /**
     * Allocate an array of size {@code elementCount} using {@code allocator}.
     * The returned segment has size {@code elementCount * layout().byteSize()}.
     */
    public static MemorySegment allocateArray(long elementCount, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(elementCount, layout()));
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, Arena arena, Consumer<MemorySegment> cleanup) {
        return reinterpret(addr, 1, arena, cleanup);
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code elementCount * layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, long elementCount, Arena arena, Consumer<MemorySegment> cleanup) {
        return addr.reinterpret(layout().byteSize() * elementCount, arena, cleanup);
    }
}

