// Generated by jextract

package org.ros2.rcl.msgs;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * struct geometry_msgs__msg__PolygonInstance {
 *     geometry_msgs__msg__Polygon polygon;
 *     int64_t id;
 * }
 * }
 */
public class geometry_msgs__msg__PolygonInstance {

    geometry_msgs__msg__PolygonInstance() {
        // Should not be called directly
    }

    private static final GroupLayout $LAYOUT = MemoryLayout.structLayout(
        geometry_msgs__msg__Polygon.layout().withName("polygon"),
        GEOMETRY_MSGS_Lib.C_LONG.withName("id")
    ).withName("geometry_msgs__msg__PolygonInstance");

    /**
     * The layout of this struct
     */
    public static final GroupLayout layout() {
        return $LAYOUT;
    }

    private static final GroupLayout polygon$LAYOUT = (GroupLayout)$LAYOUT.select(groupElement("polygon"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * geometry_msgs__msg__Polygon polygon
     * }
     */
    public static final GroupLayout polygon$layout() {
        return polygon$LAYOUT;
    }

    private static final long polygon$OFFSET = $LAYOUT.byteOffset(groupElement("polygon"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * geometry_msgs__msg__Polygon polygon
     * }
     */
    public static final long polygon$offset() {
        return polygon$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * geometry_msgs__msg__Polygon polygon
     * }
     */
    public static MemorySegment polygon(MemorySegment struct) {
        return struct.asSlice(polygon$OFFSET, polygon$LAYOUT.byteSize());
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * geometry_msgs__msg__Polygon polygon
     * }
     */
    public static void polygon(MemorySegment struct, MemorySegment fieldValue) {
        MemorySegment.copy(fieldValue, 0L, struct, polygon$OFFSET, polygon$LAYOUT.byteSize());
    }

    private static final OfLong id$LAYOUT = (OfLong)$LAYOUT.select(groupElement("id"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * int64_t id
     * }
     */
    public static final OfLong id$layout() {
        return id$LAYOUT;
    }

    private static final long id$OFFSET = $LAYOUT.byteOffset(groupElement("id"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * int64_t id
     * }
     */
    public static final long id$offset() {
        return id$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * int64_t id
     * }
     */
    public static long id(MemorySegment struct) {
        return struct.get(id$LAYOUT, id$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * int64_t id
     * }
     */
    public static void id(MemorySegment struct, long fieldValue) {
        struct.set(id$LAYOUT, id$OFFSET, fieldValue);
    }

    /**
     * Obtains a slice of {@code arrayParam} which selects the array element at {@code index}.
     * The returned segment has address {@code arrayParam.address() + index * layout().byteSize()}
     */
    public static MemorySegment asSlice(MemorySegment array, long index) {
        return array.asSlice(layout().byteSize() * index);
    }

    /**
     * The size (in bytes) of this struct
     */
    public static long sizeof() { return layout().byteSize(); }

    /**
     * Allocate a segment of size {@code layout().byteSize()} using {@code allocator}
     */
    public static MemorySegment allocate(SegmentAllocator allocator) {
        return allocator.allocate(layout());
    }

    /**
     * Allocate an array of size {@code elementCount} using {@code allocator}.
     * The returned segment has size {@code elementCount * layout().byteSize()}.
     */
    public static MemorySegment allocateArray(long elementCount, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(elementCount, layout()));
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, Arena arena, Consumer<MemorySegment> cleanup) {
        return reinterpret(addr, 1, arena, cleanup);
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code elementCount * layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, long elementCount, Arena arena, Consumer<MemorySegment> cleanup) {
        return addr.reinterpret(layout().byteSize() * elementCount, arena, cleanup);
    }
}

