// Generated by jextract

package org.ros2.rcl.msgs;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * struct geometry_msgs__msg__PoseWithCovariance {
 *     geometry_msgs__msg__Pose pose;
 *     double covariance[36];
 * }
 * }
 */
public class geometry_msgs__msg__PoseWithCovariance {

    geometry_msgs__msg__PoseWithCovariance() {
        // Should not be called directly
    }

    private static final GroupLayout $LAYOUT = MemoryLayout.structLayout(
        geometry_msgs__msg__Pose.layout().withName("pose"),
        MemoryLayout.sequenceLayout(36, GEOMETRY_MSGS_Lib.C_DOUBLE).withName("covariance")
    ).withName("geometry_msgs__msg__PoseWithCovariance");

    /**
     * The layout of this struct
     */
    public static final GroupLayout layout() {
        return $LAYOUT;
    }

    private static final GroupLayout pose$LAYOUT = (GroupLayout)$LAYOUT.select(groupElement("pose"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * geometry_msgs__msg__Pose pose
     * }
     */
    public static final GroupLayout pose$layout() {
        return pose$LAYOUT;
    }

    private static final long pose$OFFSET = $LAYOUT.byteOffset(groupElement("pose"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * geometry_msgs__msg__Pose pose
     * }
     */
    public static final long pose$offset() {
        return pose$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * geometry_msgs__msg__Pose pose
     * }
     */
    public static MemorySegment pose(MemorySegment struct) {
        return struct.asSlice(pose$OFFSET, pose$LAYOUT.byteSize());
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * geometry_msgs__msg__Pose pose
     * }
     */
    public static void pose(MemorySegment struct, MemorySegment fieldValue) {
        MemorySegment.copy(fieldValue, 0L, struct, pose$OFFSET, pose$LAYOUT.byteSize());
    }

    private static final SequenceLayout covariance$LAYOUT = (SequenceLayout)$LAYOUT.select(groupElement("covariance"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * double covariance[36]
     * }
     */
    public static final SequenceLayout covariance$layout() {
        return covariance$LAYOUT;
    }

    private static final long covariance$OFFSET = $LAYOUT.byteOffset(groupElement("covariance"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * double covariance[36]
     * }
     */
    public static final long covariance$offset() {
        return covariance$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * double covariance[36]
     * }
     */
    public static MemorySegment covariance(MemorySegment struct) {
        return struct.asSlice(covariance$OFFSET, covariance$LAYOUT.byteSize());
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * double covariance[36]
     * }
     */
    public static void covariance(MemorySegment struct, MemorySegment fieldValue) {
        MemorySegment.copy(fieldValue, 0L, struct, covariance$OFFSET, covariance$LAYOUT.byteSize());
    }

    private static long[] covariance$DIMS = { 36 };

    /**
     * Dimensions for array field:
     * {@snippet lang=c :
     * double covariance[36]
     * }
     */
    public static long[] covariance$dimensions() {
        return covariance$DIMS;
    }
    private static final VarHandle covariance$ELEM_HANDLE = covariance$LAYOUT.varHandle(sequenceElement());

    /**
     * Indexed getter for field:
     * {@snippet lang=c :
     * double covariance[36]
     * }
     */
    public static double covariance(MemorySegment struct, long index0) {
        return (double)covariance$ELEM_HANDLE.get(struct, covariance$OFFSET, index0);
    }

    /**
     * Indexed setter for field:
     * {@snippet lang=c :
     * double covariance[36]
     * }
     */
    public static void covariance(MemorySegment struct, long index0, double fieldValue) {
        covariance$ELEM_HANDLE.set(struct, covariance$OFFSET, index0, fieldValue);
    }

    /**
     * Obtains a slice of {@code arrayParam} which selects the array element at {@code index}.
     * The returned segment has address {@code arrayParam.address() + index * layout().byteSize()}
     */
    public static MemorySegment asSlice(MemorySegment array, long index) {
        return array.asSlice(layout().byteSize() * index);
    }

    /**
     * The size (in bytes) of this struct
     */
    public static long sizeof() { return layout().byteSize(); }

    /**
     * Allocate a segment of size {@code layout().byteSize()} using {@code allocator}
     */
    public static MemorySegment allocate(SegmentAllocator allocator) {
        return allocator.allocate(layout());
    }

    /**
     * Allocate an array of size {@code elementCount} using {@code allocator}.
     * The returned segment has size {@code elementCount * layout().byteSize()}.
     */
    public static MemorySegment allocateArray(long elementCount, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(elementCount, layout()));
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, Arena arena, Consumer<MemorySegment> cleanup) {
        return reinterpret(addr, 1, arena, cleanup);
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code elementCount * layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, long elementCount, Arena arena, Consumer<MemorySegment> cleanup) {
        return addr.reinterpret(layout().byteSize() * elementCount, arena, cleanup);
    }
}

