// Generated by jextract

package org.ros2.rcl.msgs;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * struct geometry_msgs__msg__Inertia {
 *     double m;
 *     geometry_msgs__msg__Vector3 com;
 *     double ixx;
 *     double ixy;
 *     double ixz;
 *     double iyy;
 *     double iyz;
 *     double izz;
 * }
 * }
 */
public class geometry_msgs__msg__Inertia {

    geometry_msgs__msg__Inertia() {
        // Should not be called directly
    }

    private static final GroupLayout $LAYOUT = MemoryLayout.structLayout(
        GEOMETRY_MSGS_Lib.C_DOUBLE.withName("m"),
        geometry_msgs__msg__Vector3.layout().withName("com"),
        GEOMETRY_MSGS_Lib.C_DOUBLE.withName("ixx"),
        GEOMETRY_MSGS_Lib.C_DOUBLE.withName("ixy"),
        GEOMETRY_MSGS_Lib.C_DOUBLE.withName("ixz"),
        GEOMETRY_MSGS_Lib.C_DOUBLE.withName("iyy"),
        GEOMETRY_MSGS_Lib.C_DOUBLE.withName("iyz"),
        GEOMETRY_MSGS_Lib.C_DOUBLE.withName("izz")
    ).withName("geometry_msgs__msg__Inertia");

    /**
     * The layout of this struct
     */
    public static final GroupLayout layout() {
        return $LAYOUT;
    }

    private static final OfDouble m$LAYOUT = (OfDouble)$LAYOUT.select(groupElement("m"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * double m
     * }
     */
    public static final OfDouble m$layout() {
        return m$LAYOUT;
    }

    private static final long m$OFFSET = $LAYOUT.byteOffset(groupElement("m"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * double m
     * }
     */
    public static final long m$offset() {
        return m$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * double m
     * }
     */
    public static double m(MemorySegment struct) {
        return struct.get(m$LAYOUT, m$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * double m
     * }
     */
    public static void m(MemorySegment struct, double fieldValue) {
        struct.set(m$LAYOUT, m$OFFSET, fieldValue);
    }

    private static final GroupLayout com$LAYOUT = (GroupLayout)$LAYOUT.select(groupElement("com"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * geometry_msgs__msg__Vector3 com
     * }
     */
    public static final GroupLayout com$layout() {
        return com$LAYOUT;
    }

    private static final long com$OFFSET = $LAYOUT.byteOffset(groupElement("com"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * geometry_msgs__msg__Vector3 com
     * }
     */
    public static final long com$offset() {
        return com$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * geometry_msgs__msg__Vector3 com
     * }
     */
    public static MemorySegment com(MemorySegment struct) {
        return struct.asSlice(com$OFFSET, com$LAYOUT.byteSize());
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * geometry_msgs__msg__Vector3 com
     * }
     */
    public static void com(MemorySegment struct, MemorySegment fieldValue) {
        MemorySegment.copy(fieldValue, 0L, struct, com$OFFSET, com$LAYOUT.byteSize());
    }

    private static final OfDouble ixx$LAYOUT = (OfDouble)$LAYOUT.select(groupElement("ixx"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * double ixx
     * }
     */
    public static final OfDouble ixx$layout() {
        return ixx$LAYOUT;
    }

    private static final long ixx$OFFSET = $LAYOUT.byteOffset(groupElement("ixx"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * double ixx
     * }
     */
    public static final long ixx$offset() {
        return ixx$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * double ixx
     * }
     */
    public static double ixx(MemorySegment struct) {
        return struct.get(ixx$LAYOUT, ixx$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * double ixx
     * }
     */
    public static void ixx(MemorySegment struct, double fieldValue) {
        struct.set(ixx$LAYOUT, ixx$OFFSET, fieldValue);
    }

    private static final OfDouble ixy$LAYOUT = (OfDouble)$LAYOUT.select(groupElement("ixy"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * double ixy
     * }
     */
    public static final OfDouble ixy$layout() {
        return ixy$LAYOUT;
    }

    private static final long ixy$OFFSET = $LAYOUT.byteOffset(groupElement("ixy"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * double ixy
     * }
     */
    public static final long ixy$offset() {
        return ixy$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * double ixy
     * }
     */
    public static double ixy(MemorySegment struct) {
        return struct.get(ixy$LAYOUT, ixy$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * double ixy
     * }
     */
    public static void ixy(MemorySegment struct, double fieldValue) {
        struct.set(ixy$LAYOUT, ixy$OFFSET, fieldValue);
    }

    private static final OfDouble ixz$LAYOUT = (OfDouble)$LAYOUT.select(groupElement("ixz"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * double ixz
     * }
     */
    public static final OfDouble ixz$layout() {
        return ixz$LAYOUT;
    }

    private static final long ixz$OFFSET = $LAYOUT.byteOffset(groupElement("ixz"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * double ixz
     * }
     */
    public static final long ixz$offset() {
        return ixz$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * double ixz
     * }
     */
    public static double ixz(MemorySegment struct) {
        return struct.get(ixz$LAYOUT, ixz$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * double ixz
     * }
     */
    public static void ixz(MemorySegment struct, double fieldValue) {
        struct.set(ixz$LAYOUT, ixz$OFFSET, fieldValue);
    }

    private static final OfDouble iyy$LAYOUT = (OfDouble)$LAYOUT.select(groupElement("iyy"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * double iyy
     * }
     */
    public static final OfDouble iyy$layout() {
        return iyy$LAYOUT;
    }

    private static final long iyy$OFFSET = $LAYOUT.byteOffset(groupElement("iyy"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * double iyy
     * }
     */
    public static final long iyy$offset() {
        return iyy$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * double iyy
     * }
     */
    public static double iyy(MemorySegment struct) {
        return struct.get(iyy$LAYOUT, iyy$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * double iyy
     * }
     */
    public static void iyy(MemorySegment struct, double fieldValue) {
        struct.set(iyy$LAYOUT, iyy$OFFSET, fieldValue);
    }

    private static final OfDouble iyz$LAYOUT = (OfDouble)$LAYOUT.select(groupElement("iyz"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * double iyz
     * }
     */
    public static final OfDouble iyz$layout() {
        return iyz$LAYOUT;
    }

    private static final long iyz$OFFSET = $LAYOUT.byteOffset(groupElement("iyz"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * double iyz
     * }
     */
    public static final long iyz$offset() {
        return iyz$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * double iyz
     * }
     */
    public static double iyz(MemorySegment struct) {
        return struct.get(iyz$LAYOUT, iyz$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * double iyz
     * }
     */
    public static void iyz(MemorySegment struct, double fieldValue) {
        struct.set(iyz$LAYOUT, iyz$OFFSET, fieldValue);
    }

    private static final OfDouble izz$LAYOUT = (OfDouble)$LAYOUT.select(groupElement("izz"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * double izz
     * }
     */
    public static final OfDouble izz$layout() {
        return izz$LAYOUT;
    }

    private static final long izz$OFFSET = $LAYOUT.byteOffset(groupElement("izz"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * double izz
     * }
     */
    public static final long izz$offset() {
        return izz$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * double izz
     * }
     */
    public static double izz(MemorySegment struct) {
        return struct.get(izz$LAYOUT, izz$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * double izz
     * }
     */
    public static void izz(MemorySegment struct, double fieldValue) {
        struct.set(izz$LAYOUT, izz$OFFSET, fieldValue);
    }

    /**
     * Obtains a slice of {@code arrayParam} which selects the array element at {@code index}.
     * The returned segment has address {@code arrayParam.address() + index * layout().byteSize()}
     */
    public static MemorySegment asSlice(MemorySegment array, long index) {
        return array.asSlice(layout().byteSize() * index);
    }

    /**
     * The size (in bytes) of this struct
     */
    public static long sizeof() { return layout().byteSize(); }

    /**
     * Allocate a segment of size {@code layout().byteSize()} using {@code allocator}
     */
    public static MemorySegment allocate(SegmentAllocator allocator) {
        return allocator.allocate(layout());
    }

    /**
     * Allocate an array of size {@code elementCount} using {@code allocator}.
     * The returned segment has size {@code elementCount * layout().byteSize()}.
     */
    public static MemorySegment allocateArray(long elementCount, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(elementCount, layout()));
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, Arena arena, Consumer<MemorySegment> cleanup) {
        return reinterpret(addr, 1, arena, cleanup);
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code elementCount * layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, long elementCount, Arena arena, Consumer<MemorySegment> cleanup) {
        return addr.reinterpret(layout().byteSize() * elementCount, arena, cleanup);
    }
}

