// Generated by jextract

package org.ros2.rcl.msgs;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * typedef struct rcutils_sha256_ctx_s {
 *     uint8_t data[64];
 *     size_t datalen;
 *     uint64_t bitlen;
 *     uint32_t state[8];
 * } rcutils_sha256_ctx_t
 * }
 */
public class rcutils_sha256_ctx_t extends rcutils_sha256_ctx_s {

    rcutils_sha256_ctx_t() {
        // Should not be called directly
    }
}

