// Generated by jextract

package org.ros2.rcl.msgs;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * struct rosidl_runtime_c__type_description__TypeDescription {
 *     rosidl_runtime_c__type_description__IndividualTypeDescription type_description;
 *     rosidl_runtime_c__type_description__IndividualTypeDescription__Sequence referenced_type_descriptions;
 * }
 * }
 */
public class rosidl_runtime_c__type_description__TypeDescription {

    rosidl_runtime_c__type_description__TypeDescription() {
        // Should not be called directly
    }

    private static final GroupLayout $LAYOUT = MemoryLayout.structLayout(
        rosidl_runtime_c__type_description__IndividualTypeDescription.layout().withName("type_description"),
        rosidl_runtime_c__type_description__IndividualTypeDescription__Sequence.layout().withName("referenced_type_descriptions")
    ).withName("rosidl_runtime_c__type_description__TypeDescription");

    /**
     * The layout of this struct
     */
    public static final GroupLayout layout() {
        return $LAYOUT;
    }

    private static final GroupLayout type_description$LAYOUT = (GroupLayout)$LAYOUT.select(groupElement("type_description"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * rosidl_runtime_c__type_description__IndividualTypeDescription type_description
     * }
     */
    public static final GroupLayout type_description$layout() {
        return type_description$LAYOUT;
    }

    private static final long type_description$OFFSET = $LAYOUT.byteOffset(groupElement("type_description"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * rosidl_runtime_c__type_description__IndividualTypeDescription type_description
     * }
     */
    public static final long type_description$offset() {
        return type_description$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * rosidl_runtime_c__type_description__IndividualTypeDescription type_description
     * }
     */
    public static MemorySegment type_description(MemorySegment struct) {
        return struct.asSlice(type_description$OFFSET, type_description$LAYOUT.byteSize());
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * rosidl_runtime_c__type_description__IndividualTypeDescription type_description
     * }
     */
    public static void type_description(MemorySegment struct, MemorySegment fieldValue) {
        MemorySegment.copy(fieldValue, 0L, struct, type_description$OFFSET, type_description$LAYOUT.byteSize());
    }

    private static final GroupLayout referenced_type_descriptions$LAYOUT = (GroupLayout)$LAYOUT.select(groupElement("referenced_type_descriptions"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * rosidl_runtime_c__type_description__IndividualTypeDescription__Sequence referenced_type_descriptions
     * }
     */
    public static final GroupLayout referenced_type_descriptions$layout() {
        return referenced_type_descriptions$LAYOUT;
    }

    private static final long referenced_type_descriptions$OFFSET = $LAYOUT.byteOffset(groupElement("referenced_type_descriptions"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * rosidl_runtime_c__type_description__IndividualTypeDescription__Sequence referenced_type_descriptions
     * }
     */
    public static final long referenced_type_descriptions$offset() {
        return referenced_type_descriptions$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * rosidl_runtime_c__type_description__IndividualTypeDescription__Sequence referenced_type_descriptions
     * }
     */
    public static MemorySegment referenced_type_descriptions(MemorySegment struct) {
        return struct.asSlice(referenced_type_descriptions$OFFSET, referenced_type_descriptions$LAYOUT.byteSize());
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * rosidl_runtime_c__type_description__IndividualTypeDescription__Sequence referenced_type_descriptions
     * }
     */
    public static void referenced_type_descriptions(MemorySegment struct, MemorySegment fieldValue) {
        MemorySegment.copy(fieldValue, 0L, struct, referenced_type_descriptions$OFFSET, referenced_type_descriptions$LAYOUT.byteSize());
    }

    /**
     * Obtains a slice of {@code arrayParam} which selects the array element at {@code index}.
     * The returned segment has address {@code arrayParam.address() + index * layout().byteSize()}
     */
    public static MemorySegment asSlice(MemorySegment array, long index) {
        return array.asSlice(layout().byteSize() * index);
    }

    /**
     * The size (in bytes) of this struct
     */
    public static long sizeof() { return layout().byteSize(); }

    /**
     * Allocate a segment of size {@code layout().byteSize()} using {@code allocator}
     */
    public static MemorySegment allocate(SegmentAllocator allocator) {
        return allocator.allocate(layout());
    }

    /**
     * Allocate an array of size {@code elementCount} using {@code allocator}.
     * The returned segment has size {@code elementCount * layout().byteSize()}.
     */
    public static MemorySegment allocateArray(long elementCount, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(elementCount, layout()));
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, Arena arena, Consumer<MemorySegment> cleanup) {
        return reinterpret(addr, 1, arena, cleanup);
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code elementCount * layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, long elementCount, Arena arena, Consumer<MemorySegment> cleanup) {
        return addr.reinterpret(layout().byteSize() * elementCount, arena, cleanup);
    }
}

