// Generated by jextract

package org.ros2.rcl.msgs;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * struct rosidl_runtime_c__type_description__TypeSource {
 *     rosidl_runtime_c__String type_name;
 *     rosidl_runtime_c__String encoding;
 *     rosidl_runtime_c__String raw_file_contents;
 * }
 * }
 */
public class rosidl_runtime_c__type_description__TypeSource {

    rosidl_runtime_c__type_description__TypeSource() {
        // Should not be called directly
    }

    private static final GroupLayout $LAYOUT = MemoryLayout.structLayout(
        rosidl_runtime_c__String.layout().withName("type_name"),
        rosidl_runtime_c__String.layout().withName("encoding"),
        rosidl_runtime_c__String.layout().withName("raw_file_contents")
    ).withName("rosidl_runtime_c__type_description__TypeSource");

    /**
     * The layout of this struct
     */
    public static final GroupLayout layout() {
        return $LAYOUT;
    }

    private static final GroupLayout type_name$LAYOUT = (GroupLayout)$LAYOUT.select(groupElement("type_name"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * rosidl_runtime_c__String type_name
     * }
     */
    public static final GroupLayout type_name$layout() {
        return type_name$LAYOUT;
    }

    private static final long type_name$OFFSET = $LAYOUT.byteOffset(groupElement("type_name"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * rosidl_runtime_c__String type_name
     * }
     */
    public static final long type_name$offset() {
        return type_name$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * rosidl_runtime_c__String type_name
     * }
     */
    public static MemorySegment type_name(MemorySegment struct) {
        return struct.asSlice(type_name$OFFSET, type_name$LAYOUT.byteSize());
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * rosidl_runtime_c__String type_name
     * }
     */
    public static void type_name(MemorySegment struct, MemorySegment fieldValue) {
        MemorySegment.copy(fieldValue, 0L, struct, type_name$OFFSET, type_name$LAYOUT.byteSize());
    }

    private static final GroupLayout encoding$LAYOUT = (GroupLayout)$LAYOUT.select(groupElement("encoding"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * rosidl_runtime_c__String encoding
     * }
     */
    public static final GroupLayout encoding$layout() {
        return encoding$LAYOUT;
    }

    private static final long encoding$OFFSET = $LAYOUT.byteOffset(groupElement("encoding"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * rosidl_runtime_c__String encoding
     * }
     */
    public static final long encoding$offset() {
        return encoding$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * rosidl_runtime_c__String encoding
     * }
     */
    public static MemorySegment encoding(MemorySegment struct) {
        return struct.asSlice(encoding$OFFSET, encoding$LAYOUT.byteSize());
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * rosidl_runtime_c__String encoding
     * }
     */
    public static void encoding(MemorySegment struct, MemorySegment fieldValue) {
        MemorySegment.copy(fieldValue, 0L, struct, encoding$OFFSET, encoding$LAYOUT.byteSize());
    }

    private static final GroupLayout raw_file_contents$LAYOUT = (GroupLayout)$LAYOUT.select(groupElement("raw_file_contents"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * rosidl_runtime_c__String raw_file_contents
     * }
     */
    public static final GroupLayout raw_file_contents$layout() {
        return raw_file_contents$LAYOUT;
    }

    private static final long raw_file_contents$OFFSET = $LAYOUT.byteOffset(groupElement("raw_file_contents"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * rosidl_runtime_c__String raw_file_contents
     * }
     */
    public static final long raw_file_contents$offset() {
        return raw_file_contents$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * rosidl_runtime_c__String raw_file_contents
     * }
     */
    public static MemorySegment raw_file_contents(MemorySegment struct) {
        return struct.asSlice(raw_file_contents$OFFSET, raw_file_contents$LAYOUT.byteSize());
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * rosidl_runtime_c__String raw_file_contents
     * }
     */
    public static void raw_file_contents(MemorySegment struct, MemorySegment fieldValue) {
        MemorySegment.copy(fieldValue, 0L, struct, raw_file_contents$OFFSET, raw_file_contents$LAYOUT.byteSize());
    }

    /**
     * Obtains a slice of {@code arrayParam} which selects the array element at {@code index}.
     * The returned segment has address {@code arrayParam.address() + index * layout().byteSize()}
     */
    public static MemorySegment asSlice(MemorySegment array, long index) {
        return array.asSlice(layout().byteSize() * index);
    }

    /**
     * The size (in bytes) of this struct
     */
    public static long sizeof() { return layout().byteSize(); }

    /**
     * Allocate a segment of size {@code layout().byteSize()} using {@code allocator}
     */
    public static MemorySegment allocate(SegmentAllocator allocator) {
        return allocator.allocate(layout());
    }

    /**
     * Allocate an array of size {@code elementCount} using {@code allocator}.
     * The returned segment has size {@code elementCount * layout().byteSize()}.
     */
    public static MemorySegment allocateArray(long elementCount, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(elementCount, layout()));
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, Arena arena, Consumer<MemorySegment> cleanup) {
        return reinterpret(addr, 1, arena, cleanup);
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code elementCount * layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, long elementCount, Arena arena, Consumer<MemorySegment> cleanup) {
        return addr.reinterpret(layout().byteSize() * elementCount, arena, cleanup);
    }
}

