// Generated by jextract

package org.ros2.rcl.msgs;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * struct sensor_msgs__msg__MultiDOFJointState {
 *     std_msgs__msg__Header header;
 *     rosidl_runtime_c__String__Sequence joint_names;
 *     geometry_msgs__msg__Transform__Sequence transforms;
 *     geometry_msgs__msg__Twist__Sequence twist;
 *     geometry_msgs__msg__Wrench__Sequence wrench;
 * }
 * }
 */
public class sensor_msgs__msg__MultiDOFJointState {

    sensor_msgs__msg__MultiDOFJointState() {
        // Should not be called directly
    }

    private static final GroupLayout $LAYOUT = MemoryLayout.structLayout(
        std_msgs__msg__Header.layout().withName("header"),
        rosidl_runtime_c__String__Sequence.layout().withName("joint_names"),
        geometry_msgs__msg__Transform__Sequence.layout().withName("transforms"),
        geometry_msgs__msg__Twist__Sequence.layout().withName("twist"),
        geometry_msgs__msg__Wrench__Sequence.layout().withName("wrench")
    ).withName("sensor_msgs__msg__MultiDOFJointState");

    /**
     * The layout of this struct
     */
    public static final GroupLayout layout() {
        return $LAYOUT;
    }

    private static final GroupLayout header$LAYOUT = (GroupLayout)$LAYOUT.select(groupElement("header"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * std_msgs__msg__Header header
     * }
     */
    public static final GroupLayout header$layout() {
        return header$LAYOUT;
    }

    private static final long header$OFFSET = $LAYOUT.byteOffset(groupElement("header"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * std_msgs__msg__Header header
     * }
     */
    public static final long header$offset() {
        return header$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * std_msgs__msg__Header header
     * }
     */
    public static MemorySegment header(MemorySegment struct) {
        return struct.asSlice(header$OFFSET, header$LAYOUT.byteSize());
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * std_msgs__msg__Header header
     * }
     */
    public static void header(MemorySegment struct, MemorySegment fieldValue) {
        MemorySegment.copy(fieldValue, 0L, struct, header$OFFSET, header$LAYOUT.byteSize());
    }

    private static final GroupLayout joint_names$LAYOUT = (GroupLayout)$LAYOUT.select(groupElement("joint_names"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * rosidl_runtime_c__String__Sequence joint_names
     * }
     */
    public static final GroupLayout joint_names$layout() {
        return joint_names$LAYOUT;
    }

    private static final long joint_names$OFFSET = $LAYOUT.byteOffset(groupElement("joint_names"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * rosidl_runtime_c__String__Sequence joint_names
     * }
     */
    public static final long joint_names$offset() {
        return joint_names$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * rosidl_runtime_c__String__Sequence joint_names
     * }
     */
    public static MemorySegment joint_names(MemorySegment struct) {
        return struct.asSlice(joint_names$OFFSET, joint_names$LAYOUT.byteSize());
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * rosidl_runtime_c__String__Sequence joint_names
     * }
     */
    public static void joint_names(MemorySegment struct, MemorySegment fieldValue) {
        MemorySegment.copy(fieldValue, 0L, struct, joint_names$OFFSET, joint_names$LAYOUT.byteSize());
    }

    private static final GroupLayout transforms$LAYOUT = (GroupLayout)$LAYOUT.select(groupElement("transforms"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * geometry_msgs__msg__Transform__Sequence transforms
     * }
     */
    public static final GroupLayout transforms$layout() {
        return transforms$LAYOUT;
    }

    private static final long transforms$OFFSET = $LAYOUT.byteOffset(groupElement("transforms"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * geometry_msgs__msg__Transform__Sequence transforms
     * }
     */
    public static final long transforms$offset() {
        return transforms$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * geometry_msgs__msg__Transform__Sequence transforms
     * }
     */
    public static MemorySegment transforms(MemorySegment struct) {
        return struct.asSlice(transforms$OFFSET, transforms$LAYOUT.byteSize());
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * geometry_msgs__msg__Transform__Sequence transforms
     * }
     */
    public static void transforms(MemorySegment struct, MemorySegment fieldValue) {
        MemorySegment.copy(fieldValue, 0L, struct, transforms$OFFSET, transforms$LAYOUT.byteSize());
    }

    private static final GroupLayout twist$LAYOUT = (GroupLayout)$LAYOUT.select(groupElement("twist"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * geometry_msgs__msg__Twist__Sequence twist
     * }
     */
    public static final GroupLayout twist$layout() {
        return twist$LAYOUT;
    }

    private static final long twist$OFFSET = $LAYOUT.byteOffset(groupElement("twist"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * geometry_msgs__msg__Twist__Sequence twist
     * }
     */
    public static final long twist$offset() {
        return twist$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * geometry_msgs__msg__Twist__Sequence twist
     * }
     */
    public static MemorySegment twist(MemorySegment struct) {
        return struct.asSlice(twist$OFFSET, twist$LAYOUT.byteSize());
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * geometry_msgs__msg__Twist__Sequence twist
     * }
     */
    public static void twist(MemorySegment struct, MemorySegment fieldValue) {
        MemorySegment.copy(fieldValue, 0L, struct, twist$OFFSET, twist$LAYOUT.byteSize());
    }

    private static final GroupLayout wrench$LAYOUT = (GroupLayout)$LAYOUT.select(groupElement("wrench"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * geometry_msgs__msg__Wrench__Sequence wrench
     * }
     */
    public static final GroupLayout wrench$layout() {
        return wrench$LAYOUT;
    }

    private static final long wrench$OFFSET = $LAYOUT.byteOffset(groupElement("wrench"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * geometry_msgs__msg__Wrench__Sequence wrench
     * }
     */
    public static final long wrench$offset() {
        return wrench$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * geometry_msgs__msg__Wrench__Sequence wrench
     * }
     */
    public static MemorySegment wrench(MemorySegment struct) {
        return struct.asSlice(wrench$OFFSET, wrench$LAYOUT.byteSize());
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * geometry_msgs__msg__Wrench__Sequence wrench
     * }
     */
    public static void wrench(MemorySegment struct, MemorySegment fieldValue) {
        MemorySegment.copy(fieldValue, 0L, struct, wrench$OFFSET, wrench$LAYOUT.byteSize());
    }

    /**
     * Obtains a slice of {@code arrayParam} which selects the array element at {@code index}.
     * The returned segment has address {@code arrayParam.address() + index * layout().byteSize()}
     */
    public static MemorySegment asSlice(MemorySegment array, long index) {
        return array.asSlice(layout().byteSize() * index);
    }

    /**
     * The size (in bytes) of this struct
     */
    public static long sizeof() { return layout().byteSize(); }

    /**
     * Allocate a segment of size {@code layout().byteSize()} using {@code allocator}
     */
    public static MemorySegment allocate(SegmentAllocator allocator) {
        return allocator.allocate(layout());
    }

    /**
     * Allocate an array of size {@code elementCount} using {@code allocator}.
     * The returned segment has size {@code elementCount * layout().byteSize()}.
     */
    public static MemorySegment allocateArray(long elementCount, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(elementCount, layout()));
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, Arena arena, Consumer<MemorySegment> cleanup) {
        return reinterpret(addr, 1, arena, cleanup);
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code elementCount * layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, long elementCount, Arena arena, Consumer<MemorySegment> cleanup) {
        return addr.reinterpret(layout().byteSize() * elementCount, arena, cleanup);
    }
}

