// Generated by jextract

package org.ros2.rcl.msgs;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * struct sensor_msgs__msg__Imu {
 *     std_msgs__msg__Header header;
 *     geometry_msgs__msg__Quaternion orientation;
 *     double orientation_covariance[9];
 *     geometry_msgs__msg__Vector3 angular_velocity;
 *     double angular_velocity_covariance[9];
 *     geometry_msgs__msg__Vector3 linear_acceleration;
 *     double linear_acceleration_covariance[9];
 * }
 * }
 */
public class sensor_msgs__msg__Imu {

    sensor_msgs__msg__Imu() {
        // Should not be called directly
    }

    private static final GroupLayout $LAYOUT = MemoryLayout.structLayout(
        std_msgs__msg__Header.layout().withName("header"),
        geometry_msgs__msg__Quaternion.layout().withName("orientation"),
        MemoryLayout.sequenceLayout(9, SENSOR_MSGS_Lib.C_DOUBLE).withName("orientation_covariance"),
        geometry_msgs__msg__Vector3.layout().withName("angular_velocity"),
        MemoryLayout.sequenceLayout(9, SENSOR_MSGS_Lib.C_DOUBLE).withName("angular_velocity_covariance"),
        geometry_msgs__msg__Vector3.layout().withName("linear_acceleration"),
        MemoryLayout.sequenceLayout(9, SENSOR_MSGS_Lib.C_DOUBLE).withName("linear_acceleration_covariance")
    ).withName("sensor_msgs__msg__Imu");

    /**
     * The layout of this struct
     */
    public static final GroupLayout layout() {
        return $LAYOUT;
    }

    private static final GroupLayout header$LAYOUT = (GroupLayout)$LAYOUT.select(groupElement("header"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * std_msgs__msg__Header header
     * }
     */
    public static final GroupLayout header$layout() {
        return header$LAYOUT;
    }

    private static final long header$OFFSET = $LAYOUT.byteOffset(groupElement("header"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * std_msgs__msg__Header header
     * }
     */
    public static final long header$offset() {
        return header$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * std_msgs__msg__Header header
     * }
     */
    public static MemorySegment header(MemorySegment struct) {
        return struct.asSlice(header$OFFSET, header$LAYOUT.byteSize());
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * std_msgs__msg__Header header
     * }
     */
    public static void header(MemorySegment struct, MemorySegment fieldValue) {
        MemorySegment.copy(fieldValue, 0L, struct, header$OFFSET, header$LAYOUT.byteSize());
    }

    private static final GroupLayout orientation$LAYOUT = (GroupLayout)$LAYOUT.select(groupElement("orientation"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * geometry_msgs__msg__Quaternion orientation
     * }
     */
    public static final GroupLayout orientation$layout() {
        return orientation$LAYOUT;
    }

    private static final long orientation$OFFSET = $LAYOUT.byteOffset(groupElement("orientation"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * geometry_msgs__msg__Quaternion orientation
     * }
     */
    public static final long orientation$offset() {
        return orientation$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * geometry_msgs__msg__Quaternion orientation
     * }
     */
    public static MemorySegment orientation(MemorySegment struct) {
        return struct.asSlice(orientation$OFFSET, orientation$LAYOUT.byteSize());
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * geometry_msgs__msg__Quaternion orientation
     * }
     */
    public static void orientation(MemorySegment struct, MemorySegment fieldValue) {
        MemorySegment.copy(fieldValue, 0L, struct, orientation$OFFSET, orientation$LAYOUT.byteSize());
    }

    private static final SequenceLayout orientation_covariance$LAYOUT = (SequenceLayout)$LAYOUT.select(groupElement("orientation_covariance"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * double orientation_covariance[9]
     * }
     */
    public static final SequenceLayout orientation_covariance$layout() {
        return orientation_covariance$LAYOUT;
    }

    private static final long orientation_covariance$OFFSET = $LAYOUT.byteOffset(groupElement("orientation_covariance"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * double orientation_covariance[9]
     * }
     */
    public static final long orientation_covariance$offset() {
        return orientation_covariance$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * double orientation_covariance[9]
     * }
     */
    public static MemorySegment orientation_covariance(MemorySegment struct) {
        return struct.asSlice(orientation_covariance$OFFSET, orientation_covariance$LAYOUT.byteSize());
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * double orientation_covariance[9]
     * }
     */
    public static void orientation_covariance(MemorySegment struct, MemorySegment fieldValue) {
        MemorySegment.copy(fieldValue, 0L, struct, orientation_covariance$OFFSET, orientation_covariance$LAYOUT.byteSize());
    }

    private static long[] orientation_covariance$DIMS = { 9 };

    /**
     * Dimensions for array field:
     * {@snippet lang=c :
     * double orientation_covariance[9]
     * }
     */
    public static long[] orientation_covariance$dimensions() {
        return orientation_covariance$DIMS;
    }
    private static final VarHandle orientation_covariance$ELEM_HANDLE = orientation_covariance$LAYOUT.varHandle(sequenceElement());

    /**
     * Indexed getter for field:
     * {@snippet lang=c :
     * double orientation_covariance[9]
     * }
     */
    public static double orientation_covariance(MemorySegment struct, long index0) {
        return (double)orientation_covariance$ELEM_HANDLE.get(struct, orientation_covariance$OFFSET, index0);
    }

    /**
     * Indexed setter for field:
     * {@snippet lang=c :
     * double orientation_covariance[9]
     * }
     */
    public static void orientation_covariance(MemorySegment struct, long index0, double fieldValue) {
        orientation_covariance$ELEM_HANDLE.set(struct, orientation_covariance$OFFSET, index0, fieldValue);
    }

    private static final GroupLayout angular_velocity$LAYOUT = (GroupLayout)$LAYOUT.select(groupElement("angular_velocity"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * geometry_msgs__msg__Vector3 angular_velocity
     * }
     */
    public static final GroupLayout angular_velocity$layout() {
        return angular_velocity$LAYOUT;
    }

    private static final long angular_velocity$OFFSET = $LAYOUT.byteOffset(groupElement("angular_velocity"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * geometry_msgs__msg__Vector3 angular_velocity
     * }
     */
    public static final long angular_velocity$offset() {
        return angular_velocity$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * geometry_msgs__msg__Vector3 angular_velocity
     * }
     */
    public static MemorySegment angular_velocity(MemorySegment struct) {
        return struct.asSlice(angular_velocity$OFFSET, angular_velocity$LAYOUT.byteSize());
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * geometry_msgs__msg__Vector3 angular_velocity
     * }
     */
    public static void angular_velocity(MemorySegment struct, MemorySegment fieldValue) {
        MemorySegment.copy(fieldValue, 0L, struct, angular_velocity$OFFSET, angular_velocity$LAYOUT.byteSize());
    }

    private static final SequenceLayout angular_velocity_covariance$LAYOUT = (SequenceLayout)$LAYOUT.select(groupElement("angular_velocity_covariance"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * double angular_velocity_covariance[9]
     * }
     */
    public static final SequenceLayout angular_velocity_covariance$layout() {
        return angular_velocity_covariance$LAYOUT;
    }

    private static final long angular_velocity_covariance$OFFSET = $LAYOUT.byteOffset(groupElement("angular_velocity_covariance"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * double angular_velocity_covariance[9]
     * }
     */
    public static final long angular_velocity_covariance$offset() {
        return angular_velocity_covariance$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * double angular_velocity_covariance[9]
     * }
     */
    public static MemorySegment angular_velocity_covariance(MemorySegment struct) {
        return struct.asSlice(angular_velocity_covariance$OFFSET, angular_velocity_covariance$LAYOUT.byteSize());
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * double angular_velocity_covariance[9]
     * }
     */
    public static void angular_velocity_covariance(MemorySegment struct, MemorySegment fieldValue) {
        MemorySegment.copy(fieldValue, 0L, struct, angular_velocity_covariance$OFFSET, angular_velocity_covariance$LAYOUT.byteSize());
    }

    private static long[] angular_velocity_covariance$DIMS = { 9 };

    /**
     * Dimensions for array field:
     * {@snippet lang=c :
     * double angular_velocity_covariance[9]
     * }
     */
    public static long[] angular_velocity_covariance$dimensions() {
        return angular_velocity_covariance$DIMS;
    }
    private static final VarHandle angular_velocity_covariance$ELEM_HANDLE = angular_velocity_covariance$LAYOUT.varHandle(sequenceElement());

    /**
     * Indexed getter for field:
     * {@snippet lang=c :
     * double angular_velocity_covariance[9]
     * }
     */
    public static double angular_velocity_covariance(MemorySegment struct, long index0) {
        return (double)angular_velocity_covariance$ELEM_HANDLE.get(struct, angular_velocity_covariance$OFFSET, index0);
    }

    /**
     * Indexed setter for field:
     * {@snippet lang=c :
     * double angular_velocity_covariance[9]
     * }
     */
    public static void angular_velocity_covariance(MemorySegment struct, long index0, double fieldValue) {
        angular_velocity_covariance$ELEM_HANDLE.set(struct, angular_velocity_covariance$OFFSET, index0, fieldValue);
    }

    private static final GroupLayout linear_acceleration$LAYOUT = (GroupLayout)$LAYOUT.select(groupElement("linear_acceleration"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * geometry_msgs__msg__Vector3 linear_acceleration
     * }
     */
    public static final GroupLayout linear_acceleration$layout() {
        return linear_acceleration$LAYOUT;
    }

    private static final long linear_acceleration$OFFSET = $LAYOUT.byteOffset(groupElement("linear_acceleration"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * geometry_msgs__msg__Vector3 linear_acceleration
     * }
     */
    public static final long linear_acceleration$offset() {
        return linear_acceleration$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * geometry_msgs__msg__Vector3 linear_acceleration
     * }
     */
    public static MemorySegment linear_acceleration(MemorySegment struct) {
        return struct.asSlice(linear_acceleration$OFFSET, linear_acceleration$LAYOUT.byteSize());
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * geometry_msgs__msg__Vector3 linear_acceleration
     * }
     */
    public static void linear_acceleration(MemorySegment struct, MemorySegment fieldValue) {
        MemorySegment.copy(fieldValue, 0L, struct, linear_acceleration$OFFSET, linear_acceleration$LAYOUT.byteSize());
    }

    private static final SequenceLayout linear_acceleration_covariance$LAYOUT = (SequenceLayout)$LAYOUT.select(groupElement("linear_acceleration_covariance"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * double linear_acceleration_covariance[9]
     * }
     */
    public static final SequenceLayout linear_acceleration_covariance$layout() {
        return linear_acceleration_covariance$LAYOUT;
    }

    private static final long linear_acceleration_covariance$OFFSET = $LAYOUT.byteOffset(groupElement("linear_acceleration_covariance"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * double linear_acceleration_covariance[9]
     * }
     */
    public static final long linear_acceleration_covariance$offset() {
        return linear_acceleration_covariance$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * double linear_acceleration_covariance[9]
     * }
     */
    public static MemorySegment linear_acceleration_covariance(MemorySegment struct) {
        return struct.asSlice(linear_acceleration_covariance$OFFSET, linear_acceleration_covariance$LAYOUT.byteSize());
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * double linear_acceleration_covariance[9]
     * }
     */
    public static void linear_acceleration_covariance(MemorySegment struct, MemorySegment fieldValue) {
        MemorySegment.copy(fieldValue, 0L, struct, linear_acceleration_covariance$OFFSET, linear_acceleration_covariance$LAYOUT.byteSize());
    }

    private static long[] linear_acceleration_covariance$DIMS = { 9 };

    /**
     * Dimensions for array field:
     * {@snippet lang=c :
     * double linear_acceleration_covariance[9]
     * }
     */
    public static long[] linear_acceleration_covariance$dimensions() {
        return linear_acceleration_covariance$DIMS;
    }
    private static final VarHandle linear_acceleration_covariance$ELEM_HANDLE = linear_acceleration_covariance$LAYOUT.varHandle(sequenceElement());

    /**
     * Indexed getter for field:
     * {@snippet lang=c :
     * double linear_acceleration_covariance[9]
     * }
     */
    public static double linear_acceleration_covariance(MemorySegment struct, long index0) {
        return (double)linear_acceleration_covariance$ELEM_HANDLE.get(struct, linear_acceleration_covariance$OFFSET, index0);
    }

    /**
     * Indexed setter for field:
     * {@snippet lang=c :
     * double linear_acceleration_covariance[9]
     * }
     */
    public static void linear_acceleration_covariance(MemorySegment struct, long index0, double fieldValue) {
        linear_acceleration_covariance$ELEM_HANDLE.set(struct, linear_acceleration_covariance$OFFSET, index0, fieldValue);
    }

    /**
     * Obtains a slice of {@code arrayParam} which selects the array element at {@code index}.
     * The returned segment has address {@code arrayParam.address() + index * layout().byteSize()}
     */
    public static MemorySegment asSlice(MemorySegment array, long index) {
        return array.asSlice(layout().byteSize() * index);
    }

    /**
     * The size (in bytes) of this struct
     */
    public static long sizeof() { return layout().byteSize(); }

    /**
     * Allocate a segment of size {@code layout().byteSize()} using {@code allocator}
     */
    public static MemorySegment allocate(SegmentAllocator allocator) {
        return allocator.allocate(layout());
    }

    /**
     * Allocate an array of size {@code elementCount} using {@code allocator}.
     * The returned segment has size {@code elementCount * layout().byteSize()}.
     */
    public static MemorySegment allocateArray(long elementCount, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(elementCount, layout()));
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, Arena arena, Consumer<MemorySegment> cleanup) {
        return reinterpret(addr, 1, arena, cleanup);
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code elementCount * layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, long elementCount, Arena arena, Consumer<MemorySegment> cleanup) {
        return addr.reinterpret(layout().byteSize() * elementCount, arena, cleanup);
    }
}

