// Generated by jextract

package org.ros2.rcl.msgs;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * struct sensor_msgs__msg__TimeReference {
 *     std_msgs__msg__Header header;
 *     builtin_interfaces__msg__Time time_ref;
 *     rosidl_runtime_c__String source;
 * }
 * }
 */
public class sensor_msgs__msg__TimeReference {

    sensor_msgs__msg__TimeReference() {
        // Should not be called directly
    }

    private static final GroupLayout $LAYOUT = MemoryLayout.structLayout(
        std_msgs__msg__Header.layout().withName("header"),
        builtin_interfaces__msg__Time.layout().withName("time_ref"),
        rosidl_runtime_c__String.layout().withName("source")
    ).withName("sensor_msgs__msg__TimeReference");

    /**
     * The layout of this struct
     */
    public static final GroupLayout layout() {
        return $LAYOUT;
    }

    private static final GroupLayout header$LAYOUT = (GroupLayout)$LAYOUT.select(groupElement("header"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * std_msgs__msg__Header header
     * }
     */
    public static final GroupLayout header$layout() {
        return header$LAYOUT;
    }

    private static final long header$OFFSET = $LAYOUT.byteOffset(groupElement("header"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * std_msgs__msg__Header header
     * }
     */
    public static final long header$offset() {
        return header$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * std_msgs__msg__Header header
     * }
     */
    public static MemorySegment header(MemorySegment struct) {
        return struct.asSlice(header$OFFSET, header$LAYOUT.byteSize());
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * std_msgs__msg__Header header
     * }
     */
    public static void header(MemorySegment struct, MemorySegment fieldValue) {
        MemorySegment.copy(fieldValue, 0L, struct, header$OFFSET, header$LAYOUT.byteSize());
    }

    private static final GroupLayout time_ref$LAYOUT = (GroupLayout)$LAYOUT.select(groupElement("time_ref"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * builtin_interfaces__msg__Time time_ref
     * }
     */
    public static final GroupLayout time_ref$layout() {
        return time_ref$LAYOUT;
    }

    private static final long time_ref$OFFSET = $LAYOUT.byteOffset(groupElement("time_ref"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * builtin_interfaces__msg__Time time_ref
     * }
     */
    public static final long time_ref$offset() {
        return time_ref$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * builtin_interfaces__msg__Time time_ref
     * }
     */
    public static MemorySegment time_ref(MemorySegment struct) {
        return struct.asSlice(time_ref$OFFSET, time_ref$LAYOUT.byteSize());
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * builtin_interfaces__msg__Time time_ref
     * }
     */
    public static void time_ref(MemorySegment struct, MemorySegment fieldValue) {
        MemorySegment.copy(fieldValue, 0L, struct, time_ref$OFFSET, time_ref$LAYOUT.byteSize());
    }

    private static final GroupLayout source$LAYOUT = (GroupLayout)$LAYOUT.select(groupElement("source"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * rosidl_runtime_c__String source
     * }
     */
    public static final GroupLayout source$layout() {
        return source$LAYOUT;
    }

    private static final long source$OFFSET = $LAYOUT.byteOffset(groupElement("source"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * rosidl_runtime_c__String source
     * }
     */
    public static final long source$offset() {
        return source$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * rosidl_runtime_c__String source
     * }
     */
    public static MemorySegment source(MemorySegment struct) {
        return struct.asSlice(source$OFFSET, source$LAYOUT.byteSize());
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * rosidl_runtime_c__String source
     * }
     */
    public static void source(MemorySegment struct, MemorySegment fieldValue) {
        MemorySegment.copy(fieldValue, 0L, struct, source$OFFSET, source$LAYOUT.byteSize());
    }

    /**
     * Obtains a slice of {@code arrayParam} which selects the array element at {@code index}.
     * The returned segment has address {@code arrayParam.address() + index * layout().byteSize()}
     */
    public static MemorySegment asSlice(MemorySegment array, long index) {
        return array.asSlice(layout().byteSize() * index);
    }

    /**
     * The size (in bytes) of this struct
     */
    public static long sizeof() { return layout().byteSize(); }

    /**
     * Allocate a segment of size {@code layout().byteSize()} using {@code allocator}
     */
    public static MemorySegment allocate(SegmentAllocator allocator) {
        return allocator.allocate(layout());
    }

    /**
     * Allocate an array of size {@code elementCount} using {@code allocator}.
     * The returned segment has size {@code elementCount * layout().byteSize()}.
     */
    public static MemorySegment allocateArray(long elementCount, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(elementCount, layout()));
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, Arena arena, Consumer<MemorySegment> cleanup) {
        return reinterpret(addr, 1, arena, cleanup);
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code elementCount * layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, long elementCount, Arena arena, Consumer<MemorySegment> cleanup) {
        return addr.reinterpret(layout().byteSize() * elementCount, arena, cleanup);
    }
}

