// Generated by jextract

package org.ros2.rcl.msgs;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * struct sensor_msgs__msg__JointState {
 *     std_msgs__msg__Header header;
 *     rosidl_runtime_c__String__Sequence name;
 *     rosidl_runtime_c__double__Sequence position;
 *     rosidl_runtime_c__double__Sequence velocity;
 *     rosidl_runtime_c__double__Sequence effort;
 * }
 * }
 */
public class sensor_msgs__msg__JointState {

    sensor_msgs__msg__JointState() {
        // Should not be called directly
    }

    private static final GroupLayout $LAYOUT = MemoryLayout.structLayout(
        std_msgs__msg__Header.layout().withName("header"),
        rosidl_runtime_c__String__Sequence.layout().withName("name"),
        rosidl_runtime_c__double__Sequence.layout().withName("position"),
        rosidl_runtime_c__double__Sequence.layout().withName("velocity"),
        rosidl_runtime_c__double__Sequence.layout().withName("effort")
    ).withName("sensor_msgs__msg__JointState");

    /**
     * The layout of this struct
     */
    public static final GroupLayout layout() {
        return $LAYOUT;
    }

    private static final GroupLayout header$LAYOUT = (GroupLayout)$LAYOUT.select(groupElement("header"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * std_msgs__msg__Header header
     * }
     */
    public static final GroupLayout header$layout() {
        return header$LAYOUT;
    }

    private static final long header$OFFSET = $LAYOUT.byteOffset(groupElement("header"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * std_msgs__msg__Header header
     * }
     */
    public static final long header$offset() {
        return header$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * std_msgs__msg__Header header
     * }
     */
    public static MemorySegment header(MemorySegment struct) {
        return struct.asSlice(header$OFFSET, header$LAYOUT.byteSize());
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * std_msgs__msg__Header header
     * }
     */
    public static void header(MemorySegment struct, MemorySegment fieldValue) {
        MemorySegment.copy(fieldValue, 0L, struct, header$OFFSET, header$LAYOUT.byteSize());
    }

    private static final GroupLayout name$LAYOUT = (GroupLayout)$LAYOUT.select(groupElement("name"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * rosidl_runtime_c__String__Sequence name
     * }
     */
    public static final GroupLayout name$layout() {
        return name$LAYOUT;
    }

    private static final long name$OFFSET = $LAYOUT.byteOffset(groupElement("name"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * rosidl_runtime_c__String__Sequence name
     * }
     */
    public static final long name$offset() {
        return name$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * rosidl_runtime_c__String__Sequence name
     * }
     */
    public static MemorySegment name(MemorySegment struct) {
        return struct.asSlice(name$OFFSET, name$LAYOUT.byteSize());
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * rosidl_runtime_c__String__Sequence name
     * }
     */
    public static void name(MemorySegment struct, MemorySegment fieldValue) {
        MemorySegment.copy(fieldValue, 0L, struct, name$OFFSET, name$LAYOUT.byteSize());
    }

    private static final GroupLayout position$LAYOUT = (GroupLayout)$LAYOUT.select(groupElement("position"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * rosidl_runtime_c__double__Sequence position
     * }
     */
    public static final GroupLayout position$layout() {
        return position$LAYOUT;
    }

    private static final long position$OFFSET = $LAYOUT.byteOffset(groupElement("position"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * rosidl_runtime_c__double__Sequence position
     * }
     */
    public static final long position$offset() {
        return position$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * rosidl_runtime_c__double__Sequence position
     * }
     */
    public static MemorySegment position(MemorySegment struct) {
        return struct.asSlice(position$OFFSET, position$LAYOUT.byteSize());
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * rosidl_runtime_c__double__Sequence position
     * }
     */
    public static void position(MemorySegment struct, MemorySegment fieldValue) {
        MemorySegment.copy(fieldValue, 0L, struct, position$OFFSET, position$LAYOUT.byteSize());
    }

    private static final GroupLayout velocity$LAYOUT = (GroupLayout)$LAYOUT.select(groupElement("velocity"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * rosidl_runtime_c__double__Sequence velocity
     * }
     */
    public static final GroupLayout velocity$layout() {
        return velocity$LAYOUT;
    }

    private static final long velocity$OFFSET = $LAYOUT.byteOffset(groupElement("velocity"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * rosidl_runtime_c__double__Sequence velocity
     * }
     */
    public static final long velocity$offset() {
        return velocity$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * rosidl_runtime_c__double__Sequence velocity
     * }
     */
    public static MemorySegment velocity(MemorySegment struct) {
        return struct.asSlice(velocity$OFFSET, velocity$LAYOUT.byteSize());
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * rosidl_runtime_c__double__Sequence velocity
     * }
     */
    public static void velocity(MemorySegment struct, MemorySegment fieldValue) {
        MemorySegment.copy(fieldValue, 0L, struct, velocity$OFFSET, velocity$LAYOUT.byteSize());
    }

    private static final GroupLayout effort$LAYOUT = (GroupLayout)$LAYOUT.select(groupElement("effort"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * rosidl_runtime_c__double__Sequence effort
     * }
     */
    public static final GroupLayout effort$layout() {
        return effort$LAYOUT;
    }

    private static final long effort$OFFSET = $LAYOUT.byteOffset(groupElement("effort"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * rosidl_runtime_c__double__Sequence effort
     * }
     */
    public static final long effort$offset() {
        return effort$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * rosidl_runtime_c__double__Sequence effort
     * }
     */
    public static MemorySegment effort(MemorySegment struct) {
        return struct.asSlice(effort$OFFSET, effort$LAYOUT.byteSize());
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * rosidl_runtime_c__double__Sequence effort
     * }
     */
    public static void effort(MemorySegment struct, MemorySegment fieldValue) {
        MemorySegment.copy(fieldValue, 0L, struct, effort$OFFSET, effort$LAYOUT.byteSize());
    }

    /**
     * Obtains a slice of {@code arrayParam} which selects the array element at {@code index}.
     * The returned segment has address {@code arrayParam.address() + index * layout().byteSize()}
     */
    public static MemorySegment asSlice(MemorySegment array, long index) {
        return array.asSlice(layout().byteSize() * index);
    }

    /**
     * The size (in bytes) of this struct
     */
    public static long sizeof() { return layout().byteSize(); }

    /**
     * Allocate a segment of size {@code layout().byteSize()} using {@code allocator}
     */
    public static MemorySegment allocate(SegmentAllocator allocator) {
        return allocator.allocate(layout());
    }

    /**
     * Allocate an array of size {@code elementCount} using {@code allocator}.
     * The returned segment has size {@code elementCount * layout().byteSize()}.
     */
    public static MemorySegment allocateArray(long elementCount, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(elementCount, layout()));
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, Arena arena, Consumer<MemorySegment> cleanup) {
        return reinterpret(addr, 1, arena, cleanup);
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code elementCount * layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, long elementCount, Arena arena, Consumer<MemorySegment> cleanup) {
        return addr.reinterpret(layout().byteSize() * elementCount, arena, cleanup);
    }
}

