// Generated by jextract

package org.ros2.rcl.msgs;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * struct sensor_msgs__msg__NavSatStatus {
 *     int8_t status;
 *     uint16_t service;
 * }
 * }
 */
public class sensor_msgs__msg__NavSatStatus {

    sensor_msgs__msg__NavSatStatus() {
        // Should not be called directly
    }

    private static final GroupLayout $LAYOUT = MemoryLayout.structLayout(
        SENSOR_MSGS_Lib.C_CHAR.withName("status"),
        MemoryLayout.paddingLayout(1),
        SENSOR_MSGS_Lib.C_SHORT.withName("service")
    ).withName("sensor_msgs__msg__NavSatStatus");

    /**
     * The layout of this struct
     */
    public static final GroupLayout layout() {
        return $LAYOUT;
    }

    private static final OfByte status$LAYOUT = (OfByte)$LAYOUT.select(groupElement("status"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * int8_t status
     * }
     */
    public static final OfByte status$layout() {
        return status$LAYOUT;
    }

    private static final long status$OFFSET = $LAYOUT.byteOffset(groupElement("status"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * int8_t status
     * }
     */
    public static final long status$offset() {
        return status$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * int8_t status
     * }
     */
    public static byte status(MemorySegment struct) {
        return struct.get(status$LAYOUT, status$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * int8_t status
     * }
     */
    public static void status(MemorySegment struct, byte fieldValue) {
        struct.set(status$LAYOUT, status$OFFSET, fieldValue);
    }

    private static final OfShort service$LAYOUT = (OfShort)$LAYOUT.select(groupElement("service"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * uint16_t service
     * }
     */
    public static final OfShort service$layout() {
        return service$LAYOUT;
    }

    private static final long service$OFFSET = $LAYOUT.byteOffset(groupElement("service"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * uint16_t service
     * }
     */
    public static final long service$offset() {
        return service$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * uint16_t service
     * }
     */
    public static short service(MemorySegment struct) {
        return struct.get(service$LAYOUT, service$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * uint16_t service
     * }
     */
    public static void service(MemorySegment struct, short fieldValue) {
        struct.set(service$LAYOUT, service$OFFSET, fieldValue);
    }

    /**
     * Obtains a slice of {@code arrayParam} which selects the array element at {@code index}.
     * The returned segment has address {@code arrayParam.address() + index * layout().byteSize()}
     */
    public static MemorySegment asSlice(MemorySegment array, long index) {
        return array.asSlice(layout().byteSize() * index);
    }

    /**
     * The size (in bytes) of this struct
     */
    public static long sizeof() { return layout().byteSize(); }

    /**
     * Allocate a segment of size {@code layout().byteSize()} using {@code allocator}
     */
    public static MemorySegment allocate(SegmentAllocator allocator) {
        return allocator.allocate(layout());
    }

    /**
     * Allocate an array of size {@code elementCount} using {@code allocator}.
     * The returned segment has size {@code elementCount * layout().byteSize()}.
     */
    public static MemorySegment allocateArray(long elementCount, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(elementCount, layout()));
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, Arena arena, Consumer<MemorySegment> cleanup) {
        return reinterpret(addr, 1, arena, cleanup);
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code elementCount * layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, long elementCount, Arena arena, Consumer<MemorySegment> cleanup) {
        return addr.reinterpret(layout().byteSize() * elementCount, arena, cleanup);
    }
}

