// Generated by jextract

package org.ros2.rcl.msgs;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * struct sensor_msgs__msg__LaserScan {
 *     std_msgs__msg__Header header;
 *     float angle_min;
 *     float angle_max;
 *     float angle_increment;
 *     float time_increment;
 *     float scan_time;
 *     float range_min;
 *     float range_max;
 *     rosidl_runtime_c__float__Sequence ranges;
 *     rosidl_runtime_c__float__Sequence intensities;
 * }
 * }
 */
public class sensor_msgs__msg__LaserScan {

    sensor_msgs__msg__LaserScan() {
        // Should not be called directly
    }

    private static final GroupLayout $LAYOUT = MemoryLayout.structLayout(
        std_msgs__msg__Header.layout().withName("header"),
        SENSOR_MSGS_Lib.C_FLOAT.withName("angle_min"),
        SENSOR_MSGS_Lib.C_FLOAT.withName("angle_max"),
        SENSOR_MSGS_Lib.C_FLOAT.withName("angle_increment"),
        SENSOR_MSGS_Lib.C_FLOAT.withName("time_increment"),
        SENSOR_MSGS_Lib.C_FLOAT.withName("scan_time"),
        SENSOR_MSGS_Lib.C_FLOAT.withName("range_min"),
        SENSOR_MSGS_Lib.C_FLOAT.withName("range_max"),
        MemoryLayout.paddingLayout(4),
        rosidl_runtime_c__float__Sequence.layout().withName("ranges"),
        rosidl_runtime_c__float__Sequence.layout().withName("intensities")
    ).withName("sensor_msgs__msg__LaserScan");

    /**
     * The layout of this struct
     */
    public static final GroupLayout layout() {
        return $LAYOUT;
    }

    private static final GroupLayout header$LAYOUT = (GroupLayout)$LAYOUT.select(groupElement("header"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * std_msgs__msg__Header header
     * }
     */
    public static final GroupLayout header$layout() {
        return header$LAYOUT;
    }

    private static final long header$OFFSET = $LAYOUT.byteOffset(groupElement("header"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * std_msgs__msg__Header header
     * }
     */
    public static final long header$offset() {
        return header$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * std_msgs__msg__Header header
     * }
     */
    public static MemorySegment header(MemorySegment struct) {
        return struct.asSlice(header$OFFSET, header$LAYOUT.byteSize());
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * std_msgs__msg__Header header
     * }
     */
    public static void header(MemorySegment struct, MemorySegment fieldValue) {
        MemorySegment.copy(fieldValue, 0L, struct, header$OFFSET, header$LAYOUT.byteSize());
    }

    private static final OfFloat angle_min$LAYOUT = (OfFloat)$LAYOUT.select(groupElement("angle_min"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * float angle_min
     * }
     */
    public static final OfFloat angle_min$layout() {
        return angle_min$LAYOUT;
    }

    private static final long angle_min$OFFSET = $LAYOUT.byteOffset(groupElement("angle_min"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * float angle_min
     * }
     */
    public static final long angle_min$offset() {
        return angle_min$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * float angle_min
     * }
     */
    public static float angle_min(MemorySegment struct) {
        return struct.get(angle_min$LAYOUT, angle_min$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * float angle_min
     * }
     */
    public static void angle_min(MemorySegment struct, float fieldValue) {
        struct.set(angle_min$LAYOUT, angle_min$OFFSET, fieldValue);
    }

    private static final OfFloat angle_max$LAYOUT = (OfFloat)$LAYOUT.select(groupElement("angle_max"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * float angle_max
     * }
     */
    public static final OfFloat angle_max$layout() {
        return angle_max$LAYOUT;
    }

    private static final long angle_max$OFFSET = $LAYOUT.byteOffset(groupElement("angle_max"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * float angle_max
     * }
     */
    public static final long angle_max$offset() {
        return angle_max$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * float angle_max
     * }
     */
    public static float angle_max(MemorySegment struct) {
        return struct.get(angle_max$LAYOUT, angle_max$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * float angle_max
     * }
     */
    public static void angle_max(MemorySegment struct, float fieldValue) {
        struct.set(angle_max$LAYOUT, angle_max$OFFSET, fieldValue);
    }

    private static final OfFloat angle_increment$LAYOUT = (OfFloat)$LAYOUT.select(groupElement("angle_increment"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * float angle_increment
     * }
     */
    public static final OfFloat angle_increment$layout() {
        return angle_increment$LAYOUT;
    }

    private static final long angle_increment$OFFSET = $LAYOUT.byteOffset(groupElement("angle_increment"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * float angle_increment
     * }
     */
    public static final long angle_increment$offset() {
        return angle_increment$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * float angle_increment
     * }
     */
    public static float angle_increment(MemorySegment struct) {
        return struct.get(angle_increment$LAYOUT, angle_increment$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * float angle_increment
     * }
     */
    public static void angle_increment(MemorySegment struct, float fieldValue) {
        struct.set(angle_increment$LAYOUT, angle_increment$OFFSET, fieldValue);
    }

    private static final OfFloat time_increment$LAYOUT = (OfFloat)$LAYOUT.select(groupElement("time_increment"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * float time_increment
     * }
     */
    public static final OfFloat time_increment$layout() {
        return time_increment$LAYOUT;
    }

    private static final long time_increment$OFFSET = $LAYOUT.byteOffset(groupElement("time_increment"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * float time_increment
     * }
     */
    public static final long time_increment$offset() {
        return time_increment$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * float time_increment
     * }
     */
    public static float time_increment(MemorySegment struct) {
        return struct.get(time_increment$LAYOUT, time_increment$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * float time_increment
     * }
     */
    public static void time_increment(MemorySegment struct, float fieldValue) {
        struct.set(time_increment$LAYOUT, time_increment$OFFSET, fieldValue);
    }

    private static final OfFloat scan_time$LAYOUT = (OfFloat)$LAYOUT.select(groupElement("scan_time"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * float scan_time
     * }
     */
    public static final OfFloat scan_time$layout() {
        return scan_time$LAYOUT;
    }

    private static final long scan_time$OFFSET = $LAYOUT.byteOffset(groupElement("scan_time"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * float scan_time
     * }
     */
    public static final long scan_time$offset() {
        return scan_time$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * float scan_time
     * }
     */
    public static float scan_time(MemorySegment struct) {
        return struct.get(scan_time$LAYOUT, scan_time$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * float scan_time
     * }
     */
    public static void scan_time(MemorySegment struct, float fieldValue) {
        struct.set(scan_time$LAYOUT, scan_time$OFFSET, fieldValue);
    }

    private static final OfFloat range_min$LAYOUT = (OfFloat)$LAYOUT.select(groupElement("range_min"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * float range_min
     * }
     */
    public static final OfFloat range_min$layout() {
        return range_min$LAYOUT;
    }

    private static final long range_min$OFFSET = $LAYOUT.byteOffset(groupElement("range_min"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * float range_min
     * }
     */
    public static final long range_min$offset() {
        return range_min$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * float range_min
     * }
     */
    public static float range_min(MemorySegment struct) {
        return struct.get(range_min$LAYOUT, range_min$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * float range_min
     * }
     */
    public static void range_min(MemorySegment struct, float fieldValue) {
        struct.set(range_min$LAYOUT, range_min$OFFSET, fieldValue);
    }

    private static final OfFloat range_max$LAYOUT = (OfFloat)$LAYOUT.select(groupElement("range_max"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * float range_max
     * }
     */
    public static final OfFloat range_max$layout() {
        return range_max$LAYOUT;
    }

    private static final long range_max$OFFSET = $LAYOUT.byteOffset(groupElement("range_max"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * float range_max
     * }
     */
    public static final long range_max$offset() {
        return range_max$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * float range_max
     * }
     */
    public static float range_max(MemorySegment struct) {
        return struct.get(range_max$LAYOUT, range_max$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * float range_max
     * }
     */
    public static void range_max(MemorySegment struct, float fieldValue) {
        struct.set(range_max$LAYOUT, range_max$OFFSET, fieldValue);
    }

    private static final GroupLayout ranges$LAYOUT = (GroupLayout)$LAYOUT.select(groupElement("ranges"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * rosidl_runtime_c__float__Sequence ranges
     * }
     */
    public static final GroupLayout ranges$layout() {
        return ranges$LAYOUT;
    }

    private static final long ranges$OFFSET = $LAYOUT.byteOffset(groupElement("ranges"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * rosidl_runtime_c__float__Sequence ranges
     * }
     */
    public static final long ranges$offset() {
        return ranges$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * rosidl_runtime_c__float__Sequence ranges
     * }
     */
    public static MemorySegment ranges(MemorySegment struct) {
        return struct.asSlice(ranges$OFFSET, ranges$LAYOUT.byteSize());
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * rosidl_runtime_c__float__Sequence ranges
     * }
     */
    public static void ranges(MemorySegment struct, MemorySegment fieldValue) {
        MemorySegment.copy(fieldValue, 0L, struct, ranges$OFFSET, ranges$LAYOUT.byteSize());
    }

    private static final GroupLayout intensities$LAYOUT = (GroupLayout)$LAYOUT.select(groupElement("intensities"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * rosidl_runtime_c__float__Sequence intensities
     * }
     */
    public static final GroupLayout intensities$layout() {
        return intensities$LAYOUT;
    }

    private static final long intensities$OFFSET = $LAYOUT.byteOffset(groupElement("intensities"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * rosidl_runtime_c__float__Sequence intensities
     * }
     */
    public static final long intensities$offset() {
        return intensities$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * rosidl_runtime_c__float__Sequence intensities
     * }
     */
    public static MemorySegment intensities(MemorySegment struct) {
        return struct.asSlice(intensities$OFFSET, intensities$LAYOUT.byteSize());
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * rosidl_runtime_c__float__Sequence intensities
     * }
     */
    public static void intensities(MemorySegment struct, MemorySegment fieldValue) {
        MemorySegment.copy(fieldValue, 0L, struct, intensities$OFFSET, intensities$LAYOUT.byteSize());
    }

    /**
     * Obtains a slice of {@code arrayParam} which selects the array element at {@code index}.
     * The returned segment has address {@code arrayParam.address() + index * layout().byteSize()}
     */
    public static MemorySegment asSlice(MemorySegment array, long index) {
        return array.asSlice(layout().byteSize() * index);
    }

    /**
     * The size (in bytes) of this struct
     */
    public static long sizeof() { return layout().byteSize(); }

    /**
     * Allocate a segment of size {@code layout().byteSize()} using {@code allocator}
     */
    public static MemorySegment allocate(SegmentAllocator allocator) {
        return allocator.allocate(layout());
    }

    /**
     * Allocate an array of size {@code elementCount} using {@code allocator}.
     * The returned segment has size {@code elementCount * layout().byteSize()}.
     */
    public static MemorySegment allocateArray(long elementCount, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(elementCount, layout()));
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, Arena arena, Consumer<MemorySegment> cleanup) {
        return reinterpret(addr, 1, arena, cleanup);
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code elementCount * layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, long elementCount, Arena arena, Consumer<MemorySegment> cleanup) {
        return addr.reinterpret(layout().byteSize() * elementCount, arena, cleanup);
    }
}

