// Generated by jextract

package org.ros2.rcl.msgs;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * struct sensor_msgs__msg__FluidPressure {
 *     std_msgs__msg__Header header;
 *     double fluid_pressure;
 *     double variance;
 * }
 * }
 */
public class sensor_msgs__msg__FluidPressure {

    sensor_msgs__msg__FluidPressure() {
        // Should not be called directly
    }

    private static final GroupLayout $LAYOUT = MemoryLayout.structLayout(
        std_msgs__msg__Header.layout().withName("header"),
        SENSOR_MSGS_Lib.C_DOUBLE.withName("fluid_pressure"),
        SENSOR_MSGS_Lib.C_DOUBLE.withName("variance")
    ).withName("sensor_msgs__msg__FluidPressure");

    /**
     * The layout of this struct
     */
    public static final GroupLayout layout() {
        return $LAYOUT;
    }

    private static final GroupLayout header$LAYOUT = (GroupLayout)$LAYOUT.select(groupElement("header"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * std_msgs__msg__Header header
     * }
     */
    public static final GroupLayout header$layout() {
        return header$LAYOUT;
    }

    private static final long header$OFFSET = $LAYOUT.byteOffset(groupElement("header"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * std_msgs__msg__Header header
     * }
     */
    public static final long header$offset() {
        return header$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * std_msgs__msg__Header header
     * }
     */
    public static MemorySegment header(MemorySegment struct) {
        return struct.asSlice(header$OFFSET, header$LAYOUT.byteSize());
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * std_msgs__msg__Header header
     * }
     */
    public static void header(MemorySegment struct, MemorySegment fieldValue) {
        MemorySegment.copy(fieldValue, 0L, struct, header$OFFSET, header$LAYOUT.byteSize());
    }

    private static final OfDouble fluid_pressure$LAYOUT = (OfDouble)$LAYOUT.select(groupElement("fluid_pressure"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * double fluid_pressure
     * }
     */
    public static final OfDouble fluid_pressure$layout() {
        return fluid_pressure$LAYOUT;
    }

    private static final long fluid_pressure$OFFSET = $LAYOUT.byteOffset(groupElement("fluid_pressure"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * double fluid_pressure
     * }
     */
    public static final long fluid_pressure$offset() {
        return fluid_pressure$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * double fluid_pressure
     * }
     */
    public static double fluid_pressure(MemorySegment struct) {
        return struct.get(fluid_pressure$LAYOUT, fluid_pressure$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * double fluid_pressure
     * }
     */
    public static void fluid_pressure(MemorySegment struct, double fieldValue) {
        struct.set(fluid_pressure$LAYOUT, fluid_pressure$OFFSET, fieldValue);
    }

    private static final OfDouble variance$LAYOUT = (OfDouble)$LAYOUT.select(groupElement("variance"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * double variance
     * }
     */
    public static final OfDouble variance$layout() {
        return variance$LAYOUT;
    }

    private static final long variance$OFFSET = $LAYOUT.byteOffset(groupElement("variance"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * double variance
     * }
     */
    public static final long variance$offset() {
        return variance$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * double variance
     * }
     */
    public static double variance(MemorySegment struct) {
        return struct.get(variance$LAYOUT, variance$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * double variance
     * }
     */
    public static void variance(MemorySegment struct, double fieldValue) {
        struct.set(variance$LAYOUT, variance$OFFSET, fieldValue);
    }

    /**
     * Obtains a slice of {@code arrayParam} which selects the array element at {@code index}.
     * The returned segment has address {@code arrayParam.address() + index * layout().byteSize()}
     */
    public static MemorySegment asSlice(MemorySegment array, long index) {
        return array.asSlice(layout().byteSize() * index);
    }

    /**
     * The size (in bytes) of this struct
     */
    public static long sizeof() { return layout().byteSize(); }

    /**
     * Allocate a segment of size {@code layout().byteSize()} using {@code allocator}
     */
    public static MemorySegment allocate(SegmentAllocator allocator) {
        return allocator.allocate(layout());
    }

    /**
     * Allocate an array of size {@code elementCount} using {@code allocator}.
     * The returned segment has size {@code elementCount * layout().byteSize()}.
     */
    public static MemorySegment allocateArray(long elementCount, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(elementCount, layout()));
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, Arena arena, Consumer<MemorySegment> cleanup) {
        return reinterpret(addr, 1, arena, cleanup);
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code elementCount * layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, long elementCount, Arena arena, Consumer<MemorySegment> cleanup) {
        return addr.reinterpret(layout().byteSize() * elementCount, arena, cleanup);
    }
}

