// Generated by jextract

package org.ros2.rcl.msgs;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * struct sensor_msgs__msg__MagneticField {
 *     std_msgs__msg__Header header;
 *     geometry_msgs__msg__Vector3 magnetic_field;
 *     double magnetic_field_covariance[9];
 * }
 * }
 */
public class sensor_msgs__msg__MagneticField {

    sensor_msgs__msg__MagneticField() {
        // Should not be called directly
    }

    private static final GroupLayout $LAYOUT = MemoryLayout.structLayout(
        std_msgs__msg__Header.layout().withName("header"),
        geometry_msgs__msg__Vector3.layout().withName("magnetic_field"),
        MemoryLayout.sequenceLayout(9, SENSOR_MSGS_Lib.C_DOUBLE).withName("magnetic_field_covariance")
    ).withName("sensor_msgs__msg__MagneticField");

    /**
     * The layout of this struct
     */
    public static final GroupLayout layout() {
        return $LAYOUT;
    }

    private static final GroupLayout header$LAYOUT = (GroupLayout)$LAYOUT.select(groupElement("header"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * std_msgs__msg__Header header
     * }
     */
    public static final GroupLayout header$layout() {
        return header$LAYOUT;
    }

    private static final long header$OFFSET = $LAYOUT.byteOffset(groupElement("header"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * std_msgs__msg__Header header
     * }
     */
    public static final long header$offset() {
        return header$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * std_msgs__msg__Header header
     * }
     */
    public static MemorySegment header(MemorySegment struct) {
        return struct.asSlice(header$OFFSET, header$LAYOUT.byteSize());
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * std_msgs__msg__Header header
     * }
     */
    public static void header(MemorySegment struct, MemorySegment fieldValue) {
        MemorySegment.copy(fieldValue, 0L, struct, header$OFFSET, header$LAYOUT.byteSize());
    }

    private static final GroupLayout magnetic_field$LAYOUT = (GroupLayout)$LAYOUT.select(groupElement("magnetic_field"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * geometry_msgs__msg__Vector3 magnetic_field
     * }
     */
    public static final GroupLayout magnetic_field$layout() {
        return magnetic_field$LAYOUT;
    }

    private static final long magnetic_field$OFFSET = $LAYOUT.byteOffset(groupElement("magnetic_field"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * geometry_msgs__msg__Vector3 magnetic_field
     * }
     */
    public static final long magnetic_field$offset() {
        return magnetic_field$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * geometry_msgs__msg__Vector3 magnetic_field
     * }
     */
    public static MemorySegment magnetic_field(MemorySegment struct) {
        return struct.asSlice(magnetic_field$OFFSET, magnetic_field$LAYOUT.byteSize());
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * geometry_msgs__msg__Vector3 magnetic_field
     * }
     */
    public static void magnetic_field(MemorySegment struct, MemorySegment fieldValue) {
        MemorySegment.copy(fieldValue, 0L, struct, magnetic_field$OFFSET, magnetic_field$LAYOUT.byteSize());
    }

    private static final SequenceLayout magnetic_field_covariance$LAYOUT = (SequenceLayout)$LAYOUT.select(groupElement("magnetic_field_covariance"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * double magnetic_field_covariance[9]
     * }
     */
    public static final SequenceLayout magnetic_field_covariance$layout() {
        return magnetic_field_covariance$LAYOUT;
    }

    private static final long magnetic_field_covariance$OFFSET = $LAYOUT.byteOffset(groupElement("magnetic_field_covariance"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * double magnetic_field_covariance[9]
     * }
     */
    public static final long magnetic_field_covariance$offset() {
        return magnetic_field_covariance$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * double magnetic_field_covariance[9]
     * }
     */
    public static MemorySegment magnetic_field_covariance(MemorySegment struct) {
        return struct.asSlice(magnetic_field_covariance$OFFSET, magnetic_field_covariance$LAYOUT.byteSize());
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * double magnetic_field_covariance[9]
     * }
     */
    public static void magnetic_field_covariance(MemorySegment struct, MemorySegment fieldValue) {
        MemorySegment.copy(fieldValue, 0L, struct, magnetic_field_covariance$OFFSET, magnetic_field_covariance$LAYOUT.byteSize());
    }

    private static long[] magnetic_field_covariance$DIMS = { 9 };

    /**
     * Dimensions for array field:
     * {@snippet lang=c :
     * double magnetic_field_covariance[9]
     * }
     */
    public static long[] magnetic_field_covariance$dimensions() {
        return magnetic_field_covariance$DIMS;
    }
    private static final VarHandle magnetic_field_covariance$ELEM_HANDLE = magnetic_field_covariance$LAYOUT.varHandle(sequenceElement());

    /**
     * Indexed getter for field:
     * {@snippet lang=c :
     * double magnetic_field_covariance[9]
     * }
     */
    public static double magnetic_field_covariance(MemorySegment struct, long index0) {
        return (double)magnetic_field_covariance$ELEM_HANDLE.get(struct, magnetic_field_covariance$OFFSET, index0);
    }

    /**
     * Indexed setter for field:
     * {@snippet lang=c :
     * double magnetic_field_covariance[9]
     * }
     */
    public static void magnetic_field_covariance(MemorySegment struct, long index0, double fieldValue) {
        magnetic_field_covariance$ELEM_HANDLE.set(struct, magnetic_field_covariance$OFFSET, index0, fieldValue);
    }

    /**
     * Obtains a slice of {@code arrayParam} which selects the array element at {@code index}.
     * The returned segment has address {@code arrayParam.address() + index * layout().byteSize()}
     */
    public static MemorySegment asSlice(MemorySegment array, long index) {
        return array.asSlice(layout().byteSize() * index);
    }

    /**
     * The size (in bytes) of this struct
     */
    public static long sizeof() { return layout().byteSize(); }

    /**
     * Allocate a segment of size {@code layout().byteSize()} using {@code allocator}
     */
    public static MemorySegment allocate(SegmentAllocator allocator) {
        return allocator.allocate(layout());
    }

    /**
     * Allocate an array of size {@code elementCount} using {@code allocator}.
     * The returned segment has size {@code elementCount * layout().byteSize()}.
     */
    public static MemorySegment allocateArray(long elementCount, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(elementCount, layout()));
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, Arena arena, Consumer<MemorySegment> cleanup) {
        return reinterpret(addr, 1, arena, cleanup);
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code elementCount * layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, long elementCount, Arena arena, Consumer<MemorySegment> cleanup) {
        return addr.reinterpret(layout().byteSize() * elementCount, arena, cleanup);
    }
}

