// Generated by jextract

package org.ros2.rcl.msgs;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * struct sensor_msgs__msg__BatteryState {
 *     std_msgs__msg__Header header;
 *     float voltage;
 *     float temperature;
 *     float current;
 *     float charge;
 *     float capacity;
 *     float design_capacity;
 *     float percentage;
 *     uint8_t power_supply_status;
 *     uint8_t power_supply_health;
 *     uint8_t power_supply_technology;
 *     bool present;
 *     rosidl_runtime_c__float__Sequence cell_voltage;
 *     rosidl_runtime_c__float__Sequence cell_temperature;
 *     rosidl_runtime_c__String location;
 *     rosidl_runtime_c__String serial_number;
 * }
 * }
 */
public class sensor_msgs__msg__BatteryState {

    sensor_msgs__msg__BatteryState() {
        // Should not be called directly
    }

    private static final GroupLayout $LAYOUT = MemoryLayout.structLayout(
        std_msgs__msg__Header.layout().withName("header"),
        SENSOR_MSGS_Lib.C_FLOAT.withName("voltage"),
        SENSOR_MSGS_Lib.C_FLOAT.withName("temperature"),
        SENSOR_MSGS_Lib.C_FLOAT.withName("current"),
        SENSOR_MSGS_Lib.C_FLOAT.withName("charge"),
        SENSOR_MSGS_Lib.C_FLOAT.withName("capacity"),
        SENSOR_MSGS_Lib.C_FLOAT.withName("design_capacity"),
        SENSOR_MSGS_Lib.C_FLOAT.withName("percentage"),
        SENSOR_MSGS_Lib.C_CHAR.withName("power_supply_status"),
        SENSOR_MSGS_Lib.C_CHAR.withName("power_supply_health"),
        SENSOR_MSGS_Lib.C_CHAR.withName("power_supply_technology"),
        SENSOR_MSGS_Lib.C_BOOL.withName("present"),
        rosidl_runtime_c__float__Sequence.layout().withName("cell_voltage"),
        rosidl_runtime_c__float__Sequence.layout().withName("cell_temperature"),
        rosidl_runtime_c__String.layout().withName("location"),
        rosidl_runtime_c__String.layout().withName("serial_number")
    ).withName("sensor_msgs__msg__BatteryState");

    /**
     * The layout of this struct
     */
    public static final GroupLayout layout() {
        return $LAYOUT;
    }

    private static final GroupLayout header$LAYOUT = (GroupLayout)$LAYOUT.select(groupElement("header"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * std_msgs__msg__Header header
     * }
     */
    public static final GroupLayout header$layout() {
        return header$LAYOUT;
    }

    private static final long header$OFFSET = $LAYOUT.byteOffset(groupElement("header"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * std_msgs__msg__Header header
     * }
     */
    public static final long header$offset() {
        return header$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * std_msgs__msg__Header header
     * }
     */
    public static MemorySegment header(MemorySegment struct) {
        return struct.asSlice(header$OFFSET, header$LAYOUT.byteSize());
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * std_msgs__msg__Header header
     * }
     */
    public static void header(MemorySegment struct, MemorySegment fieldValue) {
        MemorySegment.copy(fieldValue, 0L, struct, header$OFFSET, header$LAYOUT.byteSize());
    }

    private static final OfFloat voltage$LAYOUT = (OfFloat)$LAYOUT.select(groupElement("voltage"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * float voltage
     * }
     */
    public static final OfFloat voltage$layout() {
        return voltage$LAYOUT;
    }

    private static final long voltage$OFFSET = $LAYOUT.byteOffset(groupElement("voltage"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * float voltage
     * }
     */
    public static final long voltage$offset() {
        return voltage$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * float voltage
     * }
     */
    public static float voltage(MemorySegment struct) {
        return struct.get(voltage$LAYOUT, voltage$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * float voltage
     * }
     */
    public static void voltage(MemorySegment struct, float fieldValue) {
        struct.set(voltage$LAYOUT, voltage$OFFSET, fieldValue);
    }

    private static final OfFloat temperature$LAYOUT = (OfFloat)$LAYOUT.select(groupElement("temperature"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * float temperature
     * }
     */
    public static final OfFloat temperature$layout() {
        return temperature$LAYOUT;
    }

    private static final long temperature$OFFSET = $LAYOUT.byteOffset(groupElement("temperature"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * float temperature
     * }
     */
    public static final long temperature$offset() {
        return temperature$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * float temperature
     * }
     */
    public static float temperature(MemorySegment struct) {
        return struct.get(temperature$LAYOUT, temperature$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * float temperature
     * }
     */
    public static void temperature(MemorySegment struct, float fieldValue) {
        struct.set(temperature$LAYOUT, temperature$OFFSET, fieldValue);
    }

    private static final OfFloat current$LAYOUT = (OfFloat)$LAYOUT.select(groupElement("current"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * float current
     * }
     */
    public static final OfFloat current$layout() {
        return current$LAYOUT;
    }

    private static final long current$OFFSET = $LAYOUT.byteOffset(groupElement("current"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * float current
     * }
     */
    public static final long current$offset() {
        return current$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * float current
     * }
     */
    public static float current(MemorySegment struct) {
        return struct.get(current$LAYOUT, current$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * float current
     * }
     */
    public static void current(MemorySegment struct, float fieldValue) {
        struct.set(current$LAYOUT, current$OFFSET, fieldValue);
    }

    private static final OfFloat charge$LAYOUT = (OfFloat)$LAYOUT.select(groupElement("charge"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * float charge
     * }
     */
    public static final OfFloat charge$layout() {
        return charge$LAYOUT;
    }

    private static final long charge$OFFSET = $LAYOUT.byteOffset(groupElement("charge"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * float charge
     * }
     */
    public static final long charge$offset() {
        return charge$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * float charge
     * }
     */
    public static float charge(MemorySegment struct) {
        return struct.get(charge$LAYOUT, charge$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * float charge
     * }
     */
    public static void charge(MemorySegment struct, float fieldValue) {
        struct.set(charge$LAYOUT, charge$OFFSET, fieldValue);
    }

    private static final OfFloat capacity$LAYOUT = (OfFloat)$LAYOUT.select(groupElement("capacity"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * float capacity
     * }
     */
    public static final OfFloat capacity$layout() {
        return capacity$LAYOUT;
    }

    private static final long capacity$OFFSET = $LAYOUT.byteOffset(groupElement("capacity"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * float capacity
     * }
     */
    public static final long capacity$offset() {
        return capacity$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * float capacity
     * }
     */
    public static float capacity(MemorySegment struct) {
        return struct.get(capacity$LAYOUT, capacity$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * float capacity
     * }
     */
    public static void capacity(MemorySegment struct, float fieldValue) {
        struct.set(capacity$LAYOUT, capacity$OFFSET, fieldValue);
    }

    private static final OfFloat design_capacity$LAYOUT = (OfFloat)$LAYOUT.select(groupElement("design_capacity"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * float design_capacity
     * }
     */
    public static final OfFloat design_capacity$layout() {
        return design_capacity$LAYOUT;
    }

    private static final long design_capacity$OFFSET = $LAYOUT.byteOffset(groupElement("design_capacity"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * float design_capacity
     * }
     */
    public static final long design_capacity$offset() {
        return design_capacity$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * float design_capacity
     * }
     */
    public static float design_capacity(MemorySegment struct) {
        return struct.get(design_capacity$LAYOUT, design_capacity$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * float design_capacity
     * }
     */
    public static void design_capacity(MemorySegment struct, float fieldValue) {
        struct.set(design_capacity$LAYOUT, design_capacity$OFFSET, fieldValue);
    }

    private static final OfFloat percentage$LAYOUT = (OfFloat)$LAYOUT.select(groupElement("percentage"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * float percentage
     * }
     */
    public static final OfFloat percentage$layout() {
        return percentage$LAYOUT;
    }

    private static final long percentage$OFFSET = $LAYOUT.byteOffset(groupElement("percentage"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * float percentage
     * }
     */
    public static final long percentage$offset() {
        return percentage$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * float percentage
     * }
     */
    public static float percentage(MemorySegment struct) {
        return struct.get(percentage$LAYOUT, percentage$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * float percentage
     * }
     */
    public static void percentage(MemorySegment struct, float fieldValue) {
        struct.set(percentage$LAYOUT, percentage$OFFSET, fieldValue);
    }

    private static final OfByte power_supply_status$LAYOUT = (OfByte)$LAYOUT.select(groupElement("power_supply_status"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * uint8_t power_supply_status
     * }
     */
    public static final OfByte power_supply_status$layout() {
        return power_supply_status$LAYOUT;
    }

    private static final long power_supply_status$OFFSET = $LAYOUT.byteOffset(groupElement("power_supply_status"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * uint8_t power_supply_status
     * }
     */
    public static final long power_supply_status$offset() {
        return power_supply_status$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * uint8_t power_supply_status
     * }
     */
    public static byte power_supply_status(MemorySegment struct) {
        return struct.get(power_supply_status$LAYOUT, power_supply_status$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * uint8_t power_supply_status
     * }
     */
    public static void power_supply_status(MemorySegment struct, byte fieldValue) {
        struct.set(power_supply_status$LAYOUT, power_supply_status$OFFSET, fieldValue);
    }

    private static final OfByte power_supply_health$LAYOUT = (OfByte)$LAYOUT.select(groupElement("power_supply_health"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * uint8_t power_supply_health
     * }
     */
    public static final OfByte power_supply_health$layout() {
        return power_supply_health$LAYOUT;
    }

    private static final long power_supply_health$OFFSET = $LAYOUT.byteOffset(groupElement("power_supply_health"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * uint8_t power_supply_health
     * }
     */
    public static final long power_supply_health$offset() {
        return power_supply_health$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * uint8_t power_supply_health
     * }
     */
    public static byte power_supply_health(MemorySegment struct) {
        return struct.get(power_supply_health$LAYOUT, power_supply_health$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * uint8_t power_supply_health
     * }
     */
    public static void power_supply_health(MemorySegment struct, byte fieldValue) {
        struct.set(power_supply_health$LAYOUT, power_supply_health$OFFSET, fieldValue);
    }

    private static final OfByte power_supply_technology$LAYOUT = (OfByte)$LAYOUT.select(groupElement("power_supply_technology"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * uint8_t power_supply_technology
     * }
     */
    public static final OfByte power_supply_technology$layout() {
        return power_supply_technology$LAYOUT;
    }

    private static final long power_supply_technology$OFFSET = $LAYOUT.byteOffset(groupElement("power_supply_technology"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * uint8_t power_supply_technology
     * }
     */
    public static final long power_supply_technology$offset() {
        return power_supply_technology$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * uint8_t power_supply_technology
     * }
     */
    public static byte power_supply_technology(MemorySegment struct) {
        return struct.get(power_supply_technology$LAYOUT, power_supply_technology$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * uint8_t power_supply_technology
     * }
     */
    public static void power_supply_technology(MemorySegment struct, byte fieldValue) {
        struct.set(power_supply_technology$LAYOUT, power_supply_technology$OFFSET, fieldValue);
    }

    private static final OfBoolean present$LAYOUT = (OfBoolean)$LAYOUT.select(groupElement("present"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * bool present
     * }
     */
    public static final OfBoolean present$layout() {
        return present$LAYOUT;
    }

    private static final long present$OFFSET = $LAYOUT.byteOffset(groupElement("present"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * bool present
     * }
     */
    public static final long present$offset() {
        return present$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * bool present
     * }
     */
    public static boolean present(MemorySegment struct) {
        return struct.get(present$LAYOUT, present$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * bool present
     * }
     */
    public static void present(MemorySegment struct, boolean fieldValue) {
        struct.set(present$LAYOUT, present$OFFSET, fieldValue);
    }

    private static final GroupLayout cell_voltage$LAYOUT = (GroupLayout)$LAYOUT.select(groupElement("cell_voltage"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * rosidl_runtime_c__float__Sequence cell_voltage
     * }
     */
    public static final GroupLayout cell_voltage$layout() {
        return cell_voltage$LAYOUT;
    }

    private static final long cell_voltage$OFFSET = $LAYOUT.byteOffset(groupElement("cell_voltage"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * rosidl_runtime_c__float__Sequence cell_voltage
     * }
     */
    public static final long cell_voltage$offset() {
        return cell_voltage$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * rosidl_runtime_c__float__Sequence cell_voltage
     * }
     */
    public static MemorySegment cell_voltage(MemorySegment struct) {
        return struct.asSlice(cell_voltage$OFFSET, cell_voltage$LAYOUT.byteSize());
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * rosidl_runtime_c__float__Sequence cell_voltage
     * }
     */
    public static void cell_voltage(MemorySegment struct, MemorySegment fieldValue) {
        MemorySegment.copy(fieldValue, 0L, struct, cell_voltage$OFFSET, cell_voltage$LAYOUT.byteSize());
    }

    private static final GroupLayout cell_temperature$LAYOUT = (GroupLayout)$LAYOUT.select(groupElement("cell_temperature"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * rosidl_runtime_c__float__Sequence cell_temperature
     * }
     */
    public static final GroupLayout cell_temperature$layout() {
        return cell_temperature$LAYOUT;
    }

    private static final long cell_temperature$OFFSET = $LAYOUT.byteOffset(groupElement("cell_temperature"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * rosidl_runtime_c__float__Sequence cell_temperature
     * }
     */
    public static final long cell_temperature$offset() {
        return cell_temperature$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * rosidl_runtime_c__float__Sequence cell_temperature
     * }
     */
    public static MemorySegment cell_temperature(MemorySegment struct) {
        return struct.asSlice(cell_temperature$OFFSET, cell_temperature$LAYOUT.byteSize());
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * rosidl_runtime_c__float__Sequence cell_temperature
     * }
     */
    public static void cell_temperature(MemorySegment struct, MemorySegment fieldValue) {
        MemorySegment.copy(fieldValue, 0L, struct, cell_temperature$OFFSET, cell_temperature$LAYOUT.byteSize());
    }

    private static final GroupLayout location$LAYOUT = (GroupLayout)$LAYOUT.select(groupElement("location"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * rosidl_runtime_c__String location
     * }
     */
    public static final GroupLayout location$layout() {
        return location$LAYOUT;
    }

    private static final long location$OFFSET = $LAYOUT.byteOffset(groupElement("location"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * rosidl_runtime_c__String location
     * }
     */
    public static final long location$offset() {
        return location$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * rosidl_runtime_c__String location
     * }
     */
    public static MemorySegment location(MemorySegment struct) {
        return struct.asSlice(location$OFFSET, location$LAYOUT.byteSize());
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * rosidl_runtime_c__String location
     * }
     */
    public static void location(MemorySegment struct, MemorySegment fieldValue) {
        MemorySegment.copy(fieldValue, 0L, struct, location$OFFSET, location$LAYOUT.byteSize());
    }

    private static final GroupLayout serial_number$LAYOUT = (GroupLayout)$LAYOUT.select(groupElement("serial_number"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * rosidl_runtime_c__String serial_number
     * }
     */
    public static final GroupLayout serial_number$layout() {
        return serial_number$LAYOUT;
    }

    private static final long serial_number$OFFSET = $LAYOUT.byteOffset(groupElement("serial_number"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * rosidl_runtime_c__String serial_number
     * }
     */
    public static final long serial_number$offset() {
        return serial_number$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * rosidl_runtime_c__String serial_number
     * }
     */
    public static MemorySegment serial_number(MemorySegment struct) {
        return struct.asSlice(serial_number$OFFSET, serial_number$LAYOUT.byteSize());
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * rosidl_runtime_c__String serial_number
     * }
     */
    public static void serial_number(MemorySegment struct, MemorySegment fieldValue) {
        MemorySegment.copy(fieldValue, 0L, struct, serial_number$OFFSET, serial_number$LAYOUT.byteSize());
    }

    /**
     * Obtains a slice of {@code arrayParam} which selects the array element at {@code index}.
     * The returned segment has address {@code arrayParam.address() + index * layout().byteSize()}
     */
    public static MemorySegment asSlice(MemorySegment array, long index) {
        return array.asSlice(layout().byteSize() * index);
    }

    /**
     * The size (in bytes) of this struct
     */
    public static long sizeof() { return layout().byteSize(); }

    /**
     * Allocate a segment of size {@code layout().byteSize()} using {@code allocator}
     */
    public static MemorySegment allocate(SegmentAllocator allocator) {
        return allocator.allocate(layout());
    }

    /**
     * Allocate an array of size {@code elementCount} using {@code allocator}.
     * The returned segment has size {@code elementCount * layout().byteSize()}.
     */
    public static MemorySegment allocateArray(long elementCount, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(elementCount, layout()));
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, Arena arena, Consumer<MemorySegment> cleanup) {
        return reinterpret(addr, 1, arena, cleanup);
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code elementCount * layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, long elementCount, Arena arena, Consumer<MemorySegment> cleanup) {
        return addr.reinterpret(layout().byteSize() * elementCount, arena, cleanup);
    }
}

