// Generated by jextract

package org.ros2.rcl.msgs;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * struct sensor_msgs__srv__SetCameraInfo_Request {
 *     sensor_msgs__msg__CameraInfo camera_info;
 * }
 * }
 */
public class sensor_msgs__srv__SetCameraInfo_Request {

    sensor_msgs__srv__SetCameraInfo_Request() {
        // Should not be called directly
    }

    private static final GroupLayout $LAYOUT = MemoryLayout.structLayout(
        sensor_msgs__msg__CameraInfo.layout().withName("camera_info")
    ).withName("sensor_msgs__srv__SetCameraInfo_Request");

    /**
     * The layout of this struct
     */
    public static final GroupLayout layout() {
        return $LAYOUT;
    }

    private static final GroupLayout camera_info$LAYOUT = (GroupLayout)$LAYOUT.select(groupElement("camera_info"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * sensor_msgs__msg__CameraInfo camera_info
     * }
     */
    public static final GroupLayout camera_info$layout() {
        return camera_info$LAYOUT;
    }

    private static final long camera_info$OFFSET = $LAYOUT.byteOffset(groupElement("camera_info"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * sensor_msgs__msg__CameraInfo camera_info
     * }
     */
    public static final long camera_info$offset() {
        return camera_info$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * sensor_msgs__msg__CameraInfo camera_info
     * }
     */
    public static MemorySegment camera_info(MemorySegment struct) {
        return struct.asSlice(camera_info$OFFSET, camera_info$LAYOUT.byteSize());
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * sensor_msgs__msg__CameraInfo camera_info
     * }
     */
    public static void camera_info(MemorySegment struct, MemorySegment fieldValue) {
        MemorySegment.copy(fieldValue, 0L, struct, camera_info$OFFSET, camera_info$LAYOUT.byteSize());
    }

    /**
     * Obtains a slice of {@code arrayParam} which selects the array element at {@code index}.
     * The returned segment has address {@code arrayParam.address() + index * layout().byteSize()}
     */
    public static MemorySegment asSlice(MemorySegment array, long index) {
        return array.asSlice(layout().byteSize() * index);
    }

    /**
     * The size (in bytes) of this struct
     */
    public static long sizeof() { return layout().byteSize(); }

    /**
     * Allocate a segment of size {@code layout().byteSize()} using {@code allocator}
     */
    public static MemorySegment allocate(SegmentAllocator allocator) {
        return allocator.allocate(layout());
    }

    /**
     * Allocate an array of size {@code elementCount} using {@code allocator}.
     * The returned segment has size {@code elementCount * layout().byteSize()}.
     */
    public static MemorySegment allocateArray(long elementCount, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(elementCount, layout()));
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, Arena arena, Consumer<MemorySegment> cleanup) {
        return reinterpret(addr, 1, arena, cleanup);
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code elementCount * layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, long elementCount, Arena arena, Consumer<MemorySegment> cleanup) {
        return addr.reinterpret(layout().byteSize() * elementCount, arena, cleanup);
    }
}

