// Generated by jextract

package org.ros2.rcl.msgs;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * struct sensor_msgs__msg__CameraInfo {
 *     std_msgs__msg__Header header;
 *     uint32_t height;
 *     uint32_t width;
 *     rosidl_runtime_c__String distortion_model;
 *     rosidl_runtime_c__double__Sequence d;
 *     double k[9];
 *     double r[9];
 *     double p[12];
 *     uint32_t binning_x;
 *     uint32_t binning_y;
 *     sensor_msgs__msg__RegionOfInterest roi;
 * }
 * }
 */
public class sensor_msgs__msg__CameraInfo {

    sensor_msgs__msg__CameraInfo() {
        // Should not be called directly
    }

    private static final GroupLayout $LAYOUT = MemoryLayout.structLayout(
        std_msgs__msg__Header.layout().withName("header"),
        SENSOR_MSGS_Lib.C_INT.withName("height"),
        SENSOR_MSGS_Lib.C_INT.withName("width"),
        rosidl_runtime_c__String.layout().withName("distortion_model"),
        rosidl_runtime_c__double__Sequence.layout().withName("d"),
        MemoryLayout.sequenceLayout(9, SENSOR_MSGS_Lib.C_DOUBLE).withName("k"),
        MemoryLayout.sequenceLayout(9, SENSOR_MSGS_Lib.C_DOUBLE).withName("r"),
        MemoryLayout.sequenceLayout(12, SENSOR_MSGS_Lib.C_DOUBLE).withName("p"),
        SENSOR_MSGS_Lib.C_INT.withName("binning_x"),
        SENSOR_MSGS_Lib.C_INT.withName("binning_y"),
        sensor_msgs__msg__RegionOfInterest.layout().withName("roi"),
        MemoryLayout.paddingLayout(4)
    ).withName("sensor_msgs__msg__CameraInfo");

    /**
     * The layout of this struct
     */
    public static final GroupLayout layout() {
        return $LAYOUT;
    }

    private static final GroupLayout header$LAYOUT = (GroupLayout)$LAYOUT.select(groupElement("header"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * std_msgs__msg__Header header
     * }
     */
    public static final GroupLayout header$layout() {
        return header$LAYOUT;
    }

    private static final long header$OFFSET = $LAYOUT.byteOffset(groupElement("header"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * std_msgs__msg__Header header
     * }
     */
    public static final long header$offset() {
        return header$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * std_msgs__msg__Header header
     * }
     */
    public static MemorySegment header(MemorySegment struct) {
        return struct.asSlice(header$OFFSET, header$LAYOUT.byteSize());
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * std_msgs__msg__Header header
     * }
     */
    public static void header(MemorySegment struct, MemorySegment fieldValue) {
        MemorySegment.copy(fieldValue, 0L, struct, header$OFFSET, header$LAYOUT.byteSize());
    }

    private static final OfInt height$LAYOUT = (OfInt)$LAYOUT.select(groupElement("height"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * uint32_t height
     * }
     */
    public static final OfInt height$layout() {
        return height$LAYOUT;
    }

    private static final long height$OFFSET = $LAYOUT.byteOffset(groupElement("height"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * uint32_t height
     * }
     */
    public static final long height$offset() {
        return height$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * uint32_t height
     * }
     */
    public static int height(MemorySegment struct) {
        return struct.get(height$LAYOUT, height$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * uint32_t height
     * }
     */
    public static void height(MemorySegment struct, int fieldValue) {
        struct.set(height$LAYOUT, height$OFFSET, fieldValue);
    }

    private static final OfInt width$LAYOUT = (OfInt)$LAYOUT.select(groupElement("width"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * uint32_t width
     * }
     */
    public static final OfInt width$layout() {
        return width$LAYOUT;
    }

    private static final long width$OFFSET = $LAYOUT.byteOffset(groupElement("width"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * uint32_t width
     * }
     */
    public static final long width$offset() {
        return width$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * uint32_t width
     * }
     */
    public static int width(MemorySegment struct) {
        return struct.get(width$LAYOUT, width$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * uint32_t width
     * }
     */
    public static void width(MemorySegment struct, int fieldValue) {
        struct.set(width$LAYOUT, width$OFFSET, fieldValue);
    }

    private static final GroupLayout distortion_model$LAYOUT = (GroupLayout)$LAYOUT.select(groupElement("distortion_model"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * rosidl_runtime_c__String distortion_model
     * }
     */
    public static final GroupLayout distortion_model$layout() {
        return distortion_model$LAYOUT;
    }

    private static final long distortion_model$OFFSET = $LAYOUT.byteOffset(groupElement("distortion_model"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * rosidl_runtime_c__String distortion_model
     * }
     */
    public static final long distortion_model$offset() {
        return distortion_model$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * rosidl_runtime_c__String distortion_model
     * }
     */
    public static MemorySegment distortion_model(MemorySegment struct) {
        return struct.asSlice(distortion_model$OFFSET, distortion_model$LAYOUT.byteSize());
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * rosidl_runtime_c__String distortion_model
     * }
     */
    public static void distortion_model(MemorySegment struct, MemorySegment fieldValue) {
        MemorySegment.copy(fieldValue, 0L, struct, distortion_model$OFFSET, distortion_model$LAYOUT.byteSize());
    }

    private static final GroupLayout d$LAYOUT = (GroupLayout)$LAYOUT.select(groupElement("d"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * rosidl_runtime_c__double__Sequence d
     * }
     */
    public static final GroupLayout d$layout() {
        return d$LAYOUT;
    }

    private static final long d$OFFSET = $LAYOUT.byteOffset(groupElement("d"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * rosidl_runtime_c__double__Sequence d
     * }
     */
    public static final long d$offset() {
        return d$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * rosidl_runtime_c__double__Sequence d
     * }
     */
    public static MemorySegment d(MemorySegment struct) {
        return struct.asSlice(d$OFFSET, d$LAYOUT.byteSize());
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * rosidl_runtime_c__double__Sequence d
     * }
     */
    public static void d(MemorySegment struct, MemorySegment fieldValue) {
        MemorySegment.copy(fieldValue, 0L, struct, d$OFFSET, d$LAYOUT.byteSize());
    }

    private static final SequenceLayout k$LAYOUT = (SequenceLayout)$LAYOUT.select(groupElement("k"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * double k[9]
     * }
     */
    public static final SequenceLayout k$layout() {
        return k$LAYOUT;
    }

    private static final long k$OFFSET = $LAYOUT.byteOffset(groupElement("k"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * double k[9]
     * }
     */
    public static final long k$offset() {
        return k$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * double k[9]
     * }
     */
    public static MemorySegment k(MemorySegment struct) {
        return struct.asSlice(k$OFFSET, k$LAYOUT.byteSize());
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * double k[9]
     * }
     */
    public static void k(MemorySegment struct, MemorySegment fieldValue) {
        MemorySegment.copy(fieldValue, 0L, struct, k$OFFSET, k$LAYOUT.byteSize());
    }

    private static long[] k$DIMS = { 9 };

    /**
     * Dimensions for array field:
     * {@snippet lang=c :
     * double k[9]
     * }
     */
    public static long[] k$dimensions() {
        return k$DIMS;
    }
    private static final VarHandle k$ELEM_HANDLE = k$LAYOUT.varHandle(sequenceElement());

    /**
     * Indexed getter for field:
     * {@snippet lang=c :
     * double k[9]
     * }
     */
    public static double k(MemorySegment struct, long index0) {
        return (double)k$ELEM_HANDLE.get(struct, k$OFFSET, index0);
    }

    /**
     * Indexed setter for field:
     * {@snippet lang=c :
     * double k[9]
     * }
     */
    public static void k(MemorySegment struct, long index0, double fieldValue) {
        k$ELEM_HANDLE.set(struct, k$OFFSET, index0, fieldValue);
    }

    private static final SequenceLayout r$LAYOUT = (SequenceLayout)$LAYOUT.select(groupElement("r"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * double r[9]
     * }
     */
    public static final SequenceLayout r$layout() {
        return r$LAYOUT;
    }

    private static final long r$OFFSET = $LAYOUT.byteOffset(groupElement("r"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * double r[9]
     * }
     */
    public static final long r$offset() {
        return r$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * double r[9]
     * }
     */
    public static MemorySegment r(MemorySegment struct) {
        return struct.asSlice(r$OFFSET, r$LAYOUT.byteSize());
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * double r[9]
     * }
     */
    public static void r(MemorySegment struct, MemorySegment fieldValue) {
        MemorySegment.copy(fieldValue, 0L, struct, r$OFFSET, r$LAYOUT.byteSize());
    }

    private static long[] r$DIMS = { 9 };

    /**
     * Dimensions for array field:
     * {@snippet lang=c :
     * double r[9]
     * }
     */
    public static long[] r$dimensions() {
        return r$DIMS;
    }
    private static final VarHandle r$ELEM_HANDLE = r$LAYOUT.varHandle(sequenceElement());

    /**
     * Indexed getter for field:
     * {@snippet lang=c :
     * double r[9]
     * }
     */
    public static double r(MemorySegment struct, long index0) {
        return (double)r$ELEM_HANDLE.get(struct, r$OFFSET, index0);
    }

    /**
     * Indexed setter for field:
     * {@snippet lang=c :
     * double r[9]
     * }
     */
    public static void r(MemorySegment struct, long index0, double fieldValue) {
        r$ELEM_HANDLE.set(struct, r$OFFSET, index0, fieldValue);
    }

    private static final SequenceLayout p$LAYOUT = (SequenceLayout)$LAYOUT.select(groupElement("p"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * double p[12]
     * }
     */
    public static final SequenceLayout p$layout() {
        return p$LAYOUT;
    }

    private static final long p$OFFSET = $LAYOUT.byteOffset(groupElement("p"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * double p[12]
     * }
     */
    public static final long p$offset() {
        return p$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * double p[12]
     * }
     */
    public static MemorySegment p(MemorySegment struct) {
        return struct.asSlice(p$OFFSET, p$LAYOUT.byteSize());
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * double p[12]
     * }
     */
    public static void p(MemorySegment struct, MemorySegment fieldValue) {
        MemorySegment.copy(fieldValue, 0L, struct, p$OFFSET, p$LAYOUT.byteSize());
    }

    private static long[] p$DIMS = { 12 };

    /**
     * Dimensions for array field:
     * {@snippet lang=c :
     * double p[12]
     * }
     */
    public static long[] p$dimensions() {
        return p$DIMS;
    }
    private static final VarHandle p$ELEM_HANDLE = p$LAYOUT.varHandle(sequenceElement());

    /**
     * Indexed getter for field:
     * {@snippet lang=c :
     * double p[12]
     * }
     */
    public static double p(MemorySegment struct, long index0) {
        return (double)p$ELEM_HANDLE.get(struct, p$OFFSET, index0);
    }

    /**
     * Indexed setter for field:
     * {@snippet lang=c :
     * double p[12]
     * }
     */
    public static void p(MemorySegment struct, long index0, double fieldValue) {
        p$ELEM_HANDLE.set(struct, p$OFFSET, index0, fieldValue);
    }

    private static final OfInt binning_x$LAYOUT = (OfInt)$LAYOUT.select(groupElement("binning_x"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * uint32_t binning_x
     * }
     */
    public static final OfInt binning_x$layout() {
        return binning_x$LAYOUT;
    }

    private static final long binning_x$OFFSET = $LAYOUT.byteOffset(groupElement("binning_x"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * uint32_t binning_x
     * }
     */
    public static final long binning_x$offset() {
        return binning_x$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * uint32_t binning_x
     * }
     */
    public static int binning_x(MemorySegment struct) {
        return struct.get(binning_x$LAYOUT, binning_x$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * uint32_t binning_x
     * }
     */
    public static void binning_x(MemorySegment struct, int fieldValue) {
        struct.set(binning_x$LAYOUT, binning_x$OFFSET, fieldValue);
    }

    private static final OfInt binning_y$LAYOUT = (OfInt)$LAYOUT.select(groupElement("binning_y"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * uint32_t binning_y
     * }
     */
    public static final OfInt binning_y$layout() {
        return binning_y$LAYOUT;
    }

    private static final long binning_y$OFFSET = $LAYOUT.byteOffset(groupElement("binning_y"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * uint32_t binning_y
     * }
     */
    public static final long binning_y$offset() {
        return binning_y$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * uint32_t binning_y
     * }
     */
    public static int binning_y(MemorySegment struct) {
        return struct.get(binning_y$LAYOUT, binning_y$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * uint32_t binning_y
     * }
     */
    public static void binning_y(MemorySegment struct, int fieldValue) {
        struct.set(binning_y$LAYOUT, binning_y$OFFSET, fieldValue);
    }

    private static final GroupLayout roi$LAYOUT = (GroupLayout)$LAYOUT.select(groupElement("roi"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * sensor_msgs__msg__RegionOfInterest roi
     * }
     */
    public static final GroupLayout roi$layout() {
        return roi$LAYOUT;
    }

    private static final long roi$OFFSET = $LAYOUT.byteOffset(groupElement("roi"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * sensor_msgs__msg__RegionOfInterest roi
     * }
     */
    public static final long roi$offset() {
        return roi$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * sensor_msgs__msg__RegionOfInterest roi
     * }
     */
    public static MemorySegment roi(MemorySegment struct) {
        return struct.asSlice(roi$OFFSET, roi$LAYOUT.byteSize());
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * sensor_msgs__msg__RegionOfInterest roi
     * }
     */
    public static void roi(MemorySegment struct, MemorySegment fieldValue) {
        MemorySegment.copy(fieldValue, 0L, struct, roi$OFFSET, roi$LAYOUT.byteSize());
    }

    /**
     * Obtains a slice of {@code arrayParam} which selects the array element at {@code index}.
     * The returned segment has address {@code arrayParam.address() + index * layout().byteSize()}
     */
    public static MemorySegment asSlice(MemorySegment array, long index) {
        return array.asSlice(layout().byteSize() * index);
    }

    /**
     * The size (in bytes) of this struct
     */
    public static long sizeof() { return layout().byteSize(); }

    /**
     * Allocate a segment of size {@code layout().byteSize()} using {@code allocator}
     */
    public static MemorySegment allocate(SegmentAllocator allocator) {
        return allocator.allocate(layout());
    }

    /**
     * Allocate an array of size {@code elementCount} using {@code allocator}.
     * The returned segment has size {@code elementCount * layout().byteSize()}.
     */
    public static MemorySegment allocateArray(long elementCount, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(elementCount, layout()));
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, Arena arena, Consumer<MemorySegment> cleanup) {
        return reinterpret(addr, 1, arena, cleanup);
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code elementCount * layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, long elementCount, Arena arena, Consumer<MemorySegment> cleanup) {
        return addr.reinterpret(layout().byteSize() * elementCount, arena, cleanup);
    }
}

