// Generated by jextract

package org.ros2.rcl.msgs;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * struct sensor_msgs__msg__Joy {
 *     std_msgs__msg__Header header;
 *     rosidl_runtime_c__float__Sequence axes;
 *     rosidl_runtime_c__int32__Sequence buttons;
 * }
 * }
 */
public class sensor_msgs__msg__Joy {

    sensor_msgs__msg__Joy() {
        // Should not be called directly
    }

    private static final GroupLayout $LAYOUT = MemoryLayout.structLayout(
        std_msgs__msg__Header.layout().withName("header"),
        rosidl_runtime_c__float__Sequence.layout().withName("axes"),
        rosidl_runtime_c__int32__Sequence.layout().withName("buttons")
    ).withName("sensor_msgs__msg__Joy");

    /**
     * The layout of this struct
     */
    public static final GroupLayout layout() {
        return $LAYOUT;
    }

    private static final GroupLayout header$LAYOUT = (GroupLayout)$LAYOUT.select(groupElement("header"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * std_msgs__msg__Header header
     * }
     */
    public static final GroupLayout header$layout() {
        return header$LAYOUT;
    }

    private static final long header$OFFSET = $LAYOUT.byteOffset(groupElement("header"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * std_msgs__msg__Header header
     * }
     */
    public static final long header$offset() {
        return header$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * std_msgs__msg__Header header
     * }
     */
    public static MemorySegment header(MemorySegment struct) {
        return struct.asSlice(header$OFFSET, header$LAYOUT.byteSize());
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * std_msgs__msg__Header header
     * }
     */
    public static void header(MemorySegment struct, MemorySegment fieldValue) {
        MemorySegment.copy(fieldValue, 0L, struct, header$OFFSET, header$LAYOUT.byteSize());
    }

    private static final GroupLayout axes$LAYOUT = (GroupLayout)$LAYOUT.select(groupElement("axes"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * rosidl_runtime_c__float__Sequence axes
     * }
     */
    public static final GroupLayout axes$layout() {
        return axes$LAYOUT;
    }

    private static final long axes$OFFSET = $LAYOUT.byteOffset(groupElement("axes"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * rosidl_runtime_c__float__Sequence axes
     * }
     */
    public static final long axes$offset() {
        return axes$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * rosidl_runtime_c__float__Sequence axes
     * }
     */
    public static MemorySegment axes(MemorySegment struct) {
        return struct.asSlice(axes$OFFSET, axes$LAYOUT.byteSize());
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * rosidl_runtime_c__float__Sequence axes
     * }
     */
    public static void axes(MemorySegment struct, MemorySegment fieldValue) {
        MemorySegment.copy(fieldValue, 0L, struct, axes$OFFSET, axes$LAYOUT.byteSize());
    }

    private static final GroupLayout buttons$LAYOUT = (GroupLayout)$LAYOUT.select(groupElement("buttons"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * rosidl_runtime_c__int32__Sequence buttons
     * }
     */
    public static final GroupLayout buttons$layout() {
        return buttons$LAYOUT;
    }

    private static final long buttons$OFFSET = $LAYOUT.byteOffset(groupElement("buttons"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * rosidl_runtime_c__int32__Sequence buttons
     * }
     */
    public static final long buttons$offset() {
        return buttons$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * rosidl_runtime_c__int32__Sequence buttons
     * }
     */
    public static MemorySegment buttons(MemorySegment struct) {
        return struct.asSlice(buttons$OFFSET, buttons$LAYOUT.byteSize());
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * rosidl_runtime_c__int32__Sequence buttons
     * }
     */
    public static void buttons(MemorySegment struct, MemorySegment fieldValue) {
        MemorySegment.copy(fieldValue, 0L, struct, buttons$OFFSET, buttons$LAYOUT.byteSize());
    }

    /**
     * Obtains a slice of {@code arrayParam} which selects the array element at {@code index}.
     * The returned segment has address {@code arrayParam.address() + index * layout().byteSize()}
     */
    public static MemorySegment asSlice(MemorySegment array, long index) {
        return array.asSlice(layout().byteSize() * index);
    }

    /**
     * The size (in bytes) of this struct
     */
    public static long sizeof() { return layout().byteSize(); }

    /**
     * Allocate a segment of size {@code layout().byteSize()} using {@code allocator}
     */
    public static MemorySegment allocate(SegmentAllocator allocator) {
        return allocator.allocate(layout());
    }

    /**
     * Allocate an array of size {@code elementCount} using {@code allocator}.
     * The returned segment has size {@code elementCount * layout().byteSize()}.
     */
    public static MemorySegment allocateArray(long elementCount, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(elementCount, layout()));
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, Arena arena, Consumer<MemorySegment> cleanup) {
        return reinterpret(addr, 1, arena, cleanup);
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code elementCount * layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, long elementCount, Arena arena, Consumer<MemorySegment> cleanup) {
        return addr.reinterpret(layout().byteSize() * elementCount, arena, cleanup);
    }
}

