// Generated by jextract

package org.ros2.rcl.msgs;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * struct sensor_msgs__msg__NavSatFix {
 *     std_msgs__msg__Header header;
 *     sensor_msgs__msg__NavSatStatus status;
 *     double latitude;
 *     double longitude;
 *     double altitude;
 *     double position_covariance[9];
 *     uint8_t position_covariance_type;
 * }
 * }
 */
public class sensor_msgs__msg__NavSatFix {

    sensor_msgs__msg__NavSatFix() {
        // Should not be called directly
    }

    private static final GroupLayout $LAYOUT = MemoryLayout.structLayout(
        std_msgs__msg__Header.layout().withName("header"),
        sensor_msgs__msg__NavSatStatus.layout().withName("status"),
        MemoryLayout.paddingLayout(4),
        SENSOR_MSGS_Lib.C_DOUBLE.withName("latitude"),
        SENSOR_MSGS_Lib.C_DOUBLE.withName("longitude"),
        SENSOR_MSGS_Lib.C_DOUBLE.withName("altitude"),
        MemoryLayout.sequenceLayout(9, SENSOR_MSGS_Lib.C_DOUBLE).withName("position_covariance"),
        SENSOR_MSGS_Lib.C_CHAR.withName("position_covariance_type"),
        MemoryLayout.paddingLayout(7)
    ).withName("sensor_msgs__msg__NavSatFix");

    /**
     * The layout of this struct
     */
    public static final GroupLayout layout() {
        return $LAYOUT;
    }

    private static final GroupLayout header$LAYOUT = (GroupLayout)$LAYOUT.select(groupElement("header"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * std_msgs__msg__Header header
     * }
     */
    public static final GroupLayout header$layout() {
        return header$LAYOUT;
    }

    private static final long header$OFFSET = $LAYOUT.byteOffset(groupElement("header"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * std_msgs__msg__Header header
     * }
     */
    public static final long header$offset() {
        return header$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * std_msgs__msg__Header header
     * }
     */
    public static MemorySegment header(MemorySegment struct) {
        return struct.asSlice(header$OFFSET, header$LAYOUT.byteSize());
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * std_msgs__msg__Header header
     * }
     */
    public static void header(MemorySegment struct, MemorySegment fieldValue) {
        MemorySegment.copy(fieldValue, 0L, struct, header$OFFSET, header$LAYOUT.byteSize());
    }

    private static final GroupLayout status$LAYOUT = (GroupLayout)$LAYOUT.select(groupElement("status"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * sensor_msgs__msg__NavSatStatus status
     * }
     */
    public static final GroupLayout status$layout() {
        return status$LAYOUT;
    }

    private static final long status$OFFSET = $LAYOUT.byteOffset(groupElement("status"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * sensor_msgs__msg__NavSatStatus status
     * }
     */
    public static final long status$offset() {
        return status$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * sensor_msgs__msg__NavSatStatus status
     * }
     */
    public static MemorySegment status(MemorySegment struct) {
        return struct.asSlice(status$OFFSET, status$LAYOUT.byteSize());
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * sensor_msgs__msg__NavSatStatus status
     * }
     */
    public static void status(MemorySegment struct, MemorySegment fieldValue) {
        MemorySegment.copy(fieldValue, 0L, struct, status$OFFSET, status$LAYOUT.byteSize());
    }

    private static final OfDouble latitude$LAYOUT = (OfDouble)$LAYOUT.select(groupElement("latitude"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * double latitude
     * }
     */
    public static final OfDouble latitude$layout() {
        return latitude$LAYOUT;
    }

    private static final long latitude$OFFSET = $LAYOUT.byteOffset(groupElement("latitude"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * double latitude
     * }
     */
    public static final long latitude$offset() {
        return latitude$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * double latitude
     * }
     */
    public static double latitude(MemorySegment struct) {
        return struct.get(latitude$LAYOUT, latitude$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * double latitude
     * }
     */
    public static void latitude(MemorySegment struct, double fieldValue) {
        struct.set(latitude$LAYOUT, latitude$OFFSET, fieldValue);
    }

    private static final OfDouble longitude$LAYOUT = (OfDouble)$LAYOUT.select(groupElement("longitude"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * double longitude
     * }
     */
    public static final OfDouble longitude$layout() {
        return longitude$LAYOUT;
    }

    private static final long longitude$OFFSET = $LAYOUT.byteOffset(groupElement("longitude"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * double longitude
     * }
     */
    public static final long longitude$offset() {
        return longitude$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * double longitude
     * }
     */
    public static double longitude(MemorySegment struct) {
        return struct.get(longitude$LAYOUT, longitude$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * double longitude
     * }
     */
    public static void longitude(MemorySegment struct, double fieldValue) {
        struct.set(longitude$LAYOUT, longitude$OFFSET, fieldValue);
    }

    private static final OfDouble altitude$LAYOUT = (OfDouble)$LAYOUT.select(groupElement("altitude"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * double altitude
     * }
     */
    public static final OfDouble altitude$layout() {
        return altitude$LAYOUT;
    }

    private static final long altitude$OFFSET = $LAYOUT.byteOffset(groupElement("altitude"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * double altitude
     * }
     */
    public static final long altitude$offset() {
        return altitude$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * double altitude
     * }
     */
    public static double altitude(MemorySegment struct) {
        return struct.get(altitude$LAYOUT, altitude$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * double altitude
     * }
     */
    public static void altitude(MemorySegment struct, double fieldValue) {
        struct.set(altitude$LAYOUT, altitude$OFFSET, fieldValue);
    }

    private static final SequenceLayout position_covariance$LAYOUT = (SequenceLayout)$LAYOUT.select(groupElement("position_covariance"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * double position_covariance[9]
     * }
     */
    public static final SequenceLayout position_covariance$layout() {
        return position_covariance$LAYOUT;
    }

    private static final long position_covariance$OFFSET = $LAYOUT.byteOffset(groupElement("position_covariance"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * double position_covariance[9]
     * }
     */
    public static final long position_covariance$offset() {
        return position_covariance$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * double position_covariance[9]
     * }
     */
    public static MemorySegment position_covariance(MemorySegment struct) {
        return struct.asSlice(position_covariance$OFFSET, position_covariance$LAYOUT.byteSize());
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * double position_covariance[9]
     * }
     */
    public static void position_covariance(MemorySegment struct, MemorySegment fieldValue) {
        MemorySegment.copy(fieldValue, 0L, struct, position_covariance$OFFSET, position_covariance$LAYOUT.byteSize());
    }

    private static long[] position_covariance$DIMS = { 9 };

    /**
     * Dimensions for array field:
     * {@snippet lang=c :
     * double position_covariance[9]
     * }
     */
    public static long[] position_covariance$dimensions() {
        return position_covariance$DIMS;
    }
    private static final VarHandle position_covariance$ELEM_HANDLE = position_covariance$LAYOUT.varHandle(sequenceElement());

    /**
     * Indexed getter for field:
     * {@snippet lang=c :
     * double position_covariance[9]
     * }
     */
    public static double position_covariance(MemorySegment struct, long index0) {
        return (double)position_covariance$ELEM_HANDLE.get(struct, position_covariance$OFFSET, index0);
    }

    /**
     * Indexed setter for field:
     * {@snippet lang=c :
     * double position_covariance[9]
     * }
     */
    public static void position_covariance(MemorySegment struct, long index0, double fieldValue) {
        position_covariance$ELEM_HANDLE.set(struct, position_covariance$OFFSET, index0, fieldValue);
    }

    private static final OfByte position_covariance_type$LAYOUT = (OfByte)$LAYOUT.select(groupElement("position_covariance_type"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * uint8_t position_covariance_type
     * }
     */
    public static final OfByte position_covariance_type$layout() {
        return position_covariance_type$LAYOUT;
    }

    private static final long position_covariance_type$OFFSET = $LAYOUT.byteOffset(groupElement("position_covariance_type"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * uint8_t position_covariance_type
     * }
     */
    public static final long position_covariance_type$offset() {
        return position_covariance_type$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * uint8_t position_covariance_type
     * }
     */
    public static byte position_covariance_type(MemorySegment struct) {
        return struct.get(position_covariance_type$LAYOUT, position_covariance_type$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * uint8_t position_covariance_type
     * }
     */
    public static void position_covariance_type(MemorySegment struct, byte fieldValue) {
        struct.set(position_covariance_type$LAYOUT, position_covariance_type$OFFSET, fieldValue);
    }

    /**
     * Obtains a slice of {@code arrayParam} which selects the array element at {@code index}.
     * The returned segment has address {@code arrayParam.address() + index * layout().byteSize()}
     */
    public static MemorySegment asSlice(MemorySegment array, long index) {
        return array.asSlice(layout().byteSize() * index);
    }

    /**
     * The size (in bytes) of this struct
     */
    public static long sizeof() { return layout().byteSize(); }

    /**
     * Allocate a segment of size {@code layout().byteSize()} using {@code allocator}
     */
    public static MemorySegment allocate(SegmentAllocator allocator) {
        return allocator.allocate(layout());
    }

    /**
     * Allocate an array of size {@code elementCount} using {@code allocator}.
     * The returned segment has size {@code elementCount * layout().byteSize()}.
     */
    public static MemorySegment allocateArray(long elementCount, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(elementCount, layout()));
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, Arena arena, Consumer<MemorySegment> cleanup) {
        return reinterpret(addr, 1, arena, cleanup);
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code elementCount * layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, long elementCount, Arena arena, Consumer<MemorySegment> cleanup) {
        return addr.reinterpret(layout().byteSize() * elementCount, arena, cleanup);
    }
}

