// Generated by jextract

package org.ros2.rcl.msgs;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * struct sensor_msgs__msg__Range {
 *     std_msgs__msg__Header header;
 *     uint8_t radiation_type;
 *     float field_of_view;
 *     float min_range;
 *     float max_range;
 *     float range;
 *     float variance;
 * }
 * }
 */
public class sensor_msgs__msg__Range {

    sensor_msgs__msg__Range() {
        // Should not be called directly
    }

    private static final GroupLayout $LAYOUT = MemoryLayout.structLayout(
        std_msgs__msg__Header.layout().withName("header"),
        SENSOR_MSGS_Lib.C_CHAR.withName("radiation_type"),
        MemoryLayout.paddingLayout(3),
        SENSOR_MSGS_Lib.C_FLOAT.withName("field_of_view"),
        SENSOR_MSGS_Lib.C_FLOAT.withName("min_range"),
        SENSOR_MSGS_Lib.C_FLOAT.withName("max_range"),
        SENSOR_MSGS_Lib.C_FLOAT.withName("range"),
        SENSOR_MSGS_Lib.C_FLOAT.withName("variance")
    ).withName("sensor_msgs__msg__Range");

    /**
     * The layout of this struct
     */
    public static final GroupLayout layout() {
        return $LAYOUT;
    }

    private static final GroupLayout header$LAYOUT = (GroupLayout)$LAYOUT.select(groupElement("header"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * std_msgs__msg__Header header
     * }
     */
    public static final GroupLayout header$layout() {
        return header$LAYOUT;
    }

    private static final long header$OFFSET = $LAYOUT.byteOffset(groupElement("header"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * std_msgs__msg__Header header
     * }
     */
    public static final long header$offset() {
        return header$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * std_msgs__msg__Header header
     * }
     */
    public static MemorySegment header(MemorySegment struct) {
        return struct.asSlice(header$OFFSET, header$LAYOUT.byteSize());
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * std_msgs__msg__Header header
     * }
     */
    public static void header(MemorySegment struct, MemorySegment fieldValue) {
        MemorySegment.copy(fieldValue, 0L, struct, header$OFFSET, header$LAYOUT.byteSize());
    }

    private static final OfByte radiation_type$LAYOUT = (OfByte)$LAYOUT.select(groupElement("radiation_type"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * uint8_t radiation_type
     * }
     */
    public static final OfByte radiation_type$layout() {
        return radiation_type$LAYOUT;
    }

    private static final long radiation_type$OFFSET = $LAYOUT.byteOffset(groupElement("radiation_type"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * uint8_t radiation_type
     * }
     */
    public static final long radiation_type$offset() {
        return radiation_type$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * uint8_t radiation_type
     * }
     */
    public static byte radiation_type(MemorySegment struct) {
        return struct.get(radiation_type$LAYOUT, radiation_type$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * uint8_t radiation_type
     * }
     */
    public static void radiation_type(MemorySegment struct, byte fieldValue) {
        struct.set(radiation_type$LAYOUT, radiation_type$OFFSET, fieldValue);
    }

    private static final OfFloat field_of_view$LAYOUT = (OfFloat)$LAYOUT.select(groupElement("field_of_view"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * float field_of_view
     * }
     */
    public static final OfFloat field_of_view$layout() {
        return field_of_view$LAYOUT;
    }

    private static final long field_of_view$OFFSET = $LAYOUT.byteOffset(groupElement("field_of_view"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * float field_of_view
     * }
     */
    public static final long field_of_view$offset() {
        return field_of_view$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * float field_of_view
     * }
     */
    public static float field_of_view(MemorySegment struct) {
        return struct.get(field_of_view$LAYOUT, field_of_view$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * float field_of_view
     * }
     */
    public static void field_of_view(MemorySegment struct, float fieldValue) {
        struct.set(field_of_view$LAYOUT, field_of_view$OFFSET, fieldValue);
    }

    private static final OfFloat min_range$LAYOUT = (OfFloat)$LAYOUT.select(groupElement("min_range"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * float min_range
     * }
     */
    public static final OfFloat min_range$layout() {
        return min_range$LAYOUT;
    }

    private static final long min_range$OFFSET = $LAYOUT.byteOffset(groupElement("min_range"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * float min_range
     * }
     */
    public static final long min_range$offset() {
        return min_range$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * float min_range
     * }
     */
    public static float min_range(MemorySegment struct) {
        return struct.get(min_range$LAYOUT, min_range$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * float min_range
     * }
     */
    public static void min_range(MemorySegment struct, float fieldValue) {
        struct.set(min_range$LAYOUT, min_range$OFFSET, fieldValue);
    }

    private static final OfFloat max_range$LAYOUT = (OfFloat)$LAYOUT.select(groupElement("max_range"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * float max_range
     * }
     */
    public static final OfFloat max_range$layout() {
        return max_range$LAYOUT;
    }

    private static final long max_range$OFFSET = $LAYOUT.byteOffset(groupElement("max_range"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * float max_range
     * }
     */
    public static final long max_range$offset() {
        return max_range$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * float max_range
     * }
     */
    public static float max_range(MemorySegment struct) {
        return struct.get(max_range$LAYOUT, max_range$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * float max_range
     * }
     */
    public static void max_range(MemorySegment struct, float fieldValue) {
        struct.set(max_range$LAYOUT, max_range$OFFSET, fieldValue);
    }

    private static final OfFloat range$LAYOUT = (OfFloat)$LAYOUT.select(groupElement("range"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * float range
     * }
     */
    public static final OfFloat range$layout() {
        return range$LAYOUT;
    }

    private static final long range$OFFSET = $LAYOUT.byteOffset(groupElement("range"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * float range
     * }
     */
    public static final long range$offset() {
        return range$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * float range
     * }
     */
    public static float range(MemorySegment struct) {
        return struct.get(range$LAYOUT, range$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * float range
     * }
     */
    public static void range(MemorySegment struct, float fieldValue) {
        struct.set(range$LAYOUT, range$OFFSET, fieldValue);
    }

    private static final OfFloat variance$LAYOUT = (OfFloat)$LAYOUT.select(groupElement("variance"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * float variance
     * }
     */
    public static final OfFloat variance$layout() {
        return variance$LAYOUT;
    }

    private static final long variance$OFFSET = $LAYOUT.byteOffset(groupElement("variance"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * float variance
     * }
     */
    public static final long variance$offset() {
        return variance$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * float variance
     * }
     */
    public static float variance(MemorySegment struct) {
        return struct.get(variance$LAYOUT, variance$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * float variance
     * }
     */
    public static void variance(MemorySegment struct, float fieldValue) {
        struct.set(variance$LAYOUT, variance$OFFSET, fieldValue);
    }

    /**
     * Obtains a slice of {@code arrayParam} which selects the array element at {@code index}.
     * The returned segment has address {@code arrayParam.address() + index * layout().byteSize()}
     */
    public static MemorySegment asSlice(MemorySegment array, long index) {
        return array.asSlice(layout().byteSize() * index);
    }

    /**
     * The size (in bytes) of this struct
     */
    public static long sizeof() { return layout().byteSize(); }

    /**
     * Allocate a segment of size {@code layout().byteSize()} using {@code allocator}
     */
    public static MemorySegment allocate(SegmentAllocator allocator) {
        return allocator.allocate(layout());
    }

    /**
     * Allocate an array of size {@code elementCount} using {@code allocator}.
     * The returned segment has size {@code elementCount * layout().byteSize()}.
     */
    public static MemorySegment allocateArray(long elementCount, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(elementCount, layout()));
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, Arena arena, Consumer<MemorySegment> cleanup) {
        return reinterpret(addr, 1, arena, cleanup);
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code elementCount * layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, long elementCount, Arena arena, Consumer<MemorySegment> cleanup) {
        return addr.reinterpret(layout().byteSize() * elementCount, arena, cleanup);
    }
}

