// Generated by jextract

package org.ros2.rcl.msgs;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * struct sensor_msgs__msg__PointCloud2 {
 *     std_msgs__msg__Header header;
 *     uint32_t height;
 *     uint32_t width;
 *     sensor_msgs__msg__PointField__Sequence fields;
 *     bool is_bigendian;
 *     uint32_t point_step;
 *     uint32_t row_step;
 *     rosidl_runtime_c__uint8__Sequence data;
 *     bool is_dense;
 * }
 * }
 */
public class sensor_msgs__msg__PointCloud2 {

    sensor_msgs__msg__PointCloud2() {
        // Should not be called directly
    }

    private static final GroupLayout $LAYOUT = MemoryLayout.structLayout(
        std_msgs__msg__Header.layout().withName("header"),
        SENSOR_MSGS_Lib.C_INT.withName("height"),
        SENSOR_MSGS_Lib.C_INT.withName("width"),
        sensor_msgs__msg__PointField__Sequence.layout().withName("fields"),
        SENSOR_MSGS_Lib.C_BOOL.withName("is_bigendian"),
        MemoryLayout.paddingLayout(3),
        SENSOR_MSGS_Lib.C_INT.withName("point_step"),
        SENSOR_MSGS_Lib.C_INT.withName("row_step"),
        MemoryLayout.paddingLayout(4),
        rosidl_runtime_c__uint8__Sequence.layout().withName("data"),
        SENSOR_MSGS_Lib.C_BOOL.withName("is_dense"),
        MemoryLayout.paddingLayout(7)
    ).withName("sensor_msgs__msg__PointCloud2");

    /**
     * The layout of this struct
     */
    public static final GroupLayout layout() {
        return $LAYOUT;
    }

    private static final GroupLayout header$LAYOUT = (GroupLayout)$LAYOUT.select(groupElement("header"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * std_msgs__msg__Header header
     * }
     */
    public static final GroupLayout header$layout() {
        return header$LAYOUT;
    }

    private static final long header$OFFSET = $LAYOUT.byteOffset(groupElement("header"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * std_msgs__msg__Header header
     * }
     */
    public static final long header$offset() {
        return header$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * std_msgs__msg__Header header
     * }
     */
    public static MemorySegment header(MemorySegment struct) {
        return struct.asSlice(header$OFFSET, header$LAYOUT.byteSize());
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * std_msgs__msg__Header header
     * }
     */
    public static void header(MemorySegment struct, MemorySegment fieldValue) {
        MemorySegment.copy(fieldValue, 0L, struct, header$OFFSET, header$LAYOUT.byteSize());
    }

    private static final OfInt height$LAYOUT = (OfInt)$LAYOUT.select(groupElement("height"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * uint32_t height
     * }
     */
    public static final OfInt height$layout() {
        return height$LAYOUT;
    }

    private static final long height$OFFSET = $LAYOUT.byteOffset(groupElement("height"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * uint32_t height
     * }
     */
    public static final long height$offset() {
        return height$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * uint32_t height
     * }
     */
    public static int height(MemorySegment struct) {
        return struct.get(height$LAYOUT, height$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * uint32_t height
     * }
     */
    public static void height(MemorySegment struct, int fieldValue) {
        struct.set(height$LAYOUT, height$OFFSET, fieldValue);
    }

    private static final OfInt width$LAYOUT = (OfInt)$LAYOUT.select(groupElement("width"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * uint32_t width
     * }
     */
    public static final OfInt width$layout() {
        return width$LAYOUT;
    }

    private static final long width$OFFSET = $LAYOUT.byteOffset(groupElement("width"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * uint32_t width
     * }
     */
    public static final long width$offset() {
        return width$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * uint32_t width
     * }
     */
    public static int width(MemorySegment struct) {
        return struct.get(width$LAYOUT, width$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * uint32_t width
     * }
     */
    public static void width(MemorySegment struct, int fieldValue) {
        struct.set(width$LAYOUT, width$OFFSET, fieldValue);
    }

    private static final GroupLayout fields$LAYOUT = (GroupLayout)$LAYOUT.select(groupElement("fields"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * sensor_msgs__msg__PointField__Sequence fields
     * }
     */
    public static final GroupLayout fields$layout() {
        return fields$LAYOUT;
    }

    private static final long fields$OFFSET = $LAYOUT.byteOffset(groupElement("fields"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * sensor_msgs__msg__PointField__Sequence fields
     * }
     */
    public static final long fields$offset() {
        return fields$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * sensor_msgs__msg__PointField__Sequence fields
     * }
     */
    public static MemorySegment fields(MemorySegment struct) {
        return struct.asSlice(fields$OFFSET, fields$LAYOUT.byteSize());
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * sensor_msgs__msg__PointField__Sequence fields
     * }
     */
    public static void fields(MemorySegment struct, MemorySegment fieldValue) {
        MemorySegment.copy(fieldValue, 0L, struct, fields$OFFSET, fields$LAYOUT.byteSize());
    }

    private static final OfBoolean is_bigendian$LAYOUT = (OfBoolean)$LAYOUT.select(groupElement("is_bigendian"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * bool is_bigendian
     * }
     */
    public static final OfBoolean is_bigendian$layout() {
        return is_bigendian$LAYOUT;
    }

    private static final long is_bigendian$OFFSET = $LAYOUT.byteOffset(groupElement("is_bigendian"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * bool is_bigendian
     * }
     */
    public static final long is_bigendian$offset() {
        return is_bigendian$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * bool is_bigendian
     * }
     */
    public static boolean is_bigendian(MemorySegment struct) {
        return struct.get(is_bigendian$LAYOUT, is_bigendian$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * bool is_bigendian
     * }
     */
    public static void is_bigendian(MemorySegment struct, boolean fieldValue) {
        struct.set(is_bigendian$LAYOUT, is_bigendian$OFFSET, fieldValue);
    }

    private static final OfInt point_step$LAYOUT = (OfInt)$LAYOUT.select(groupElement("point_step"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * uint32_t point_step
     * }
     */
    public static final OfInt point_step$layout() {
        return point_step$LAYOUT;
    }

    private static final long point_step$OFFSET = $LAYOUT.byteOffset(groupElement("point_step"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * uint32_t point_step
     * }
     */
    public static final long point_step$offset() {
        return point_step$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * uint32_t point_step
     * }
     */
    public static int point_step(MemorySegment struct) {
        return struct.get(point_step$LAYOUT, point_step$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * uint32_t point_step
     * }
     */
    public static void point_step(MemorySegment struct, int fieldValue) {
        struct.set(point_step$LAYOUT, point_step$OFFSET, fieldValue);
    }

    private static final OfInt row_step$LAYOUT = (OfInt)$LAYOUT.select(groupElement("row_step"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * uint32_t row_step
     * }
     */
    public static final OfInt row_step$layout() {
        return row_step$LAYOUT;
    }

    private static final long row_step$OFFSET = $LAYOUT.byteOffset(groupElement("row_step"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * uint32_t row_step
     * }
     */
    public static final long row_step$offset() {
        return row_step$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * uint32_t row_step
     * }
     */
    public static int row_step(MemorySegment struct) {
        return struct.get(row_step$LAYOUT, row_step$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * uint32_t row_step
     * }
     */
    public static void row_step(MemorySegment struct, int fieldValue) {
        struct.set(row_step$LAYOUT, row_step$OFFSET, fieldValue);
    }

    private static final GroupLayout data$LAYOUT = (GroupLayout)$LAYOUT.select(groupElement("data"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * rosidl_runtime_c__uint8__Sequence data
     * }
     */
    public static final GroupLayout data$layout() {
        return data$LAYOUT;
    }

    private static final long data$OFFSET = $LAYOUT.byteOffset(groupElement("data"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * rosidl_runtime_c__uint8__Sequence data
     * }
     */
    public static final long data$offset() {
        return data$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * rosidl_runtime_c__uint8__Sequence data
     * }
     */
    public static MemorySegment data(MemorySegment struct) {
        return struct.asSlice(data$OFFSET, data$LAYOUT.byteSize());
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * rosidl_runtime_c__uint8__Sequence data
     * }
     */
    public static void data(MemorySegment struct, MemorySegment fieldValue) {
        MemorySegment.copy(fieldValue, 0L, struct, data$OFFSET, data$LAYOUT.byteSize());
    }

    private static final OfBoolean is_dense$LAYOUT = (OfBoolean)$LAYOUT.select(groupElement("is_dense"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * bool is_dense
     * }
     */
    public static final OfBoolean is_dense$layout() {
        return is_dense$LAYOUT;
    }

    private static final long is_dense$OFFSET = $LAYOUT.byteOffset(groupElement("is_dense"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * bool is_dense
     * }
     */
    public static final long is_dense$offset() {
        return is_dense$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * bool is_dense
     * }
     */
    public static boolean is_dense(MemorySegment struct) {
        return struct.get(is_dense$LAYOUT, is_dense$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * bool is_dense
     * }
     */
    public static void is_dense(MemorySegment struct, boolean fieldValue) {
        struct.set(is_dense$LAYOUT, is_dense$OFFSET, fieldValue);
    }

    /**
     * Obtains a slice of {@code arrayParam} which selects the array element at {@code index}.
     * The returned segment has address {@code arrayParam.address() + index * layout().byteSize()}
     */
    public static MemorySegment asSlice(MemorySegment array, long index) {
        return array.asSlice(layout().byteSize() * index);
    }

    /**
     * The size (in bytes) of this struct
     */
    public static long sizeof() { return layout().byteSize(); }

    /**
     * Allocate a segment of size {@code layout().byteSize()} using {@code allocator}
     */
    public static MemorySegment allocate(SegmentAllocator allocator) {
        return allocator.allocate(layout());
    }

    /**
     * Allocate an array of size {@code elementCount} using {@code allocator}.
     * The returned segment has size {@code elementCount * layout().byteSize()}.
     */
    public static MemorySegment allocateArray(long elementCount, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(elementCount, layout()));
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, Arena arena, Consumer<MemorySegment> cleanup) {
        return reinterpret(addr, 1, arena, cleanup);
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code elementCount * layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, long elementCount, Arena arena, Consumer<MemorySegment> cleanup) {
        return addr.reinterpret(layout().byteSize() * elementCount, arena, cleanup);
    }
}

