// Generated by jextract

package org.ros2.rcl.msgs;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * struct std_msgs__msg__Header {
 *     builtin_interfaces__msg__Time stamp;
 *     rosidl_runtime_c__String frame_id;
 * }
 * }
 */
public class std_msgs__msg__Header {

    std_msgs__msg__Header() {
        // Should not be called directly
    }

    private static final GroupLayout $LAYOUT = MemoryLayout.structLayout(
        builtin_interfaces__msg__Time.layout().withName("stamp"),
        rosidl_runtime_c__String.layout().withName("frame_id")
    ).withName("std_msgs__msg__Header");

    /**
     * The layout of this struct
     */
    public static final GroupLayout layout() {
        return $LAYOUT;
    }

    private static final GroupLayout stamp$LAYOUT = (GroupLayout)$LAYOUT.select(groupElement("stamp"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * builtin_interfaces__msg__Time stamp
     * }
     */
    public static final GroupLayout stamp$layout() {
        return stamp$LAYOUT;
    }

    private static final long stamp$OFFSET = $LAYOUT.byteOffset(groupElement("stamp"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * builtin_interfaces__msg__Time stamp
     * }
     */
    public static final long stamp$offset() {
        return stamp$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * builtin_interfaces__msg__Time stamp
     * }
     */
    public static MemorySegment stamp(MemorySegment struct) {
        return struct.asSlice(stamp$OFFSET, stamp$LAYOUT.byteSize());
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * builtin_interfaces__msg__Time stamp
     * }
     */
    public static void stamp(MemorySegment struct, MemorySegment fieldValue) {
        MemorySegment.copy(fieldValue, 0L, struct, stamp$OFFSET, stamp$LAYOUT.byteSize());
    }

    private static final GroupLayout frame_id$LAYOUT = (GroupLayout)$LAYOUT.select(groupElement("frame_id"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * rosidl_runtime_c__String frame_id
     * }
     */
    public static final GroupLayout frame_id$layout() {
        return frame_id$LAYOUT;
    }

    private static final long frame_id$OFFSET = $LAYOUT.byteOffset(groupElement("frame_id"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * rosidl_runtime_c__String frame_id
     * }
     */
    public static final long frame_id$offset() {
        return frame_id$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * rosidl_runtime_c__String frame_id
     * }
     */
    public static MemorySegment frame_id(MemorySegment struct) {
        return struct.asSlice(frame_id$OFFSET, frame_id$LAYOUT.byteSize());
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * rosidl_runtime_c__String frame_id
     * }
     */
    public static void frame_id(MemorySegment struct, MemorySegment fieldValue) {
        MemorySegment.copy(fieldValue, 0L, struct, frame_id$OFFSET, frame_id$LAYOUT.byteSize());
    }

    /**
     * Obtains a slice of {@code arrayParam} which selects the array element at {@code index}.
     * The returned segment has address {@code arrayParam.address() + index * layout().byteSize()}
     */
    public static MemorySegment asSlice(MemorySegment array, long index) {
        return array.asSlice(layout().byteSize() * index);
    }

    /**
     * The size (in bytes) of this struct
     */
    public static long sizeof() { return layout().byteSize(); }

    /**
     * Allocate a segment of size {@code layout().byteSize()} using {@code allocator}
     */
    public static MemorySegment allocate(SegmentAllocator allocator) {
        return allocator.allocate(layout());
    }

    /**
     * Allocate an array of size {@code elementCount} using {@code allocator}.
     * The returned segment has size {@code elementCount * layout().byteSize()}.
     */
    public static MemorySegment allocateArray(long elementCount, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(elementCount, layout()));
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, Arena arena, Consumer<MemorySegment> cleanup) {
        return reinterpret(addr, 1, arena, cleanup);
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code elementCount * layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, long elementCount, Arena arena, Consumer<MemorySegment> cleanup) {
        return addr.reinterpret(layout().byteSize() * elementCount, arena, cleanup);
    }
}

