// Generated by jextract

package org.ros2.rcl.msgs;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * struct std_srvs__srv__Empty_Event {
 *     service_msgs__msg__ServiceEventInfo info;
 *     std_srvs__srv__Empty_Request__Sequence request;
 *     std_srvs__srv__Empty_Response__Sequence response;
 * }
 * }
 */
public class std_srvs__srv__Empty_Event {

    std_srvs__srv__Empty_Event() {
        // Should not be called directly
    }

    private static final GroupLayout $LAYOUT = MemoryLayout.structLayout(
        service_msgs__msg__ServiceEventInfo.layout().withName("info"),
        std_srvs__srv__Empty_Request__Sequence.layout().withName("request"),
        std_srvs__srv__Empty_Response__Sequence.layout().withName("response")
    ).withName("std_srvs__srv__Empty_Event");

    /**
     * The layout of this struct
     */
    public static final GroupLayout layout() {
        return $LAYOUT;
    }

    private static final GroupLayout info$LAYOUT = (GroupLayout)$LAYOUT.select(groupElement("info"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * service_msgs__msg__ServiceEventInfo info
     * }
     */
    public static final GroupLayout info$layout() {
        return info$LAYOUT;
    }

    private static final long info$OFFSET = $LAYOUT.byteOffset(groupElement("info"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * service_msgs__msg__ServiceEventInfo info
     * }
     */
    public static final long info$offset() {
        return info$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * service_msgs__msg__ServiceEventInfo info
     * }
     */
    public static MemorySegment info(MemorySegment struct) {
        return struct.asSlice(info$OFFSET, info$LAYOUT.byteSize());
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * service_msgs__msg__ServiceEventInfo info
     * }
     */
    public static void info(MemorySegment struct, MemorySegment fieldValue) {
        MemorySegment.copy(fieldValue, 0L, struct, info$OFFSET, info$LAYOUT.byteSize());
    }

    private static final GroupLayout request$LAYOUT = (GroupLayout)$LAYOUT.select(groupElement("request"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * std_srvs__srv__Empty_Request__Sequence request
     * }
     */
    public static final GroupLayout request$layout() {
        return request$LAYOUT;
    }

    private static final long request$OFFSET = $LAYOUT.byteOffset(groupElement("request"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * std_srvs__srv__Empty_Request__Sequence request
     * }
     */
    public static final long request$offset() {
        return request$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * std_srvs__srv__Empty_Request__Sequence request
     * }
     */
    public static MemorySegment request(MemorySegment struct) {
        return struct.asSlice(request$OFFSET, request$LAYOUT.byteSize());
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * std_srvs__srv__Empty_Request__Sequence request
     * }
     */
    public static void request(MemorySegment struct, MemorySegment fieldValue) {
        MemorySegment.copy(fieldValue, 0L, struct, request$OFFSET, request$LAYOUT.byteSize());
    }

    private static final GroupLayout response$LAYOUT = (GroupLayout)$LAYOUT.select(groupElement("response"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * std_srvs__srv__Empty_Response__Sequence response
     * }
     */
    public static final GroupLayout response$layout() {
        return response$LAYOUT;
    }

    private static final long response$OFFSET = $LAYOUT.byteOffset(groupElement("response"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * std_srvs__srv__Empty_Response__Sequence response
     * }
     */
    public static final long response$offset() {
        return response$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * std_srvs__srv__Empty_Response__Sequence response
     * }
     */
    public static MemorySegment response(MemorySegment struct) {
        return struct.asSlice(response$OFFSET, response$LAYOUT.byteSize());
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * std_srvs__srv__Empty_Response__Sequence response
     * }
     */
    public static void response(MemorySegment struct, MemorySegment fieldValue) {
        MemorySegment.copy(fieldValue, 0L, struct, response$OFFSET, response$LAYOUT.byteSize());
    }

    /**
     * Obtains a slice of {@code arrayParam} which selects the array element at {@code index}.
     * The returned segment has address {@code arrayParam.address() + index * layout().byteSize()}
     */
    public static MemorySegment asSlice(MemorySegment array, long index) {
        return array.asSlice(layout().byteSize() * index);
    }

    /**
     * The size (in bytes) of this struct
     */
    public static long sizeof() { return layout().byteSize(); }

    /**
     * Allocate a segment of size {@code layout().byteSize()} using {@code allocator}
     */
    public static MemorySegment allocate(SegmentAllocator allocator) {
        return allocator.allocate(layout());
    }

    /**
     * Allocate an array of size {@code elementCount} using {@code allocator}.
     * The returned segment has size {@code elementCount * layout().byteSize()}.
     */
    public static MemorySegment allocateArray(long elementCount, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(elementCount, layout()));
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, Arena arena, Consumer<MemorySegment> cleanup) {
        return reinterpret(addr, 1, arena, cleanup);
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code elementCount * layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, long elementCount, Arena arena, Consumer<MemorySegment> cleanup) {
        return addr.reinterpret(layout().byteSize() * elementCount, arena, cleanup);
    }
}

