// Generated by jextract

package org.ros2.rcl.msgs;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * struct std_msgs__msg__MultiArrayLayout {
 *     std_msgs__msg__MultiArrayDimension__Sequence dim;
 *     uint32_t data_offset;
 * }
 * }
 */
public class std_msgs__msg__MultiArrayLayout {

    std_msgs__msg__MultiArrayLayout() {
        // Should not be called directly
    }

    private static final GroupLayout $LAYOUT = MemoryLayout.structLayout(
        std_msgs__msg__MultiArrayDimension__Sequence.layout().withName("dim"),
        STD_MSGS_Lib.C_INT.withName("data_offset"),
        MemoryLayout.paddingLayout(4)
    ).withName("std_msgs__msg__MultiArrayLayout");

    /**
     * The layout of this struct
     */
    public static final GroupLayout layout() {
        return $LAYOUT;
    }

    private static final GroupLayout dim$LAYOUT = (GroupLayout)$LAYOUT.select(groupElement("dim"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * std_msgs__msg__MultiArrayDimension__Sequence dim
     * }
     */
    public static final GroupLayout dim$layout() {
        return dim$LAYOUT;
    }

    private static final long dim$OFFSET = $LAYOUT.byteOffset(groupElement("dim"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * std_msgs__msg__MultiArrayDimension__Sequence dim
     * }
     */
    public static final long dim$offset() {
        return dim$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * std_msgs__msg__MultiArrayDimension__Sequence dim
     * }
     */
    public static MemorySegment dim(MemorySegment struct) {
        return struct.asSlice(dim$OFFSET, dim$LAYOUT.byteSize());
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * std_msgs__msg__MultiArrayDimension__Sequence dim
     * }
     */
    public static void dim(MemorySegment struct, MemorySegment fieldValue) {
        MemorySegment.copy(fieldValue, 0L, struct, dim$OFFSET, dim$LAYOUT.byteSize());
    }

    private static final OfInt data_offset$LAYOUT = (OfInt)$LAYOUT.select(groupElement("data_offset"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * uint32_t data_offset
     * }
     */
    public static final OfInt data_offset$layout() {
        return data_offset$LAYOUT;
    }

    private static final long data_offset$OFFSET = $LAYOUT.byteOffset(groupElement("data_offset"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * uint32_t data_offset
     * }
     */
    public static final long data_offset$offset() {
        return data_offset$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * uint32_t data_offset
     * }
     */
    public static int data_offset(MemorySegment struct) {
        return struct.get(data_offset$LAYOUT, data_offset$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * uint32_t data_offset
     * }
     */
    public static void data_offset(MemorySegment struct, int fieldValue) {
        struct.set(data_offset$LAYOUT, data_offset$OFFSET, fieldValue);
    }

    /**
     * Obtains a slice of {@code arrayParam} which selects the array element at {@code index}.
     * The returned segment has address {@code arrayParam.address() + index * layout().byteSize()}
     */
    public static MemorySegment asSlice(MemorySegment array, long index) {
        return array.asSlice(layout().byteSize() * index);
    }

    /**
     * The size (in bytes) of this struct
     */
    public static long sizeof() { return layout().byteSize(); }

    /**
     * Allocate a segment of size {@code layout().byteSize()} using {@code allocator}
     */
    public static MemorySegment allocate(SegmentAllocator allocator) {
        return allocator.allocate(layout());
    }

    /**
     * Allocate an array of size {@code elementCount} using {@code allocator}.
     * The returned segment has size {@code elementCount * layout().byteSize()}.
     */
    public static MemorySegment allocateArray(long elementCount, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(elementCount, layout()));
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, Arena arena, Consumer<MemorySegment> cleanup) {
        return reinterpret(addr, 1, arena, cleanup);
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code elementCount * layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, long elementCount, Arena arena, Consumer<MemorySegment> cleanup) {
        return addr.reinterpret(layout().byteSize() * elementCount, arena, cleanup);
    }
}

