// Generated by jextract

package org.ros2.rcl;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * struct rcl_timer_on_reset_callback_data_s {
 *     rcl_event_callback_t on_reset_callback;
 *     const void *user_data;
 *     size_t reset_counter;
 * }
 * }
 */
public class rcl_timer_on_reset_callback_data_s {

    rcl_timer_on_reset_callback_data_s() {
        // Should not be called directly
    }

    private static final GroupLayout $LAYOUT = MemoryLayout.structLayout(
        RclLib.C_POINTER.withName("on_reset_callback"),
        RclLib.C_POINTER.withName("user_data"),
        RclLib.C_LONG.withName("reset_counter")
    ).withName("rcl_timer_on_reset_callback_data_s");

    /**
     * The layout of this struct
     */
    public static final GroupLayout layout() {
        return $LAYOUT;
    }

    private static final AddressLayout on_reset_callback$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("on_reset_callback"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * rcl_event_callback_t on_reset_callback
     * }
     */
    public static final AddressLayout on_reset_callback$layout() {
        return on_reset_callback$LAYOUT;
    }

    private static final long on_reset_callback$OFFSET = $LAYOUT.byteOffset(groupElement("on_reset_callback"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * rcl_event_callback_t on_reset_callback
     * }
     */
    public static final long on_reset_callback$offset() {
        return on_reset_callback$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * rcl_event_callback_t on_reset_callback
     * }
     */
    public static MemorySegment on_reset_callback(MemorySegment struct) {
        return struct.get(on_reset_callback$LAYOUT, on_reset_callback$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * rcl_event_callback_t on_reset_callback
     * }
     */
    public static void on_reset_callback(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(on_reset_callback$LAYOUT, on_reset_callback$OFFSET, fieldValue);
    }

    private static final AddressLayout user_data$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("user_data"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * const void *user_data
     * }
     */
    public static final AddressLayout user_data$layout() {
        return user_data$LAYOUT;
    }

    private static final long user_data$OFFSET = $LAYOUT.byteOffset(groupElement("user_data"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * const void *user_data
     * }
     */
    public static final long user_data$offset() {
        return user_data$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * const void *user_data
     * }
     */
    public static MemorySegment user_data(MemorySegment struct) {
        return struct.get(user_data$LAYOUT, user_data$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * const void *user_data
     * }
     */
    public static void user_data(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(user_data$LAYOUT, user_data$OFFSET, fieldValue);
    }

    private static final OfLong reset_counter$LAYOUT = (OfLong)$LAYOUT.select(groupElement("reset_counter"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * size_t reset_counter
     * }
     */
    public static final OfLong reset_counter$layout() {
        return reset_counter$LAYOUT;
    }

    private static final long reset_counter$OFFSET = $LAYOUT.byteOffset(groupElement("reset_counter"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * size_t reset_counter
     * }
     */
    public static final long reset_counter$offset() {
        return reset_counter$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * size_t reset_counter
     * }
     */
    public static long reset_counter(MemorySegment struct) {
        return struct.get(reset_counter$LAYOUT, reset_counter$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * size_t reset_counter
     * }
     */
    public static void reset_counter(MemorySegment struct, long fieldValue) {
        struct.set(reset_counter$LAYOUT, reset_counter$OFFSET, fieldValue);
    }

    /**
     * Obtains a slice of {@code arrayParam} which selects the array element at {@code index}.
     * The returned segment has address {@code arrayParam.address() + index * layout().byteSize()}
     */
    public static MemorySegment asSlice(MemorySegment array, long index) {
        return array.asSlice(layout().byteSize() * index);
    }

    /**
     * The size (in bytes) of this struct
     */
    public static long sizeof() { return layout().byteSize(); }

    /**
     * Allocate a segment of size {@code layout().byteSize()} using {@code allocator}
     */
    public static MemorySegment allocate(SegmentAllocator allocator) {
        return allocator.allocate(layout());
    }

    /**
     * Allocate an array of size {@code elementCount} using {@code allocator}.
     * The returned segment has size {@code elementCount * layout().byteSize()}.
     */
    public static MemorySegment allocateArray(long elementCount, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(elementCount, layout()));
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, Arena arena, Consumer<MemorySegment> cleanup) {
        return reinterpret(addr, 1, arena, cleanup);
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code elementCount * layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, long elementCount, Arena arena, Consumer<MemorySegment> cleanup) {
        return addr.reinterpret(layout().byteSize() * elementCount, arena, cleanup);
    }
}

