// Generated by jextract

package org.ros2.rcl;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * struct rcl_timer_call_info_s {
 *     rcl_time_point_value_t expected_call_time;
 *     rcl_time_point_value_t actual_call_time;
 * }
 * }
 */
public class rcl_timer_call_info_s {

    rcl_timer_call_info_s() {
        // Should not be called directly
    }

    private static final GroupLayout $LAYOUT = MemoryLayout.structLayout(
        RclLib.C_LONG.withName("expected_call_time"),
        RclLib.C_LONG.withName("actual_call_time")
    ).withName("rcl_timer_call_info_s");

    /**
     * The layout of this struct
     */
    public static final GroupLayout layout() {
        return $LAYOUT;
    }

    private static final OfLong expected_call_time$LAYOUT = (OfLong)$LAYOUT.select(groupElement("expected_call_time"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * rcl_time_point_value_t expected_call_time
     * }
     */
    public static final OfLong expected_call_time$layout() {
        return expected_call_time$LAYOUT;
    }

    private static final long expected_call_time$OFFSET = $LAYOUT.byteOffset(groupElement("expected_call_time"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * rcl_time_point_value_t expected_call_time
     * }
     */
    public static final long expected_call_time$offset() {
        return expected_call_time$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * rcl_time_point_value_t expected_call_time
     * }
     */
    public static long expected_call_time(MemorySegment struct) {
        return struct.get(expected_call_time$LAYOUT, expected_call_time$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * rcl_time_point_value_t expected_call_time
     * }
     */
    public static void expected_call_time(MemorySegment struct, long fieldValue) {
        struct.set(expected_call_time$LAYOUT, expected_call_time$OFFSET, fieldValue);
    }

    private static final OfLong actual_call_time$LAYOUT = (OfLong)$LAYOUT.select(groupElement("actual_call_time"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * rcl_time_point_value_t actual_call_time
     * }
     */
    public static final OfLong actual_call_time$layout() {
        return actual_call_time$LAYOUT;
    }

    private static final long actual_call_time$OFFSET = $LAYOUT.byteOffset(groupElement("actual_call_time"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * rcl_time_point_value_t actual_call_time
     * }
     */
    public static final long actual_call_time$offset() {
        return actual_call_time$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * rcl_time_point_value_t actual_call_time
     * }
     */
    public static long actual_call_time(MemorySegment struct) {
        return struct.get(actual_call_time$LAYOUT, actual_call_time$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * rcl_time_point_value_t actual_call_time
     * }
     */
    public static void actual_call_time(MemorySegment struct, long fieldValue) {
        struct.set(actual_call_time$LAYOUT, actual_call_time$OFFSET, fieldValue);
    }

    /**
     * Obtains a slice of {@code arrayParam} which selects the array element at {@code index}.
     * The returned segment has address {@code arrayParam.address() + index * layout().byteSize()}
     */
    public static MemorySegment asSlice(MemorySegment array, long index) {
        return array.asSlice(layout().byteSize() * index);
    }

    /**
     * The size (in bytes) of this struct
     */
    public static long sizeof() { return layout().byteSize(); }

    /**
     * Allocate a segment of size {@code layout().byteSize()} using {@code allocator}
     */
    public static MemorySegment allocate(SegmentAllocator allocator) {
        return allocator.allocate(layout());
    }

    /**
     * Allocate an array of size {@code elementCount} using {@code allocator}.
     * The returned segment has size {@code elementCount * layout().byteSize()}.
     */
    public static MemorySegment allocateArray(long elementCount, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(elementCount, layout()));
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, Arena arena, Consumer<MemorySegment> cleanup) {
        return reinterpret(addr, 1, arena, cleanup);
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code elementCount * layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, long elementCount, Arena arena, Consumer<MemorySegment> cleanup) {
        return addr.reinterpret(layout().byteSize() * elementCount, arena, cleanup);
    }
}

