// Generated by jextract

package org.ros2.rcl;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * typedef struct rcl_timer_call_info_s {
 *     rcl_time_point_value_t expected_call_time;
 *     rcl_time_point_value_t actual_call_time;
 * } rcl_timer_call_info_t
 * }
 */
public class rcl_timer_call_info_t extends rcl_timer_call_info_s {

    rcl_timer_call_info_t() {
        // Should not be called directly
    }
}

