// Generated by jextract

package org.ros2.rcl;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * typedef struct rcl_timer_on_reset_callback_data_s {
 *     rcl_event_callback_t on_reset_callback;
 *     const void *user_data;
 *     size_t reset_counter;
 * } rcl_timer_on_reset_callback_data_t
 * }
 */
public class rcl_timer_on_reset_callback_data_t extends rcl_timer_on_reset_callback_data_s {

    rcl_timer_on_reset_callback_data_t() {
        // Should not be called directly
    }
}

