// Generated by jextract

package org.ros2.rcl;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * typedef void (*rcutils_logging_output_handler_t)(const rcutils_log_location_t *, int, const char *, rcutils_time_point_value_t, const char *, va_list *)
 * }
 */
public final class rcutils_logging_output_handler_t {

    private rcutils_logging_output_handler_t() {
        // Should not be called directly
    }

    /**
     * The function pointer signature, expressed as a functional interface
     */
    public interface Function {
        void apply(MemorySegment location, int severity, MemorySegment name, long timestamp, MemorySegment format, MemorySegment args);
    }

    private static final FunctionDescriptor $DESC = FunctionDescriptor.ofVoid(
        RclLib.C_POINTER,
        RclLib.C_INT,
        RclLib.C_POINTER,
        RclLib.C_LONG,
        RclLib.C_POINTER,
        RclLib.C_POINTER
    );

    /**
     * The descriptor of this function pointer
     */
    public static FunctionDescriptor descriptor() {
        return $DESC;
    }

    private static final MethodHandle UP$MH = RclLib.upcallHandle(rcutils_logging_output_handler_t.Function.class, "apply", $DESC);

    /**
     * Allocates a new upcall stub, whose implementation is defined by {@code fi}.
     * The lifetime of the returned segment is managed by {@code arena}
     */
    public static MemorySegment allocate(rcutils_logging_output_handler_t.Function fi, Arena arena) {
        return Linker.nativeLinker().upcallStub(UP$MH.bindTo(fi), $DESC, arena);
    }

    private static final MethodHandle DOWN$MH = Linker.nativeLinker().downcallHandle($DESC);

    /**
     * Invoke the upcall stub {@code funcPtr}, with given parameters
     */
    public static void invoke(MemorySegment funcPtr, MemorySegment location, int severity, MemorySegment name, long timestamp, MemorySegment format, MemorySegment args) {
        try {
             DOWN$MH.invokeExact(funcPtr, location, severity, name, timestamp, format, args);
        } catch (Error | RuntimeException ex) {
            throw ex;
        } catch (Throwable ex$) {
            throw new AssertionError("should not reach here", ex$);
        }
    }
}

