// Generated by jextract

package org.ros2.rcl;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * struct rmw_discovery_options_s {
 *     rmw_automatic_discovery_range_t automatic_discovery_range;
 *     rmw_peer_address_t *static_peers;
 *     size_t static_peers_count;
 *     rcutils_allocator_t allocator;
 * }
 * }
 */
public class rmw_discovery_options_s {

    rmw_discovery_options_s() {
        // Should not be called directly
    }

    private static final GroupLayout $LAYOUT = MemoryLayout.structLayout(
        RclLib.C_INT.withName("automatic_discovery_range"),
        MemoryLayout.paddingLayout(4),
        RclLib.C_POINTER.withName("static_peers"),
        RclLib.C_LONG.withName("static_peers_count"),
        rcutils_allocator_s.layout().withName("allocator")
    ).withName("rmw_discovery_options_s");

    /**
     * The layout of this struct
     */
    public static final GroupLayout layout() {
        return $LAYOUT;
    }

    private static final OfInt automatic_discovery_range$LAYOUT = (OfInt)$LAYOUT.select(groupElement("automatic_discovery_range"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * rmw_automatic_discovery_range_t automatic_discovery_range
     * }
     */
    public static final OfInt automatic_discovery_range$layout() {
        return automatic_discovery_range$LAYOUT;
    }

    private static final long automatic_discovery_range$OFFSET = $LAYOUT.byteOffset(groupElement("automatic_discovery_range"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * rmw_automatic_discovery_range_t automatic_discovery_range
     * }
     */
    public static final long automatic_discovery_range$offset() {
        return automatic_discovery_range$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * rmw_automatic_discovery_range_t automatic_discovery_range
     * }
     */
    public static int automatic_discovery_range(MemorySegment struct) {
        return struct.get(automatic_discovery_range$LAYOUT, automatic_discovery_range$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * rmw_automatic_discovery_range_t automatic_discovery_range
     * }
     */
    public static void automatic_discovery_range(MemorySegment struct, int fieldValue) {
        struct.set(automatic_discovery_range$LAYOUT, automatic_discovery_range$OFFSET, fieldValue);
    }

    private static final AddressLayout static_peers$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("static_peers"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * rmw_peer_address_t *static_peers
     * }
     */
    public static final AddressLayout static_peers$layout() {
        return static_peers$LAYOUT;
    }

    private static final long static_peers$OFFSET = $LAYOUT.byteOffset(groupElement("static_peers"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * rmw_peer_address_t *static_peers
     * }
     */
    public static final long static_peers$offset() {
        return static_peers$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * rmw_peer_address_t *static_peers
     * }
     */
    public static MemorySegment static_peers(MemorySegment struct) {
        return struct.get(static_peers$LAYOUT, static_peers$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * rmw_peer_address_t *static_peers
     * }
     */
    public static void static_peers(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(static_peers$LAYOUT, static_peers$OFFSET, fieldValue);
    }

    private static final OfLong static_peers_count$LAYOUT = (OfLong)$LAYOUT.select(groupElement("static_peers_count"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * size_t static_peers_count
     * }
     */
    public static final OfLong static_peers_count$layout() {
        return static_peers_count$LAYOUT;
    }

    private static final long static_peers_count$OFFSET = $LAYOUT.byteOffset(groupElement("static_peers_count"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * size_t static_peers_count
     * }
     */
    public static final long static_peers_count$offset() {
        return static_peers_count$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * size_t static_peers_count
     * }
     */
    public static long static_peers_count(MemorySegment struct) {
        return struct.get(static_peers_count$LAYOUT, static_peers_count$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * size_t static_peers_count
     * }
     */
    public static void static_peers_count(MemorySegment struct, long fieldValue) {
        struct.set(static_peers_count$LAYOUT, static_peers_count$OFFSET, fieldValue);
    }

    private static final GroupLayout allocator$LAYOUT = (GroupLayout)$LAYOUT.select(groupElement("allocator"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * rcutils_allocator_t allocator
     * }
     */
    public static final GroupLayout allocator$layout() {
        return allocator$LAYOUT;
    }

    private static final long allocator$OFFSET = $LAYOUT.byteOffset(groupElement("allocator"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * rcutils_allocator_t allocator
     * }
     */
    public static final long allocator$offset() {
        return allocator$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * rcutils_allocator_t allocator
     * }
     */
    public static MemorySegment allocator(MemorySegment struct) {
        return struct.asSlice(allocator$OFFSET, allocator$LAYOUT.byteSize());
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * rcutils_allocator_t allocator
     * }
     */
    public static void allocator(MemorySegment struct, MemorySegment fieldValue) {
        MemorySegment.copy(fieldValue, 0L, struct, allocator$OFFSET, allocator$LAYOUT.byteSize());
    }

    /**
     * Obtains a slice of {@code arrayParam} which selects the array element at {@code index}.
     * The returned segment has address {@code arrayParam.address() + index * layout().byteSize()}
     */
    public static MemorySegment asSlice(MemorySegment array, long index) {
        return array.asSlice(layout().byteSize() * index);
    }

    /**
     * The size (in bytes) of this struct
     */
    public static long sizeof() { return layout().byteSize(); }

    /**
     * Allocate a segment of size {@code layout().byteSize()} using {@code allocator}
     */
    public static MemorySegment allocate(SegmentAllocator allocator) {
        return allocator.allocate(layout());
    }

    /**
     * Allocate an array of size {@code elementCount} using {@code allocator}.
     * The returned segment has size {@code elementCount * layout().byteSize()}.
     */
    public static MemorySegment allocateArray(long elementCount, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(elementCount, layout()));
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, Arena arena, Consumer<MemorySegment> cleanup) {
        return reinterpret(addr, 1, arena, cleanup);
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code elementCount * layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, long elementCount, Arena arena, Consumer<MemorySegment> cleanup) {
        return addr.reinterpret(layout().byteSize() * elementCount, arena, cleanup);
    }
}

