// Generated by jextract

package org.ros2.rcl;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * typedef struct rmw_discovery_options_s {
 *     rmw_automatic_discovery_range_t automatic_discovery_range;
 *     rmw_peer_address_t *static_peers;
 *     size_t static_peers_count;
 *     rcutils_allocator_t allocator;
 * } rmw_discovery_options_t
 * }
 */
public class rmw_discovery_options_t extends rmw_discovery_options_s {

    rmw_discovery_options_t() {
        // Should not be called directly
    }
}

