// Generated by jextract

package org.ros2.rcl;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * typedef struct rosidl_service_introspection_info_s {
 *     uint8_t event_type;
 *     int32_t stamp_sec;
 *     uint32_t stamp_nanosec;
 *     uint8_t client_gid[16];
 *     int64_t sequence_number;
 * } rosidl_service_introspection_info_t
 * }
 */
public class rosidl_service_introspection_info_t extends rosidl_service_introspection_info_s {

    rosidl_service_introspection_info_t() {
        // Should not be called directly
    }
}

