// Generated by jextract

package org.ros2.rcl;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * typedef struct rosidl_type_hash_s {
 *     uint8_t version;
 *     uint8_t value[32];
 * } rosidl_type_hash_t
 * }
 */
public class rosidl_type_hash_t extends rosidl_type_hash_s {

    rosidl_type_hash_t() {
        // Should not be called directly
    }
}

