// Generated by jextract

package org.ros2.rcl;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * typedef struct rosidl_dynamic_message_type_support_impl_s {
 *     rcutils_allocator_t allocator;
 *     rosidl_type_hash_t type_hash;
 *     rosidl_runtime_c__type_description__TypeDescription type_description;
 *     rosidl_runtime_c__type_description__TypeSource__Sequence type_description_sources;
 *     rosidl_dynamic_typesupport_serialization_support_t serialization_support;
 *     rosidl_dynamic_typesupport_dynamic_type_t *dynamic_message_type;
 *     rosidl_dynamic_typesupport_dynamic_data_t *dynamic_message;
 * } rosidl_dynamic_message_type_support_impl_t
 * }
 */
public class rosidl_dynamic_message_type_support_impl_t extends rosidl_dynamic_message_type_support_impl_s {

    rosidl_dynamic_message_type_support_impl_t() {
        // Should not be called directly
    }
}

