// Generated by jextract

package org.ros2.rcl;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * typedef struct rosidl_dynamic_typesupport_dynamic_data_impl_s rosidl_dynamic_typesupport_dynamic_data_impl_t
 * }
 */
public class rosidl_dynamic_typesupport_dynamic_data_impl_t extends rosidl_dynamic_typesupport_dynamic_data_impl_s {

    rosidl_dynamic_typesupport_dynamic_data_impl_t() {
        // Should not be called directly
    }
}

