// Generated by jextract

package org.ros2.rcl;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * struct rosidl_dynamic_message_type_support_impl_s {
 *     rcutils_allocator_t allocator;
 *     rosidl_type_hash_t type_hash;
 *     rosidl_runtime_c__type_description__TypeDescription type_description;
 *     rosidl_runtime_c__type_description__TypeSource__Sequence type_description_sources;
 *     rosidl_dynamic_typesupport_serialization_support_t serialization_support;
 *     rosidl_dynamic_typesupport_dynamic_type_t *dynamic_message_type;
 *     rosidl_dynamic_typesupport_dynamic_data_t *dynamic_message;
 * }
 * }
 */
public class rosidl_dynamic_message_type_support_impl_s {

    rosidl_dynamic_message_type_support_impl_s() {
        // Should not be called directly
    }

    private static final GroupLayout $LAYOUT = MemoryLayout.structLayout(
        rcutils_allocator_s.layout().withName("allocator"),
        rosidl_type_hash_s.layout().withName("type_hash"),
        MemoryLayout.paddingLayout(7),
        rosidl_runtime_c__type_description__TypeDescription.layout().withName("type_description"),
        rosidl_runtime_c__type_description__TypeSource__Sequence.layout().withName("type_description_sources"),
        rosidl_dynamic_typesupport_serialization_support_s.layout().withName("serialization_support"),
        RclLib.C_POINTER.withName("dynamic_message_type"),
        RclLib.C_POINTER.withName("dynamic_message")
    ).withName("rosidl_dynamic_message_type_support_impl_s");

    /**
     * The layout of this struct
     */
    public static final GroupLayout layout() {
        return $LAYOUT;
    }

    private static final GroupLayout allocator$LAYOUT = (GroupLayout)$LAYOUT.select(groupElement("allocator"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * rcutils_allocator_t allocator
     * }
     */
    public static final GroupLayout allocator$layout() {
        return allocator$LAYOUT;
    }

    private static final long allocator$OFFSET = $LAYOUT.byteOffset(groupElement("allocator"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * rcutils_allocator_t allocator
     * }
     */
    public static final long allocator$offset() {
        return allocator$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * rcutils_allocator_t allocator
     * }
     */
    public static MemorySegment allocator(MemorySegment struct) {
        return struct.asSlice(allocator$OFFSET, allocator$LAYOUT.byteSize());
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * rcutils_allocator_t allocator
     * }
     */
    public static void allocator(MemorySegment struct, MemorySegment fieldValue) {
        MemorySegment.copy(fieldValue, 0L, struct, allocator$OFFSET, allocator$LAYOUT.byteSize());
    }

    private static final GroupLayout type_hash$LAYOUT = (GroupLayout)$LAYOUT.select(groupElement("type_hash"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * rosidl_type_hash_t type_hash
     * }
     */
    public static final GroupLayout type_hash$layout() {
        return type_hash$LAYOUT;
    }

    private static final long type_hash$OFFSET = $LAYOUT.byteOffset(groupElement("type_hash"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * rosidl_type_hash_t type_hash
     * }
     */
    public static final long type_hash$offset() {
        return type_hash$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * rosidl_type_hash_t type_hash
     * }
     */
    public static MemorySegment type_hash(MemorySegment struct) {
        return struct.asSlice(type_hash$OFFSET, type_hash$LAYOUT.byteSize());
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * rosidl_type_hash_t type_hash
     * }
     */
    public static void type_hash(MemorySegment struct, MemorySegment fieldValue) {
        MemorySegment.copy(fieldValue, 0L, struct, type_hash$OFFSET, type_hash$LAYOUT.byteSize());
    }

    private static final GroupLayout type_description$LAYOUT = (GroupLayout)$LAYOUT.select(groupElement("type_description"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * rosidl_runtime_c__type_description__TypeDescription type_description
     * }
     */
    public static final GroupLayout type_description$layout() {
        return type_description$LAYOUT;
    }

    private static final long type_description$OFFSET = $LAYOUT.byteOffset(groupElement("type_description"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * rosidl_runtime_c__type_description__TypeDescription type_description
     * }
     */
    public static final long type_description$offset() {
        return type_description$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * rosidl_runtime_c__type_description__TypeDescription type_description
     * }
     */
    public static MemorySegment type_description(MemorySegment struct) {
        return struct.asSlice(type_description$OFFSET, type_description$LAYOUT.byteSize());
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * rosidl_runtime_c__type_description__TypeDescription type_description
     * }
     */
    public static void type_description(MemorySegment struct, MemorySegment fieldValue) {
        MemorySegment.copy(fieldValue, 0L, struct, type_description$OFFSET, type_description$LAYOUT.byteSize());
    }

    private static final GroupLayout type_description_sources$LAYOUT = (GroupLayout)$LAYOUT.select(groupElement("type_description_sources"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * rosidl_runtime_c__type_description__TypeSource__Sequence type_description_sources
     * }
     */
    public static final GroupLayout type_description_sources$layout() {
        return type_description_sources$LAYOUT;
    }

    private static final long type_description_sources$OFFSET = $LAYOUT.byteOffset(groupElement("type_description_sources"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * rosidl_runtime_c__type_description__TypeSource__Sequence type_description_sources
     * }
     */
    public static final long type_description_sources$offset() {
        return type_description_sources$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * rosidl_runtime_c__type_description__TypeSource__Sequence type_description_sources
     * }
     */
    public static MemorySegment type_description_sources(MemorySegment struct) {
        return struct.asSlice(type_description_sources$OFFSET, type_description_sources$LAYOUT.byteSize());
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * rosidl_runtime_c__type_description__TypeSource__Sequence type_description_sources
     * }
     */
    public static void type_description_sources(MemorySegment struct, MemorySegment fieldValue) {
        MemorySegment.copy(fieldValue, 0L, struct, type_description_sources$OFFSET, type_description_sources$LAYOUT.byteSize());
    }

    private static final GroupLayout serialization_support$LAYOUT = (GroupLayout)$LAYOUT.select(groupElement("serialization_support"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * rosidl_dynamic_typesupport_serialization_support_t serialization_support
     * }
     */
    public static final GroupLayout serialization_support$layout() {
        return serialization_support$LAYOUT;
    }

    private static final long serialization_support$OFFSET = $LAYOUT.byteOffset(groupElement("serialization_support"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * rosidl_dynamic_typesupport_serialization_support_t serialization_support
     * }
     */
    public static final long serialization_support$offset() {
        return serialization_support$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * rosidl_dynamic_typesupport_serialization_support_t serialization_support
     * }
     */
    public static MemorySegment serialization_support(MemorySegment struct) {
        return struct.asSlice(serialization_support$OFFSET, serialization_support$LAYOUT.byteSize());
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * rosidl_dynamic_typesupport_serialization_support_t serialization_support
     * }
     */
    public static void serialization_support(MemorySegment struct, MemorySegment fieldValue) {
        MemorySegment.copy(fieldValue, 0L, struct, serialization_support$OFFSET, serialization_support$LAYOUT.byteSize());
    }

    private static final AddressLayout dynamic_message_type$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("dynamic_message_type"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * rosidl_dynamic_typesupport_dynamic_type_t *dynamic_message_type
     * }
     */
    public static final AddressLayout dynamic_message_type$layout() {
        return dynamic_message_type$LAYOUT;
    }

    private static final long dynamic_message_type$OFFSET = $LAYOUT.byteOffset(groupElement("dynamic_message_type"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * rosidl_dynamic_typesupport_dynamic_type_t *dynamic_message_type
     * }
     */
    public static final long dynamic_message_type$offset() {
        return dynamic_message_type$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * rosidl_dynamic_typesupport_dynamic_type_t *dynamic_message_type
     * }
     */
    public static MemorySegment dynamic_message_type(MemorySegment struct) {
        return struct.get(dynamic_message_type$LAYOUT, dynamic_message_type$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * rosidl_dynamic_typesupport_dynamic_type_t *dynamic_message_type
     * }
     */
    public static void dynamic_message_type(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(dynamic_message_type$LAYOUT, dynamic_message_type$OFFSET, fieldValue);
    }

    private static final AddressLayout dynamic_message$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("dynamic_message"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * rosidl_dynamic_typesupport_dynamic_data_t *dynamic_message
     * }
     */
    public static final AddressLayout dynamic_message$layout() {
        return dynamic_message$LAYOUT;
    }

    private static final long dynamic_message$OFFSET = $LAYOUT.byteOffset(groupElement("dynamic_message"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * rosidl_dynamic_typesupport_dynamic_data_t *dynamic_message
     * }
     */
    public static final long dynamic_message$offset() {
        return dynamic_message$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * rosidl_dynamic_typesupport_dynamic_data_t *dynamic_message
     * }
     */
    public static MemorySegment dynamic_message(MemorySegment struct) {
        return struct.get(dynamic_message$LAYOUT, dynamic_message$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * rosidl_dynamic_typesupport_dynamic_data_t *dynamic_message
     * }
     */
    public static void dynamic_message(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(dynamic_message$LAYOUT, dynamic_message$OFFSET, fieldValue);
    }

    /**
     * Obtains a slice of {@code arrayParam} which selects the array element at {@code index}.
     * The returned segment has address {@code arrayParam.address() + index * layout().byteSize()}
     */
    public static MemorySegment asSlice(MemorySegment array, long index) {
        return array.asSlice(layout().byteSize() * index);
    }

    /**
     * The size (in bytes) of this struct
     */
    public static long sizeof() { return layout().byteSize(); }

    /**
     * Allocate a segment of size {@code layout().byteSize()} using {@code allocator}
     */
    public static MemorySegment allocate(SegmentAllocator allocator) {
        return allocator.allocate(layout());
    }

    /**
     * Allocate an array of size {@code elementCount} using {@code allocator}.
     * The returned segment has size {@code elementCount * layout().byteSize()}.
     */
    public static MemorySegment allocateArray(long elementCount, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(elementCount, layout()));
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, Arena arena, Consumer<MemorySegment> cleanup) {
        return reinterpret(addr, 1, arena, cleanup);
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code elementCount * layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, long elementCount, Arena arena, Consumer<MemorySegment> cleanup) {
        return addr.reinterpret(layout().byteSize() * elementCount, arena, cleanup);
    }
}

