// Generated by jextract

package org.ros2.rcl;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * struct rosidl_runtime_c__type_description__Field {
 *     rosidl_runtime_c__String name;
 *     rosidl_runtime_c__type_description__FieldType type;
 *     rosidl_runtime_c__String default_value;
 * }
 * }
 */
public class rosidl_runtime_c__type_description__Field {

    rosidl_runtime_c__type_description__Field() {
        // Should not be called directly
    }

    private static final GroupLayout $LAYOUT = MemoryLayout.structLayout(
        rosidl_runtime_c__String.layout().withName("name"),
        rosidl_runtime_c__type_description__FieldType.layout().withName("type"),
        rosidl_runtime_c__String.layout().withName("default_value")
    ).withName("rosidl_runtime_c__type_description__Field");

    /**
     * The layout of this struct
     */
    public static final GroupLayout layout() {
        return $LAYOUT;
    }

    private static final GroupLayout name$LAYOUT = (GroupLayout)$LAYOUT.select(groupElement("name"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * rosidl_runtime_c__String name
     * }
     */
    public static final GroupLayout name$layout() {
        return name$LAYOUT;
    }

    private static final long name$OFFSET = $LAYOUT.byteOffset(groupElement("name"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * rosidl_runtime_c__String name
     * }
     */
    public static final long name$offset() {
        return name$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * rosidl_runtime_c__String name
     * }
     */
    public static MemorySegment name(MemorySegment struct) {
        return struct.asSlice(name$OFFSET, name$LAYOUT.byteSize());
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * rosidl_runtime_c__String name
     * }
     */
    public static void name(MemorySegment struct, MemorySegment fieldValue) {
        MemorySegment.copy(fieldValue, 0L, struct, name$OFFSET, name$LAYOUT.byteSize());
    }

    private static final GroupLayout type$LAYOUT = (GroupLayout)$LAYOUT.select(groupElement("type"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * rosidl_runtime_c__type_description__FieldType type
     * }
     */
    public static final GroupLayout type$layout() {
        return type$LAYOUT;
    }

    private static final long type$OFFSET = $LAYOUT.byteOffset(groupElement("type"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * rosidl_runtime_c__type_description__FieldType type
     * }
     */
    public static final long type$offset() {
        return type$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * rosidl_runtime_c__type_description__FieldType type
     * }
     */
    public static MemorySegment type(MemorySegment struct) {
        return struct.asSlice(type$OFFSET, type$LAYOUT.byteSize());
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * rosidl_runtime_c__type_description__FieldType type
     * }
     */
    public static void type(MemorySegment struct, MemorySegment fieldValue) {
        MemorySegment.copy(fieldValue, 0L, struct, type$OFFSET, type$LAYOUT.byteSize());
    }

    private static final GroupLayout default_value$LAYOUT = (GroupLayout)$LAYOUT.select(groupElement("default_value"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * rosidl_runtime_c__String default_value
     * }
     */
    public static final GroupLayout default_value$layout() {
        return default_value$LAYOUT;
    }

    private static final long default_value$OFFSET = $LAYOUT.byteOffset(groupElement("default_value"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * rosidl_runtime_c__String default_value
     * }
     */
    public static final long default_value$offset() {
        return default_value$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * rosidl_runtime_c__String default_value
     * }
     */
    public static MemorySegment default_value(MemorySegment struct) {
        return struct.asSlice(default_value$OFFSET, default_value$LAYOUT.byteSize());
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * rosidl_runtime_c__String default_value
     * }
     */
    public static void default_value(MemorySegment struct, MemorySegment fieldValue) {
        MemorySegment.copy(fieldValue, 0L, struct, default_value$OFFSET, default_value$LAYOUT.byteSize());
    }

    /**
     * Obtains a slice of {@code arrayParam} which selects the array element at {@code index}.
     * The returned segment has address {@code arrayParam.address() + index * layout().byteSize()}
     */
    public static MemorySegment asSlice(MemorySegment array, long index) {
        return array.asSlice(layout().byteSize() * index);
    }

    /**
     * The size (in bytes) of this struct
     */
    public static long sizeof() { return layout().byteSize(); }

    /**
     * Allocate a segment of size {@code layout().byteSize()} using {@code allocator}
     */
    public static MemorySegment allocate(SegmentAllocator allocator) {
        return allocator.allocate(layout());
    }

    /**
     * Allocate an array of size {@code elementCount} using {@code allocator}.
     * The returned segment has size {@code elementCount * layout().byteSize()}.
     */
    public static MemorySegment allocateArray(long elementCount, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(elementCount, layout()));
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, Arena arena, Consumer<MemorySegment> cleanup) {
        return reinterpret(addr, 1, arena, cleanup);
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code elementCount * layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, long elementCount, Arena arena, Consumer<MemorySegment> cleanup) {
        return addr.reinterpret(layout().byteSize() * elementCount, arena, cleanup);
    }
}

