// Generated by jextract

package org.ros2.rcl;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * struct service_msgs__msg__ServiceEventInfo {
 *     uint8_t event_type;
 *     builtin_interfaces__msg__Time stamp;
 *     uint8_t client_gid[16];
 *     int64_t sequence_number;
 * }
 * }
 */
public class service_msgs__msg__ServiceEventInfo {

    service_msgs__msg__ServiceEventInfo() {
        // Should not be called directly
    }

    private static final GroupLayout $LAYOUT = MemoryLayout.structLayout(
        RclLib.C_CHAR.withName("event_type"),
        MemoryLayout.paddingLayout(3),
        builtin_interfaces__msg__Time.layout().withName("stamp"),
        MemoryLayout.sequenceLayout(16, RclLib.C_CHAR).withName("client_gid"),
        MemoryLayout.paddingLayout(4),
        RclLib.C_LONG.withName("sequence_number")
    ).withName("service_msgs__msg__ServiceEventInfo");

    /**
     * The layout of this struct
     */
    public static final GroupLayout layout() {
        return $LAYOUT;
    }

    private static final OfByte event_type$LAYOUT = (OfByte)$LAYOUT.select(groupElement("event_type"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * uint8_t event_type
     * }
     */
    public static final OfByte event_type$layout() {
        return event_type$LAYOUT;
    }

    private static final long event_type$OFFSET = $LAYOUT.byteOffset(groupElement("event_type"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * uint8_t event_type
     * }
     */
    public static final long event_type$offset() {
        return event_type$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * uint8_t event_type
     * }
     */
    public static byte event_type(MemorySegment struct) {
        return struct.get(event_type$LAYOUT, event_type$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * uint8_t event_type
     * }
     */
    public static void event_type(MemorySegment struct, byte fieldValue) {
        struct.set(event_type$LAYOUT, event_type$OFFSET, fieldValue);
    }

    private static final GroupLayout stamp$LAYOUT = (GroupLayout)$LAYOUT.select(groupElement("stamp"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * builtin_interfaces__msg__Time stamp
     * }
     */
    public static final GroupLayout stamp$layout() {
        return stamp$LAYOUT;
    }

    private static final long stamp$OFFSET = $LAYOUT.byteOffset(groupElement("stamp"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * builtin_interfaces__msg__Time stamp
     * }
     */
    public static final long stamp$offset() {
        return stamp$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * builtin_interfaces__msg__Time stamp
     * }
     */
    public static MemorySegment stamp(MemorySegment struct) {
        return struct.asSlice(stamp$OFFSET, stamp$LAYOUT.byteSize());
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * builtin_interfaces__msg__Time stamp
     * }
     */
    public static void stamp(MemorySegment struct, MemorySegment fieldValue) {
        MemorySegment.copy(fieldValue, 0L, struct, stamp$OFFSET, stamp$LAYOUT.byteSize());
    }

    private static final SequenceLayout client_gid$LAYOUT = (SequenceLayout)$LAYOUT.select(groupElement("client_gid"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * uint8_t client_gid[16]
     * }
     */
    public static final SequenceLayout client_gid$layout() {
        return client_gid$LAYOUT;
    }

    private static final long client_gid$OFFSET = $LAYOUT.byteOffset(groupElement("client_gid"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * uint8_t client_gid[16]
     * }
     */
    public static final long client_gid$offset() {
        return client_gid$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * uint8_t client_gid[16]
     * }
     */
    public static MemorySegment client_gid(MemorySegment struct) {
        return struct.asSlice(client_gid$OFFSET, client_gid$LAYOUT.byteSize());
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * uint8_t client_gid[16]
     * }
     */
    public static void client_gid(MemorySegment struct, MemorySegment fieldValue) {
        MemorySegment.copy(fieldValue, 0L, struct, client_gid$OFFSET, client_gid$LAYOUT.byteSize());
    }

    private static long[] client_gid$DIMS = { 16 };

    /**
     * Dimensions for array field:
     * {@snippet lang=c :
     * uint8_t client_gid[16]
     * }
     */
    public static long[] client_gid$dimensions() {
        return client_gid$DIMS;
    }
    private static final VarHandle client_gid$ELEM_HANDLE = client_gid$LAYOUT.varHandle(sequenceElement());

    /**
     * Indexed getter for field:
     * {@snippet lang=c :
     * uint8_t client_gid[16]
     * }
     */
    public static byte client_gid(MemorySegment struct, long index0) {
        return (byte)client_gid$ELEM_HANDLE.get(struct, client_gid$OFFSET, index0);
    }

    /**
     * Indexed setter for field:
     * {@snippet lang=c :
     * uint8_t client_gid[16]
     * }
     */
    public static void client_gid(MemorySegment struct, long index0, byte fieldValue) {
        client_gid$ELEM_HANDLE.set(struct, client_gid$OFFSET, index0, fieldValue);
    }

    private static final OfLong sequence_number$LAYOUT = (OfLong)$LAYOUT.select(groupElement("sequence_number"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * int64_t sequence_number
     * }
     */
    public static final OfLong sequence_number$layout() {
        return sequence_number$LAYOUT;
    }

    private static final long sequence_number$OFFSET = $LAYOUT.byteOffset(groupElement("sequence_number"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * int64_t sequence_number
     * }
     */
    public static final long sequence_number$offset() {
        return sequence_number$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * int64_t sequence_number
     * }
     */
    public static long sequence_number(MemorySegment struct) {
        return struct.get(sequence_number$LAYOUT, sequence_number$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * int64_t sequence_number
     * }
     */
    public static void sequence_number(MemorySegment struct, long fieldValue) {
        struct.set(sequence_number$LAYOUT, sequence_number$OFFSET, fieldValue);
    }

    /**
     * Obtains a slice of {@code arrayParam} which selects the array element at {@code index}.
     * The returned segment has address {@code arrayParam.address() + index * layout().byteSize()}
     */
    public static MemorySegment asSlice(MemorySegment array, long index) {
        return array.asSlice(layout().byteSize() * index);
    }

    /**
     * The size (in bytes) of this struct
     */
    public static long sizeof() { return layout().byteSize(); }

    /**
     * Allocate a segment of size {@code layout().byteSize()} using {@code allocator}
     */
    public static MemorySegment allocate(SegmentAllocator allocator) {
        return allocator.allocate(layout());
    }

    /**
     * Allocate an array of size {@code elementCount} using {@code allocator}.
     * The returned segment has size {@code elementCount * layout().byteSize()}.
     */
    public static MemorySegment allocateArray(long elementCount, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(elementCount, layout()));
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, Arena arena, Consumer<MemorySegment> cleanup) {
        return reinterpret(addr, 1, arena, cleanup);
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code elementCount * layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, long elementCount, Arena arena, Consumer<MemorySegment> cleanup) {
        return addr.reinterpret(layout().byteSize() * elementCount, arena, cleanup);
    }
}

